import { version } from '../data.mjs'

export const config = {
  // Whether we're publishing next or latest tags
  tag: 'next',
  // Minimum node version
  node: 18,
  // Site to download from
  fileUri: 'https://raw.githubusercontent.com',
  // Repository to download from
  repo: process.env.FS_REPO || 'freesewing/freesewing',
  // Branch to download from
  branch: process.env.FS_BRANCH || `v${version}`,
  i18n: [
    'account',
    'common',
    'patrons',
    'themes',
    'workbench',
    'errors',
    'i18n',
    'sde',
    'measurements',
    'optiongroups',
    'o_bella',
    'o_bent',
    'o_breanna',
    'o_brian',
    'o_titan',
    'parts',
    'plugin',
    'settings',
    'welcome',
  ],
  gitignore: `
# See https://help.github.com/ignore-files/ for more about ignoring files.

# dependencies
node_modules

# builds
dist
.next

# misc
.DS_Store
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*

`,
  fetch: {
    config: [
      {
        from: 'measurements.mjs',
        to: 'shared/config/measurements.mjs',
      },
    ],
    sites: [
      {
        from: 'sde/env.local',
        to: 'sde/.env.local',
      },
      'sde/i18n.config.mjs',
      'sde/next-i18next.config.js',
      'sde/next.config.mjs',
      'sde/package.json',
      'sde/postcss.config.js',
      'sde/site.config.mjs',
      'sde/tailwind.config.mjs',
      'sde/hooks/use-design.mjs',
      'sde/components/dynamic-org-docs.mjs',
      'sde/components/feeds.mjs',
      'sde/components/search.mjs',
      'sde/components/header/design-picker.mjs',
      'sde/components/header/index.mjs',
      'sde/components/navigation/modal-menu.mjs',
      'sde/components/layouts/bare.mjs',
      'sde/components/layouts/default.mjs',
      'sde/components/layouts/workbench.mjs',
      'sde/components/wrappers/page.mjs',
      'sde/design/from-bent/src/back.mjs',
      'sde/design/from-bent/src/front.mjs',
      'sde/design/from-bent/src/index.mjs',
      'sde/design/from-bent/src/top-sleeve.mjs',
      'sde/design/from-bent/src/under-sleeve.mjs',
      'sde/design/from-bent/i18n/de.json',
      'sde/design/from-bent/i18n/en.json',
      'sde/design/from-bent/i18n/es.json',
      'sde/design/from-bent/i18n/fr.json',
      'sde/design/from-bent/i18n/index.mjs',
      'sde/design/from-bent/i18n/nl.json',
      'sde/design/from-bent/i18n/uk.json',
      'sde/design/from-bella/en.json',
      'sde/design/from-bella/src/back.mjs',
      'sde/design/from-bella/src/front.mjs',
      'sde/design/from-bella/src/index.mjs',
      'sde/design/from-bella/i18n/de.json',
      'sde/design/from-bella/i18n/en.json',
      'sde/design/from-bella/i18n/es.json',
      'sde/design/from-bella/i18n/fr.json',
      'sde/design/from-bella/i18n/index.mjs',
      'sde/design/from-bella/i18n/nl.json',
      'sde/design/from-bella/i18n/uk.json',
      'sde/design/from-breanna/src/back.mjs',
      'sde/design/from-breanna/src/front.mjs',
      'sde/design/from-breanna/src/index.mjs',
      'sde/design/from-breanna/src/sleeve.mjs',
      'sde/design/from-breanna/i18n/de.json',
      'sde/design/from-breanna/i18n/en.json',
      'sde/design/from-breanna/i18n/es.json',
      'sde/design/from-breanna/i18n/fr.json',
      'sde/design/from-breanna/i18n/index.mjs',
      'sde/design/from-breanna/i18n/nl.json',
      'sde/design/from-breanna/i18n/uk.json',
      'sde/design/from-brian/i18n/de.json',
      'sde/design/from-brian/i18n/en.json',
      'sde/design/from-brian/i18n/es.json',
      'sde/design/from-brian/i18n/fr.json',
      'sde/design/from-brian/i18n/index.mjs',
      'sde/design/from-brian/i18n/nl.json',
      'sde/design/from-brian/i18n/uk.json',
      'sde/design/from-brian/src/back.mjs',
      'sde/design/from-brian/src/front.mjs',
      'sde/design/from-brian/src/index.mjs',
      'sde/design/from-brian/src/sleeve.mjs',
      'sde/design/from-titan/i18n/de.json',
      'sde/design/from-titan/i18n/en.json',
      'sde/design/from-titan/i18n/es.json',
      'sde/design/from-titan/i18n/fr.json',
      'sde/design/from-titan/i18n/index.mjs',
      'sde/design/from-titan/i18n/nl.json',
      'sde/design/from-titan/i18n/uk.json',
      'sde/design/from-titan/src/back.mjs',
      'sde/design/from-titan/src/front.mjs',
      'sde/design/from-titan/src/index.mjs',
      'sde/design/from-scratch/i18n/de.json',
      'sde/design/from-scratch/i18n/en.json',
      'sde/design/from-scratch/i18n/es.json',
      'sde/design/from-scratch/i18n/fr.json',
      'sde/design/from-scratch/i18n/index.mjs',
      'sde/design/from-scratch/i18n/nl.json',
      'sde/design/from-scratch/i18n/uk.json',
      'sde/design/from-scratch/src/index.mjs',
      'sde/design/from-scratch/src/scratch.mjs',
      'sde/design/tutorial/i18n/de.json',
      'sde/design/tutorial/i18n/en.json',
      'sde/design/tutorial/i18n/es.json',
      'sde/design/tutorial/i18n/fr.json',
      'sde/design/tutorial/i18n/index.mjs',
      'sde/design/tutorial/i18n/nl.json',
      'sde/design/tutorial/i18n/uk.json',
      'sde/design/tutorial/src/bib.mjs',
      'sde/design/tutorial/src/index.mjs',
      'sde/public/brands/algolia.svg',
      'sde/public/brands/bugsnag.svg',
      'sde/public/brands/crowdin.svg',
      'sde/public/brands/netlify.svg',
      'sde/public/brands/vercel.svg',
      'sde/pages/_app.mjs',
      'sde/pages/design.mjs',
      'sde/pages/index.mjs',
      'sde/pages/support.mjs',
      'sde/pages/code/index.mjs',
      'sde/pages/design/[design].mjs',
      'sde/pages/docs/index.mjs',
      'sde/pages/sde/en.yaml',
      'sde/pages/sde/index.mjs',
      'sde/pages/sets/[id].mjs',
      'sde/pages/signup/index.mjs',
      'sde/pages/patterns/index.mjs',
      'sde/pages/patterns/[id]/edit.mjs',
      'sde/pages/patterns/[id]/index.mjs',
      'sde/pages/signin/index.mjs',
      'sde/pages/signin/callback/[provider].mjs',
      'sde/pages/account/[platform].mjs',
      'sde/pages/account/bio.mjs',
      'sde/pages/account/compare.mjs',
      'sde/pages/account/consent.mjs',
      'sde/pages/account/control.mjs',
      'sde/pages/account/email.mjs',
      'sde/pages/account/export.mjs',
      'sde/pages/account/github.mjs',
      'sde/pages/account/img.mjs',
      'sde/pages/account/index.mjs',
      'sde/pages/account/language.mjs',
      'sde/pages/account/mfa.mjs',
      'sde/pages/account/newsletter.mjs',
      'sde/pages/account/password.mjs',
      'sde/pages/account/privacy.mjs',
      'sde/pages/account/reload.mjs',
      'sde/pages/account/remove.mjs',
      'sde/pages/account/restrict.mjs',
      'sde/pages/account/units.mjs',
      'sde/pages/account/username.mjs',
      'sde/pages/account/apikeys/[id].mjs',
      'sde/pages/account/apikeys/index.mjs',
      'sde/pages/account/bookmarks/[id].mjs',
      'sde/pages/account/bookmarks/index.mjs',
      'sde/pages/account/sets/[id].mjs',
      'sde/pages/account/sets/index.mjs',
      'sde/pages/account/patterns/index.mjs',
      'sde/pages/account/patterns/[id]/edit.mjs',
      'sde/pages/account/patterns/[id]/index.mjs',
      'shared/config/cloudflare.mjs',
      'shared/config/designs.mjs',
      'shared/config/freesewing.config.mjs',
      'shared/config/i18n.config.mjs',
      'shared/config/next.mjs',
      'shared/config/paypal.mjs',
      'shared/config/playwright.mjs',
      'shared/config/postcss.config.js',
      'shared/config/tailwind-force.html',
      'shared/config/tailwind.config.mjs',
    ],
  },
}
