import { version } from '../data.mjs'

export const config = {
  // Whether we're publishing next or latest tags
  tag: 'next',
  // Minimum node version
  node: 16,
  // Site to download from
  fileUri: 'https://raw.githubusercontent.com',
  // Repository to download from
  repo: process.env.FS_REPO || 'freesewing/freesewing',
  // Branch to download from
  branch: process.env.FS_BRANCH || version,
  i18n: [
    'account',
    'common',
    'patrons',
    'themes',
    'workbench',
    'errors',
    'i18n',
    'lab',
    'measurements',
    'optiongroups',
    'o_bella',
    'o_bent',
    'o_breanna',
    'o_brian',
    'o_titan',
    'parts',
    'plugin',
    'settings',
    'welcome',
  ],
  gitignore: `
# See https://help.github.com/ignore-files/ for more about ignoring files.

# dependencies
node_modules

# builds
dist
.next

# misc
.DS_Store
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*

# e2e test results
playwright-report
`,
  fetch: {
    config: [
      {
        from: 'measurements.mjs',
        to: 'shared/config/measurements.mjs',
      },
    ],
    sites: [
      'shared/utils.mjs',
      'shared/designs/index.js',
      'shared/config/freesewing.mjs',
      'shared/config/i18n.config.mjs',
      'shared/config/next.mjs',
      'shared/config/postcss.config.js',
      'shared/config/tailwind-force.html',
      'shared/config/tailwind.config.js',
      'shared/hooks/useGist.mjs',
      'shared/hooks/useLocalStorage.mjs',
      'shared/hooks/useTheme.mjs',
      'shared/mdx/compiler.mjs',
      'shared/mdx/loader.mjs',
      'shared/mdx/mdx-plugin-toc.mjs',
      'shared/mdx/remark-intro-plugin.mjs',
      'shared/strapi/loader.js',
      'shared/strapi/qa.mjs',
      'shared/themes/dark.js',
      'shared/themes/hax0r.js',
      'shared/themes/index.js',
      'shared/themes/lgbtq.js',
      'shared/themes/light.js',
      'shared/themes/runtime.mjs',
      'shared/styles/code.css',
      'shared/styles/globals.css',
      'shared/styles/svg-freesewing-draft.css',
      'shared/prebuild/contributors.mjs',
      'shared/prebuild/feed.mjs',
      'shared/prebuild/i18n-only.mjs',
      'shared/prebuild/i18n.mjs',
      'shared/prebuild/index.mjs',
      'shared/prebuild/lab.mjs',
      'shared/prebuild/md-intro.mjs',
      'shared/prebuild/mdx.mjs',
      'shared/prebuild/navigation.mjs',
      'shared/prebuild/patrons.mjs',
      'shared/prebuild/strapi.mjs',
      'shared/prebuild/og/index.mjs',
      'shared/components/breadcrumbs.mjs',
      'shared/components/code.mjs',
      'shared/components/copy-to-clipboard.mjs',
      'shared/components/docs-link.mjs',
      'shared/components/icons.mjs',
      'shared/components/json.mjs',
      'shared/components/lightbox.mjs',
      'shared/components/loader.mjs',
      'shared/components/modal.mjs',
      'shared/components/page-link.mjs',
      'shared/components/picker.mjs',
      'shared/components/popout.mjs',
      'shared/components/raw-span.mjs',
      'shared/components/ribbon.mjs',
      'shared/components/spinner.mjs',
      'shared/components/web-link.mjs',
      'shared/components/wordmark.mjs',
      'shared/components/worm.mjs',
      'shared/components/yaml.mjs',
      'shared/components/error/error-boundary.mjs',
      'shared/components/error/reset-buttons.mjs',
      'shared/components/error/view.mjs',
      'shared/components/icons/flip.js',
      'shared/components/icons/rotate.js',
      'shared/components/locale-picker/index.mjs',
      'shared/components/locale-picker/locales.de.yaml',
      'shared/components/locale-picker/locales.en.yaml',
      'shared/components/locale-picker/locales.es.yaml',
      'shared/components/locale-picker/locales.fr.yaml',
      'shared/components/locale-picker/locales.nl.yaml',
      'shared/components/logos/cc-by.mjs',
      'shared/components/logos/cc.mjs',
      'shared/components/logos/freesewing.mjs',
      'shared/components/logos/osi.mjs',
      'shared/components/mdx/figure.mjs',
      'shared/components/mdx/highlight.mjs',
      'shared/components/mdx/http.mjs',
      'shared/components/mdx/index.mjs',
      'shared/components/mdx/mermaid.mjs',
      'shared/components/mdx/prev-next.mjs',
      'shared/components/mdx/read-more.mjs',
      'shared/components/mdx/tabbed-example.mjs',
      'shared/components/mdx/tabs.mjs',
      'shared/components/mdx/youtube.mjs',
      'shared/components/navigation/aside.mjs',
      'shared/components/navigation/primary.mjs',
      'shared/components/robot/index.mjs',
      'shared/components/robot/poses.mjs',
      'shared/components/theme-picker/index.mjs',
      'shared/components/theme-picker/themes.de.yaml',
      'shared/components/theme-picker/themes.en.yaml',
      'shared/components/theme-picker/themes.es.yaml',
      'shared/components/theme-picker/themes.fr.yaml',
      'shared/components/theme-picker/themes.nl.yaml',
      'shared/components/wrappers/img.mjs',
      'shared/components/wrappers/mdx.mjs',
      'shared/components/wrappers/page.mjs',
      'shared/components/wrappers/toc.mjs',
      'shared/components/wrappers/workbench.mjs',
      'shared/components/workbench/gist.mjs',
      'shared/components/workbench/logs.mjs',
      'shared/components/workbench/preloaders.mjs',
      'shared/components/workbench/sample.mjs',
      'shared/components/workbench/edit/index.mjs',
      'shared/components/workbench/edit/gist-validator.mjs',
      'shared/components/workbench/exporting/export-handler.mjs',
      'shared/components/workbench/exporting/export-worker.js',
      'shared/components/workbench/exporting/index.mjs',
      'shared/components/workbench/exporting/pdf-maker.mjs',
      'shared/components/workbench/inputs/design-option-count.mjs',
      'shared/components/workbench/inputs/design-option-list.mjs',
      'shared/components/workbench/inputs/design-option-pct-deg.mjs',
      'shared/components/workbench/inputs/measurement.mjs',
      'shared/components/workbench/measurements/index.mjs',
      'shared/components/workbench/draft/circle.mjs',
      'shared/components/workbench/draft/defs.mjs',
      'shared/components/workbench/draft/error.mjs',
      'shared/components/workbench/draft/index.mjs',
      'shared/components/workbench/draft/part.mjs',
      'shared/components/workbench/draft/path.mjs',
      'shared/components/workbench/draft/point.mjs',
      'shared/components/workbench/draft/snippet.mjs',
      'shared/components/workbench/draft/stack.mjs',
      'shared/components/workbench/draft/svg.mjs',
      'shared/components/workbench/draft/text.mjs',
      'shared/components/workbench/draft/utils.mjs',
      'shared/components/workbench/layout/default.mjs',
      'shared/components/workbench/layout/cut/index.mjs',
      'shared/components/workbench/layout/cut/plugin-cut-layout.mjs',
      'shared/components/workbench/layout/cut/settings.mjs',
      'shared/components/workbench/layout/print/index.mjs',
      'shared/components/workbench/layout/print/orientation-picker.mjs',
      'shared/components/workbench/layout/print/pagesize-picker.mjs',
      'shared/components/workbench/layout/plugin-layout-part.mjs',
      'shared/components/workbench/layout/print/settings.mjs',
      'shared/components/workbench/layout/draft/buttons.mjs',
      'shared/components/workbench/layout/draft/index.mjs',
      'shared/components/workbench/layout/draft/stack.mjs',
      'shared/components/workbench/menu/index.mjs',
      'shared/components/workbench/menu/view.mjs',
      'shared/components/workbench/menu/design-options/index.mjs',
      'shared/components/workbench/menu/design-options/option-group.mjs',
      'shared/components/workbench/menu/design-options/option-input.mjs',
      'shared/components/workbench/menu/design-options/option-value.mjs',
      'shared/components/workbench/menu/design-options/option.mjs',
      'shared/components/workbench/menu/test-design-options/index.mjs',
      'shared/components/workbench/menu/test-design-options/option.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-bool.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-list.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-mm.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-nr.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-only.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-sa-bool.mjs',
      'shared/components/workbench/menu/core-settings/core-setting-sa-mm.mjs',
      'shared/components/workbench/menu/core-settings/index.mjs',
      'shared/components/workbench/menu/core-settings/setting.mjs',
      'shared/components/workbench/menu/xray/attributes.mjs',
      'shared/components/workbench/menu/xray/disable.mjs',
      'shared/components/workbench/menu/xray/index.mjs',
      'shared/components/workbench/menu/xray/list.mjs',
      'shared/components/workbench/menu/xray/log.mjs',
      'shared/components/workbench/menu/xray/path-ops.mjs',
      'shared/components/workbench/menu/xray/path.mjs',
      'shared/components/workbench/menu/xray/point.mjs',
      'shared/components/workbench/menu/xray/reset.mjs',
      'lab/components/about.mjs',
      'lab/components/design-picker.mjs',
      'lab/components/header.mjs',
      'lab/components/layouts/bare.mjs',
      'lab/components/layouts/lab.mjs',
      'lab/components/wrappers/layout.mjs',
      'lab/components/wrappers/page.mjs',
    ],
  },
}
