##### Labeler #####
labelPRBasedOnFilePath:
  # Add 'label1' to any changes within 'example' folder or any subfolders
  ":package: aaron": [ packages/aaron/* ]
  ":package: albert": [ packages/albert/* ]
  ":package: bee": [ packages/bee/* ]
  ":package: bella": [ packages/bella/* ]
  ":package: benjamin": [ packages/benjamin/* ]
  ":package: bent": [ packages/bent/* ]
  ":package: breanna": [ packages/breanna/* ]
  ":package: brian": [ packages/brian/* ]
  ":package: bruce": [ packages/bruce/* ]
  ":package: carlita": [ packages/carlita/* ]
  ":package: carlton": [ packages/carlton/* ]
  ":package: cathrin": [ packages/cathrin/* ]
  ":package: charlie": [ packages/charlie/* ]
  ":package: components": [ packages/components/* ]
  ":package: core": [ packages/core/* ]
  ":package: cornelius": [ packages/cornelius/* ]
  ":package: create-freesewing-pattern": [ packages/create-freesewing-pattern/* ]
  ":package: css-theme": [ packages/css-theme/* ]
  ":package: diana": [ packages/diana/* ]
  ":package: examples": [ packages/examples/* ]
  ":package: florence": [ packages/florence/* ]
  ":package: florent": [ packages/florent/* ]
  ":package: gatsby-remark-jargon": [ packages/gatsby-remark-jargon/* ]
  ":package: holmes": [ packages/holmes/* ]
  ":package: hortensia": [ packages/hortensia/* ]
  ":package: huey": [ packages/huey/* ]
  ":package: hugo": [ packages/hugo/* ]
  ":package: i18n": [ packages/i18n/* ]
  ":package: jaeger": [ packages/jaeger/* ]
  ":package: legend": [ packages/legend/* ]
  ":package: lunetius": [ packages/lunetius/* ]
  ":package: models": [ packages/models/* ]
  ":package: mui-theme": [ packages/mui-theme/* ]
  ":package: paco": [ packages/paco/* ]
  ":package: pattern-info": [ packages/pattern-info/* ]
  ":package: penelope": [ packages/penelope/* ]
  ":package: plugin-banner": [ packages/plugin-banner/* ]
  ":package: plugin-bartack": [ packages/plugin-bartack/* ]
  ":package: plugin-bundle": [ packages/plugin-bundle/* ]
  ":package: plugin-bust": [ packages/plugin-bust/* ]
  ":package: plugin-buttons": [ packages/plugin-buttons/* ]
  ":package: plugin-cutonfold": [ packages/plugin-cutonfold/* ]
  ":package: plugin-dimension": [ packages/plugin-dimension/* ]
  ":package: plugin-export-dxf": [ packages/plugin-export-dxf/* ]
  ":package: plugin-flip": [ packages/plugin-flip/* ]
  ":package: plugin-gore": [ packages/plugin-gore/* ]
  ":package: plugin-grainline": [ packages/plugin-grainline/* ]
  ":package: plugin-i18n": [ packages/plugin-i18n/* ]
  ":package: plugin-logo": [ packages/plugin-logo/* ]
  ":package: plugin-measurements": [ packages/plugin-measurements/* ]
  ":package: plugin-mirror": [ packages/plugin-mirror/* ]
  ":package: plugin-notches": [ packages/plugin-notches/* ]
  ":package: plugin-round": [ packages/plugin-round/* ]
  ":package: plugin-scalebox": [ packages/plugin-scalebox/* ]
  ":package: plugin-sprinkle": [ packages/plugin-sprinkle/* ]
  ":package: plugin-svgattr": [ packages/plugin-svgattr/* ]
  ":package: plugin-theme": [ packages/plugin-theme/* ]
  ":package: plugin-title": [ packages/plugin-title/* ]
  ":package: plugin-validate": [ packages/plugin-validate/* ]
  ":package: plugin-versionfree-svg": [ packages/plugin-versionfree-svg/* ]
  ":package: prettier-config": [ packages/prettier-config/* ]
  ":package: remark-jargon": [ packages/remark-jargon/* ]
  ":package: rendertest": [ packages/rendertest/* ]
  ":package: sandy": [ packages/sandy/* ]
  ":package: shin": [ packages/shin/* ]
  ":package: simon": [ packages/simon/* ]
  ":package: simone": [ packages/simone/* ]
  ":package: snapseries": [ packages/snapseries/* ]
  ":package: strapi": [ packages/strapi/* ]
  ":package: sven": [ packages/sven/* ]
  ":package: tamiko": [ packages/tamiko/* ]
  ":package: teagan": [ packages/teagan/* ]
  ":package: theo": [ packages/theo/* ]
  ":package: tiberius": [ packages/tiberius/* ]
  ":package: titan": [ packages/titan/* ]
  ":package: trayvon": [ packages/trayvon/* ]
  ":package: tutorial": [ packages/tutorial/* ]
  ":package: ursula": [ packages/ursula/* ]
  ":package: utils": [ packages/utils/* ]
  ":package: wahid": [ packages/wahid/* ]
  ":package: walburga": [ packages/walburga/* ]
  ":package: waralee": [ packages/waralee/* ]
  ":package: yuri": [ packages/yuri/* ]
  ":book: documentation": [ markdown/* ]
  ":test_tube: tests": [ tests/* ]
  ":gear: configuration": [ "config/*", ".github/*" ]

labelerFlags:
  labelOnPRUpdates: true

##### Greetings #####
firstPRWelcomeComment: >
  Thanks for opening this pull request 😀
  Please take a moment to read [our contributing guidelines](https://github.com/freesewing/freesewing/blob/develop/CONTRIBUTING.md).

firstPRMergeComment: >
  Awesome work 🎉 congrats on your first merged pull request 🤓

  ![Welcome to the nerd zone](https://media.giphy.com/media/l0HlHFRbmaZtBRhXG/giphy.gif)

firstIssueWelcomeComment: >
  Thanks for opening your first issue here at FreeSewing 🥇

  One of our contributors should triage this soon so that it gets some attention.
  If it's urgent, you can [join us on Discord](https://discord.freesewing.org/)
  where we tend to hang out.

