/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Обліковий запис",
  "blog": "Блог",
  "commumity": "Спільнота",
  "designs": "Дизайни",
  "docs": "Документація",
  "patternInstructions": "Інструкції до викрійок",
  "patternOptions": "Налаштування викрійок",
  "requiredMeasurements": "Необхідні вимірювання",
  "showcase": "Готові проєкти",
  "sloganCome": "Приходьте за викрійками",
  "sloganStay": "Залишайтеся заради спільноти",
  "support": "Підтримка"
}

export default common
