/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const docs = {
  "thingIsDeprecated": "{thing} є застарілим",
  "weRecommendThingInstead": "Ми рекомендуємо {thing} замість цього"
}

export default docs
