/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "Сторінку не знайдено",
  "confirmationNotFound": "Якщо Ви перейшли на дану сторінку через посилання в електронному листі, ми будемо вдячні, якщо Ви повідомите нам про цю проблему.",
  "emailExists": "У нас вже є користувач з цією адресою електронної пошти. Можливо, Ви хочете авторизуватися?",
  "networkError": "Помилка сервера або мережі",
  "notAValidImageFormat": "Неприпустимий формат зображення",
  "requestFailedWithStatusCode400": "Не вдалося виконати запит",
  "requestFailedWithStatusCode401": "Помилка аутентифікації",
  "requestFailedWithStatusCode403": "Заборонено",
  "requestFailedWithStatusCode500": "Виникла неочікувана проблема. Будь ласка, повідомте про це.",
  "something": "Щось пішло не так"
}

export default errors
