/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const homepage = {
  "scrollDownToLearnMore": "Прокрутіть вниз, щоб дізнатися більше про FreeSewing і безкоштовно скористатися його функціями"
}

export default homepage
