/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "Німецька",
  "en": "Англійська",
  "es": "Іспанська",
  "fr": "Французька",
  "nl": "Нідерландська"
}

export default i18n
