/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "Дивіться <a href='/docs/sewing/basting/'>Зметування</a> у <a href='/docs/sewing'> документація до шиття</a>",
  "coverlock.d": "Дивіться <a href='/docs/sewing/coverlock/'>Каверлок</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "cutting.d": "Дивіться <a href='/docs/sewing/cutting/'>Вирізання</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "darts.d": "Дивіться <a href='/docs/sewing/darts/'>Виточки</a> у<a href='/docs/sewing'>Документація до шиття</a>",
  "doubleWeltPockets.d": "Дивіться <a href='/docs/sewing/double-welt-pockets/'>Кишеня з подвійною листочкою</a> у<a href='/docs/sewing'>Документація до шиття</a>",
  "ease.d": "Дивіться <a href='/docs/sewing/ease/'>Свобода облягання</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "edgestitch.d": "Дивіться <a href='/docs/sewing/edgestitching/'>Шов по краю</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "fabricGrain.d": "Дивіться <a href='/docs/sewing/fabric-grain/'>Нитка основа тканини</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "goodSidesTogether.d": "Дивіться <a href='/docs/sewing/good-sides-together/'>Лицьові сторони одна до одної</a> у <a href='/docs/sewing/'>Документація до шиття</a>",
  "onTheFold.d": "Дивіться <a href='/docs/sewing/on-the-fold/'>На згині</a> у <a href='/docs/sewing/'>Документація до шиття</a>",
  "hemming.d": "Дивіться <a href='/docs/sewing/hemming/'>Підшивання краю</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "jersey.d": "Дивіться <a href='/docs/sewing/jersey/'>Джерсі</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "knitBinding.d": "Дивіться <a href='/docs/sewing/knit-binding/'>Трикотажна бейка</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "knitFabric.d": "Дивіться <a href='/docs/sewing/knit-fabric/'>Трикотаж</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "pinning.d": "Дивіться <a href='/docs/sewing/pinning/'>Зметування булавками</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "rayon.d": "Дивіться <a href='/docs/sewing/rayon/'>Віскоза</a> у<a href='/docs/sewing'>Документація до шиття</a>",
  "sa.d": "Дивіться <a href='/docs/sewing/seam-allowance/'>Припуск на шов</a> у <a href='/docs/sewing'> Документація до шиття</a>",
  "serger.d": "Дивіться <a href='/docs/sewing/serger/'>Оверлок</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "slipstitch.d": "Дивіться <a href='/docs/sewing/slipstitch/'>Потайний шов</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "topstitching.d": "Дивіться <a href='/docs/sewing/topstitching/'>Оздоблювальний шов</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "trimming.d": "Дивіться <a href='/docs/sewing/trimming/'>Підрізання припусків на шов</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "twinNeedle.d": "Дивіться <a href='/docs/sewing/twin-neelde/'>Подвійна голка</a> у <a href='/docs/sewing'>Документація до шиття</a>",
  "zigZag.d": "Дивіться <a href='/docs/sewing/zig-zag-stitch/'>шов \"Зіг-заг\"</a> у<a href='/docs/sewing'>Документація до пошиття</a>",
  "freesewing.d": "<b>FreeSewing</b> є платформою з відкритим кодом для створення швейних викрійок, які адаптуються під виміри користувача",
  "patternOptions.d": "<b>Налаштування викрійки</b> дозволяє Вам змінити дизайн викрійки за Вашими побажаннями",
  "draftSettings.d": "<b>налаштування чернетки</b> надає Вам контроль над генерацією викрійки",
  "patrons.d": "Патрони фінансово підтримують FreeSewing. Вони є лояльними прихильниками, які забезпечують стійке майбутнє для freesewing.org, нашого коду, викрійок та нашої спільноти.",
  "msf.d": "Médecins Sans Frontières/Лікарі без кордонів – Більше на <a href='https://msf.org/'>msf.org</a>"
}

export default jargon
