/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const measurements = {
  "ankle": "Обхват щиколотки",
  "biceps": "Обхват біцепсів",
  "bustFront": "Передній напівобхват грудей",
  "bustPointToUnderbust": "Центр грудей до підгруддя",
  "bustSpan": "Центр грудей",
  "chest": "Обхват грудей",
  "crossSeam": "Посадка",
  "crossSeamFront": "Посадка спереду",
  "head": "Обхват голови",
  "heel": "Обхват підйому",
  "highBustFront": "Напівобхват над грудьми",
  "highBust": "Обхват над грудьми",
  "hips": "Обхват тазу",
  "hpsToBust": "Від плеча до грудей",
  "hpsToWaistBack": "Від плеча до талії ззаду",
  "hpsToWaistFront": "Від плеча до талії спереду",
  "inseam": "Внутрішній шов",
  "knee": "Обхват коліна",
  "neck": "Обхват шиї",
  "seat": "Обхват стегон",
  "seatBack": "Напівобхват стегон",
  "crotchDepth": "Висота сидіння",
  "shoulderSlope": "Нахил плеча",
  "shoulderToElbow": "Від плеча до ліктя",
  "shoulderToShoulder": "Ширина плечей",
  "shoulderToWrist": "Від плеча до зап'ястя",
  "underbust": "Підгруддя",
  "upperLeg": "Обхват верху ноги",
  "waist": "Обхват талії",
  "waistBack": "Ширина талії ззаду",
  "waistToArmhole": "Від талії до пройми",
  "waistToFloor": "Від талії до підлоги",
  "waistToHips": "Талія до кісточки таза",
  "waistToKnee": "Талія до коліна",
  "waistToSeat": "Від талії до стегон",
  "waistToUnderbust": "Від талії до підгруддя",
  "waistToUpperLeg": "Від талії до початку ноги",
  "wrist": "Обхват зап'ясть"
}

export default measurements
