/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Спуск пройми",
  "armholeDrop.d": "Опускає пройму на обрану відстань. Негативний показик підіймає пройму.",
  "backlineBend.t": "Задня частина пройми",
  "backlineBend.d": "Визначає форму/криву задньої частини пройми.",
  "hipsEase.t": "Свобода облягяння на животі",
  "hipsEase.d": "Відсоток свободи облягання на животі.",
  "necklineBend.t": "Форма горловини",
  "necklineBend.d": "Визначає форму/криву горловини спереду.",
  "necklineDrop.t": "Спуск горловини",
  "necklineDrop.d": "Процент відкриття шиї спереду.",
  "shoulderStrapPlacement.t": "Розташування лямки",
  "shoulderStrapPlacement.d": "Визначає розташування лямки ближче до шиї (нижчі номери) або ближче до плеча (вищі номери).",
  "shoulderStrapWidth.t": "Ширина лямки",
  "shoulderStrapWidth.d": "Визначає ширину лямок.",
  "stretchFactor.t": "Розтяжність",
  "stretchFactor.d": "Визначає горизонтальне зменшення свободи облягання."
}

export default o_aaron
