/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Відкриття спини",
  "backOpening.d": "Контролює відкриття на задній частині фартука",
  "chestDepth.t": "Довжина лямки",
  "chestDepth.d": "Контролює довжину лямки",
  "lengthBonus.t": "Додаткова довжина",
  "lengthBonus.d": "Контролює довжину фартука",
  "bibLength.t": "Довжина нагрудної пройми",
  "bibLength.d": "Контролює довжину нагрудної пройми",
  "bibWidth.t": "Ширина нагрудної пройми",
  "bibWidth.d": "Контролює ширину нагрудної пройми",
  "strapWidth.t": "Ширина лямки",
  "strapWidth.d": "Контролює ширину лямки"
}

export default o_albert
