/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Згин рукава",
  "sleeveBend.d": "Керує кутом згину рукава в лікті.",
  "sleevecapHeight.t": "Висота окату",
  "sleevecapHeight.d": "Керує висотою окату рукава."
}

export default o_bent
