/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Рихтувальна тасьма",
  "adjustmentRibbon.d": "Додавати чи не додавати рихтувальну тасьму в елементи викрійки",
  "bandLength.t": "Band length",
  "bandLength.d": "Length of the band",
  "tipWidth.t": "Ширина країв",
  "tipWidth.d": "Ширина чи висота країв бантика",
  "knotWidth.t": "Ширина вузлика",
  "knotWidth.d": "Ширина перемички (місця зав'язування краватки)",
  "bowLength.t": "Довжина бантика",
  "bowLength.d": "Довжина бантика (у зав'язаному стані)",
  "bowStyle.t": "Форма бантика",
  "bowStyle.d": "Загальна форма бантика",
  "endStyle.t": "Форма стрічок",
  "endStyle.d": "Форма стрічок під бантиком",
  "collarEase.t": "Свобода коміра",
  "collarEase.d": "Свобода облягання коміра навколо шиї",
  "ribbonWidth.t": "Ширина тасьми",
  "ribbonWidth.d": "Ширина тасьми (стрічки)"
}

export default o_benjamin
