/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bob = {
  "neckRatio.t": "Шийний зріз",
  "neckRatio.d": "Керує діаметром шийного зрізу відповідно до розміру слинявчика",
  "widthRatio.t": "Ширина",
  "widthRatio.d": "Керує загальною шириною слинявчика",
  "lengthRatio.t": "Довжина",
  "lengthRatio.d": "Керує загальною довжиною слинявчика",
  "headSize.t": "Розмір голови",
  "headSize.d": "Обхват голови, на який має налізати слинявчик"
}

export default o_bob
