/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Пахова вставка",
  "bulge.d": "Керує кутом пахової вставки для регулювання простору в передній мішковині.",
  "legBonus.t": "Додаткова довжина",
  "legBonus.d": "Збільшує загальну довжину по нозі.",
  "rise.t": "Посадка",
  "rise.d": "Керує висотою посадки на талії. Негативний показник зробить посадку нижчою.",
  "stretch.t": "Еластичність",
  "stretch.d": "Керує негативною свободою облягання.",
  "legStretch.t": "Обхват ноги",
  "legStretch.d": "Для найкращого результату рекомендується дещо туга посадка на нозі — ніяких пройм.",
  "backRise.t": "Посадка ззаду",
  "backRise.d": "Керує відсотком висоти посадки ззаду."
}

export default o_bruce
