/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Плечова виточка",
  "shoulderDart.d": "Додавати чи не додавати виточку на плечі для заокруглення спини",
  "shoulderDartSize.t": "Розмір плечової виточки",
  "shoulderDartSize.d": "Ширина (розмір) плечової виточки",
  "shoulderDartLength.t": "Довжина плечової виточки",
  "shoulderDartLength.d": "Загальна довжина плечової виточки",
  "waistDart.t": "Поясна виточка",
  "waistDart.d": "Додавати чи не додавати виточки на талії для заокруглення спини",
  "waistDartSize.t": "Розмір поясної виточки",
  "waistDartSize.d": "Ширина (розмір) виточки на талії",
  "waistDartLength.t": "Довжина поясної виточки",
  "waistDartLength.d": "Загальна довжина виточки на талії",
  "verticalEase.t": "Вертикальна свобода облягання",
  "verticalEase.d": "Керує свободою облягання, що розподіляється по довжині виробу",
  "waistEase.t": "Свобода облягання на талії",
  "waistEase.d": "Відсоток свободи облягання на талії",
  "primaryBustDart.t": "Грудна виточка",
  "primaryBustDart.d": "Керує розташуванням виточки для формування ліфу",
  "primaryBustDartLength.t": "Довжина грудної виточки",
  "primaryBustDartLength.d": "Загальна довжина виточки на грудях",
  "secondaryBustDart.t": "Вторинна грудна виточка",
  "secondaryBustDart.d": "За бажанням можна додати вторинну виточку на грудях для подальшого формування ліфу",
  "secondaryBustDartLength.t": "Довжина вторинної грудної виточки",
  "secondaryBustDartLength.d": "Загальна довжина вторинної виточки на грудях",
  "primaryBustDartShaping.t": "Формування грудних виточок",
  "primaryBustDartShaping.d": "Керує співвідношенням між головними та вторинними виточками на грудях"
}

export default o_breanna
