/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlita = {
  "contour.t": "Contour",
  "contour.d": "Controls how sharply the princess seam is contoured."
}

export default o_carlita
