/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlton = {
  "seatEase.t": "Seat ease",
  "seatEase.d": "Amount of ease around your bum",
  "pocketPlacementHorizontal.t": "Horizontal pocket placement",
  "pocketPlacementHorizontal.d": "The (horizontal) location of the pockets",
  "pocketPlacementVertical.t": "Vertical pocket placement",
  "pocketPlacementVertical.d": "The (vertical) location of the pockets",
  "collarHeight.t": "Collar height",
  "collarHeight.d": "Height of the collar",
  "length.t": "Length",
  "length.d": "Total length",
  "pocketFlapRadius.t": "Pocket flap radius",
  "pocketFlapRadius.d": "The amount by which the pocket flap is rounded",
  "pocketRadius.t": "Pocket radius",
  "pocketRadius.d": "The amount by which the pocket is rounded",
  "chestPocketHeight.t": "Chest pocket height",
  "chestPocketHeight.d": "Height of the chest pocket",
  "beltWidth.t": "Belt width",
  "beltWidth.d": "Width of the belt",
  "buttonSpacingHorizontal.t": "Horizontal button spacing",
  "buttonSpacingHorizontal.d": "Horizontal spacing of the buttons, also determines the front closure overlap"
}

export default o_carlton
