/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cathrin = {
  "panels.t": "Number of panels",
  "panels.d": "The number of panels to draft. More panels are better to fit a curvier model.",
  "waistReduction.t": "Waist reduction",
  "waistReduction.d": "The amount by which you want the corset to pinch your waist.",
  "backOpening.t": "Back opening",
  "backOpening.d": "Opening at the center back closure.",
  "backRise.t": "Back rise",
  "backRise.d": "How much the back panels rise from your arms to your center back.",
  "backDrop.t": "Back drop",
  "backDrop.d": "How much the back panels lower from your hips towards your center back. Negative values will raise the back.",
  "frontRise.t": "Front rise",
  "frontRise.d": "Rise of the front panels at center front, between your breasts. Negative values will lower them.",
  "frontDrop.t": "Front drop",
  "frontDrop.d": "How much the front panels lower from your hips towards your center front.",
  "hipRise.t": "Hip rise",
  "hipRise.d": "How much the side panels rise on your hips."
}

export default o_cathrin
