/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_charlie = {
  "backPocketHorizontalPlacement.t": "Back pocket horizontal placement",
  "backPocketHorizontalPlacement.d": "Controls the horizontal placement of the back pocket",
  "backPocketVerticalPlacement.t": "Back pocket vertical placement",
  "backPocketVerticalPlacement.d": "Controls the vertical placement of the back pocket",
  "backPocketWidth.t": "Back pocket width",
  "backPocketWidth.d": "Controls the width of the back pocket",
  "backPocketDepth.t": "Back pocket depth",
  "backPocketDepth.d": "Controls the depth of the back pocket",
  "backPocketFacing.t": "Back pocket facing",
  "backPocketFacing.d": "Controls whether or not to include facing on the back pockets",
  "frontPocketSlantDepth.t": "Front pocket slant depth",
  "frontPocketSlantDepth.d": "Controls the depth of the (front) pocket slant",
  "frontPocketSlantWidth.t": "Front pocket slant width",
  "frontPocketSlantWidth.d": "Controls the width of the (front) pocket slant",
  "frontPocketSlantRound.t": "Front pocket slant round",
  "frontPocketSlantRound.d": "Controls how far from the end of the slant we start rounding into the outseam",
  "frontPocketSlantBend.t": "Front pocket slant bend",
  "frontPocketSlantBend.d": "Controls the radius by which we round the pocket slant into the outseam",
  "frontPocketWidth.t": "Front pocket width",
  "frontPocketWidth.d": "Controls the width of the front pocket bag",
  "frontPocketDepth.t": "Front pocket depth",
  "frontPocketDepth.d": "Controls the depth of the front pocket bag",
  "frontPocketFacing.t": "Front pocket facing",
  "frontPocketFacing.d": "Controls how far the pocket facing extends into the pocket bag",
  "beltLoops.t": "Belt loops",
  "beltLoops.d": "Controls the amount of belt loops",
  "flyCurve.t": "Fly curve",
  "flyCurve.d": "Controls the curvature of the fly J-seam",
  "flyLength.t": "Fly length",
  "flyLength.d": "Controls the length of the fly",
  "flyWidth.t": "Fly width",
  "flyWidth.d": "Controls how far the J-seam of offset from the fly edge",
  "waistbandCurve.t": "Waistband Curve",
  "waistbandCurve.d": "Controls how curved the waistband is."
}

export default o_charlie
