/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_noble = {
  "dartPosition.t": "Dart position",
  "dartPosition.d": "Controls whether to split at the shoulder or armhole",
  "chestEase.t": "Chest ease",
  "chestEase.d": "Controls the amount of ease at the chest",
  "waistEase.t": "Waist ease",
  "waistEase.d": "Controls the amount of ease at the waist",
  "bustSpanEase.t": "Bust span ease",
  "bustSpanEase.d": "Controls the amount of ease along the bust span",
  "backDartHeight.t": "Controls the height of the back dart",
  "backDartHeight.d": "Back dart height",
  "waistDartLength.t": "Waist dart length",
  "waistDartLength.d": "Controls the length of the waist dart",
  "shoulderDartPosition.t": "Shoulder dart position",
  "shoulderDartPosition.d": "Controls the position of the shoulder dart",
  "upperDartLength.t": "Upper dart length",
  "upperDartLength.d": "Controls the length of the upper dart",
  "armholeDartPosition.t": "Armhole dart position",
  "armholeDartPosition.d": "Controls the position of the armhole dart",
  "armholeDepth.t": "Armhole depth",
  "armholeDepth.d": "Controls the depth of the armhole",
  "backArmholeSlant.t": "Back armhole slant",
  "backArmholeSlant.d": "Controls the slant of the armhole at the back",
  "backArmholeCurvature.t": "Back armhole curvature",
  "backArmholeCurvature.d": "Controls how deep the armhole is scooped out at the back",
  "frontArmholePitchDepth.t": "Front armhole pitch depth",
  "frontArmholePitchDepth.d": "Controls how deep the armhole curts into the front",
  "backArmholePitchDepth.t": "Back armhole pitch depth",
  "backArmholePitchDepth.d": "Controls how deep the armhole curts into the back",
  "backNeckCutout.t": "Back neck cutout",
  "backNeckCutout.d": "Controls how deep the neck is cutout in the back",
  "backHemSlope.t": "Back hem slope",
  "backHemSlope.d": "Constrols the slope of the back hem",
  "frontShoulderWidth.t": "Front shoulder width",
  "frontShoulderWidth.d": "Controls how much width is added to the shoulder in the front",
  "highBustWidth.t": "Hight bust width",
  "highBustWidth.d": "Controls the widht of the high bust",
  "shoulderToShoulderEase.t": "Shoulder to shoulder ease",
  "shoulderToShoulderEase.d": "Controls the amount of ease long the shoulder to shoulder measurement"
}

export default o_noble
