/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sandy = {
  "waistbandWidth.t": "Waistband width",
  "waistbandWidth.d": "Controls the width of the waistband.",
  "waistbandPosition.t": "Waistband position",
  "waistbandPosition.d": "Controls the position of the waistband.",
  "waistbandShape.t": "Waistband shape",
  "waistbandShape.d": "Whether you want a straight or shaped waistband.",
  "circleRatio.t": "Circle ratio",
  "circleRatio.d": "The percentage of a circle you want the skirt to be.",
  "waistbandOverlap.t": "Waistband overlap",
  "waistbandOverlap.d": "The amount by which the waistband overlaps.",
  "gathering.t": "Gathering",
  "gathering.d": "The percent by which the top of the skirt is longer than the bottom of the waistband.",
  "seamlessFullCircle.t": "Seamless full circle",
  "seamlessFullCircle.d": "Enables a seamless full circle skirt.",
  "hemWidth.t": "Hem width",
  "hemWidth.d": "Width of the hem"
}

export default o_sandy
