/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tamiko = {
  "flare.t": "Flare",
  "flare.d": "The amount by which the garment flares from your chest downwards",
  "shoulderseamLength.t": "Shoulder seam length",
  "shoulderseamLength.d": "The length of the shoulder seam, as a factor of your shoulder to shoulder measurement",
  "shoulderSlope.t": "Shoulder slope",
  "shoulderSlope.d": "Controls the angle of the shoulder seams"
}

export default o_tamiko
