/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Draft for high bust",
  "draftForHighBust.d": "Draft the pattern for the high bust measurement (if available) rather than the (full) chest. This will result in a more fitted garment for people with breasts.",
  "sleeveEase.t": "Свобода прилягання рукава",
  "sleeveEase.d": "Змінити свободу прилягання рукавів",
  "sleeveLength.t": "Довжина рукава",
  "sleeveLength.d": "Змінити довжину рукавів",
  "necklineBend.t": "Вигін горловини",
  "necklineBend.d": "Змінити лінію вигину горловини.",
  "necklineDepth.t": "Глибина горловини",
  "necklineDepth.d": "Змінити параметр того, як низько знаходиться горловина.",
  "necklineWidth.t": "Ширина горловини",
  "necklineWidth.d": "Змінити ширину горловини."
}

export default o_teagan
