/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_theo = {
  "wedge.t": "Wedge",
  "wedge.d": "Controls the length of the cross seam",
  "legWidth.t": "Leg width",
  "legWidth.d": "Controls the width of the legs"
}

export default o_theo
