/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tiberius = {
  "headRatio.t": "Head ratio",
  "headRatio.d": "Controls the size of the head opening",
  "armholeDrop.t": "Armhole drop",
  "armholeDrop.d": "Controls the depth of the armhole",
  "lengthBonus.t": "Length bonus",
  "lengthBonus.d": "Allows variation of the length of the garment",
  "widthBonus.t": "Width bonus",
  "widthBonus.d": "Allows variation of the width of the garment",
  "clavi.t": "Clavi",
  "clavi.d": "Whether or not to include guides for clavi",
  "clavusLocation.t": "Clavus location",
  "clavusLocation.d": "Controls the location of the clavi",
  "clavusWidth.t": "Clavus width",
  "clavusWidth.d": "Controls the width of the clavi",
  "length.t": "Length",
  "length.d": "Controls the length of the garment",
  "width.t": "Width",
  "width.d": "Controls the width of the garment",
  "forceWidth.t": "Force width",
  "forceWidth.d": "Apply width settings regardless of constraints"
}

export default o_tiberius
