/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_titan = {
  "kneeEase.t": "Knee ease",
  "kneeEase.d": "Controls the amout of ease at the knee",
  "waistHeight.t": "Waist height",
  "waistHeight.d": "Controls the height of the waist, 100% = waist height, 0% = hip height",
  "lengthBonus.t": "Length bonus",
  "lengthBonus.d": "Controls the length of the trousers",
  "crotchDrop.t": "Crotch drop",
  "crotchDrop.d": "Lowers the crotch for a more relaxed fit",
  "fitKnee.t": "Fit the knee",
  "fitKnee.d": "Fits the legs from based on the knee circumference, rather than seat circumference",
  "legBalance.t": "Leg balance",
  "legBalance.d": "Controls the ratio between front and back panel of the leg",
  "crossSeamCurveStart.t": "Start of the cross seam curve",
  "crossSeamCurveStart.d": "Controls how far into the cross seam we start to curve",
  "crossSeamCurveBend.t": "Cross seam bend",
  "crossSeamCurveBend.d": "Controls the curvature of the cross seam",
  "crossSeamCurveAngle.t": "Cross seam angle",
  "crossSeamCurveAngle.d": "Controls the angle of the cross seam",
  "crotchSeamCurveStart.t": "Start of the crotch seam curve",
  "crotchSeamCurveStart.d": "Controls how far into the crotch seam we start to curve",
  "crotchSeamCurveBend.t": "Crotch seam bend",
  "crotchSeamCurveBend.d": "Controls the curvature of the crotch seam",
  "crotchSeamCurveAngle.t": "Crotch seam angle",
  "crotchSeamCurveAngle.d": "Controls the angle of the crotch seam",
  "waistBalance.t": "Waist balance",
  "waistBalance.d": "Controls the horizontal position of the waist relative to the seat",
  "waistbandWidth.t": "Waistband width",
  "waistbandWidth.d": "The width of the waistband",
  "grainlinePosition.t": "Grainline position",
  "grainlinePosition.d": "Controls the horizontal position of the leg relative to the seat"
}

export default o_titan
