/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_trayvon = {
  "tipWidth.t": "Tip width",
  "tipWidth.d": "The width of your tie at the tip",
  "knotWidth.t": "Knot width",
  "knotWidth.d": "The width of your tie at the knot"
}

export default o_trayvon
