/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const ograph = {
  "orgTitle": "Ласкаво просимо до FreeSewing.org",
  "devTitle": "Ласкаво просимо до FreeSewing.dev",
  "labTitle": "Ласкаво просимо до lab.FreeSewing.lab",
  "devDescription": "Документація та навчальні матеріали для розробників FreeSewing та учасників. А також наш блог розробників"
}

export default ograph
