/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const patrons = {
  "becomeAPatron": "Стати патроном",
  "supportFreesewing": "Підтримати FreeSewing",
  "patronLead": "FreeSewing існує завдяки добровільній моделі підписки",
  "patronPitch": "Якщо Ви думаєте, що ми робимо цінну роботу, і якщо Ви можете відшкодувати кілька монет щомісяця без труднощів, будь ласка, підтримайте нашу роботу"
}

export default patrons
