/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const posts = {
  "xMadeThis": "<strong>{x}</strong> є автором цієї роботи",
  "xWroteThis": "<strong>{x}</strong> є автором цього тексту"
}

export default posts
