/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const themes = {
  "lightTheme": "Світла тема",
  "darkTheme": "Темна тема",
  "hax0rTheme": "Тема Hax0r",
  "lgbtqTheme": "Тема ЛГБТК",
  "transTheme": "Тема Транс"
}

export default themes
