/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Оберіть одиниці, які Ви хочете використовувати",
  "username": "Оберіть ім'я користувача",
  "avatar": "Додайте зображення профілю",
  "bio": "Розкажіть нам трохи про себе",
  "social": "Дайте нам знати, де ми можемо слідкувати за Вами",
  "newsletter": "Надайте нам свої налаштування для розсилки",
  "letUsSetupYourAccount": "Давайте налаштуємо Ваш обліковий запис.",
  "walkYouThrough": "Ми допоможемо Вам пройти наступні етапи:",
  "someOptional": "Хоча всі ці етапи необов'язкові, ми рекомендуємо Вам пройти їх, щоб отримати максимум користі від FreeSewing."
}

export default welcome
