content_segmentation: 0
commit_message: skip-build
pull_request_assignees:
  - joostdecock
pull_request_title: 'New Crowdin Translations [skip build]'
pull_request_labels:
  - crowdin
  - i18n
files:
  - source: /markdown/org/**/en.md
    translation: /markdown/org/**/%two_letters_code%.md
  - source: /sites/**/en.yaml
    translation: /sites/**/%two_letters_code%.yaml
  - source: /sites/shared/jargon/en.json
    translation: /sites/shared/jargon/%two_letters_code%.json
  - source: /designs/*/i18n/en.json
    translation: /designs/*/i18n/%two_letters_code%.json
  - source: /packages/new-design/i18n/en.json
    translation: /packages/new-design/i18n/%two_letters_code%.json
