export default [
  'backend',
  'camelCase',
  'capitalize',
  'cloneObject',
  'convertSize',
  'defaultGist',
  'defaultSa',
  'formatImperial',
  'formatMm',
  'isDegMeasurement',
  'measurementAsMm',
  'measurementDiffers',
  'neckstimate',
  'optionDefault',
  'optionType',
  'roundMm',
  'roundMmDown',
  'roundMmUp',
  'sliderStep',
  'smallestImperialStep',
  'storage',
  'tiler',
  'validateEmail',
  'validateTld',
]
const frowns = -1
