/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cfp = {
  "author": "Auteur",
  "githubRepo": "GitHub repository",
  "packageManager": "Pakketbeheerder",
  "patternName": "Patroon naam",
  "patternType": "Patroon type",
  "patternCreated": "Het skelet van je patroon is aangemaakt in",
  "runTheseCommands": "Voer dit commando uit om te beginnen.",
  "startRollup": "In één terminal, start de rollup bundler in de volgmodus",
  "startWebpack": "Het zal de map 'voorbeeld' invoeren en de ontwikkelingsomgeving starten.",
  "devDocsAvailableAt": "Documentatie voor ontwikkelaars is beschikbaar op",
  "talkToUs": "Voor vragen, feedback of suggesties, neem deel aan onze Discord server",
  "draftYourPattern": "Teken je patroon",
  "testYourPattern": "Test je patroon",
  "draftThing": "Teken {thing}",
  "testThing": "Test {thing}",
  "renderInBrowser": "Klik hieronder om je patroon in de browser te tonen.",
  "weWillReRender": "Wanneer je wijzigingen maakt, renderen we opnieuw.",
  "youCan": "Je kan",
  "enterMeasurements": "Maten manueel invoeren",
  "preloadMeasurements": "Een set van maten inladen",
  "size": "Maat",
  "noRequiredMeasurements": "Dit patroon heeft geen vereiste maten",
  "howtoAddMeasurements": "Om maten te vereisen, voeg je ze toe aan de <b>measurements</b> sectie van het configuratiebestand van het patroon.",
  "seeDocsAt": "Documentatie over dit onderwerp is beschikbaar op",
  "clearDesignMode": "Ontwerp modus wissen",
  "designMode": "Ontwerp modus",
  "exportMode": "Export modus",
  "thingIsEnabled": "{thing} is ingeschakeld",
  "thingIsDisabled": "{thing} is uitgeschakeld",
  "turnOn": "Inschakelen",
  "turnOff": "Uitschakelen",
  "validNameWarning": "Kies een andere naam, deze zou voor problemen zorgen.\nWe (her)gebruiken de patroonnaam als naam voor het NPM-pakket.\nPakketnamen mogen geen hoofdletters of speciale tekens bevatten.\nDus geef je patroon een geschikte naam, zoals:"
}

export default cfp
