/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Account",
  "blog": "Blog",
  "community": "Community",
  "designs": "Designs",
  "docs": "Documentatie",
  "showcase": "Voorbeelden",
  "sloganCome": "Kom voor de naaipatronen",
  "sloganStay": "Blijf voor de community"
}

export default common
