/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cty = {
  "wafsHashtag": "WeAreFreeSewing",
  "weAreACommunityOfMakers": "Wij zijn een gemeenschap van makers",
  "weProvideMtmSewingPatterns": "We bieden naaipatronen op maat",
  "isAPatron": "is een beschermheer",
  "contributesWith": "draagt bij aan",
  "communityBuilding": "Gemeenschap gebouw",
  "development": "Ontwikkeling",
  "patternTesting": "Patroon testen",
  "patternDesign": "Patroon ontwerp",
  "support": "Ondersteuning",
  "translation": "Vertaling",
  "writing": "Schrijven",
  "whereToFindUs": "Waar kunnen we vinden",
  "whoWeAre": "Wie zijn wij",
  "community": "Gemeenschap",
  "team": "Team",
  "teams": "teams",
  "contributors": "Bijdragers",
  "calls": "Gesprekken met bijdragers"
}

export default cty
