/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const docs = {
  "thingIsDeprecated": "{thing} is deprecated",
  "weRecommendThingInstead": "We recommend {thing} instead"
}

export default docs
