/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const email = {
  "chatWithUs": "Chat met ons",
  "emailchangeActionText": "Bevestig uw nieuwe e-mailadres",
  "emailchangeCopy1": "U heeft verzocht het e-mailadres dat aan uw account is gekoppeld te wijzigen op <b> freesewing.org </b>.<br><br>Voordat we dat doen, moet u uw nieuwe e-mailadres bevestigen. Klik op de onderstaande link om dat te doen:",
  "emailchangeHeaderOpeningLine": "We zorgen ervoor dat we u kunnen bereiken wanneer dat nodig is",
  "emailchangeHiddenIntro": "Laten we uw nieuwe e-mailadres bevestigen",
  "emailchangeSubject": "Bevestig uw nieuwe e-mailadres",
  "emailchangeTitle": "Bevestig uw nieuwe e-mailadres",
  "emailchangeWhy": "Je ontving deze e-mail omdat je het e-mailadres hebt gewijzigd dat gekoppeld is aan je account op freesewing.org",
  "footerCredits": "Gemaakt door joost & vrijwilligers met de financiële steun van onze Patrons ❤️ ",
  "footerSlogan": "FreeSewing is een open source platform voor naaipatronen op maat",
  "goodbyeCopy1": "Als je wilt delen waarom je vertrekt, kun je dit bericht beantwoorden. <br> Van onze kant zullen we je niet opnieuw lastig vallen.",
  "goodbyeHeaderOpeningLine": "Weet gewoon dat je altijd terug kunt komen",
  "goodbyeHiddenIntro": "Bedankt dat je freesewing.org een kans hebt gegeven",
  "goodbyeSubject": "Vaarwel 👋",
  "goodbyeTitle": "Bedankt dat je freesewing.org een kans hebt gegeven",
  "goodbyeWhy": "U ontving deze e-mail als een laatste adieu na het verwijderen van uw account op freesewing.org",
  "joostFromFreesewing": "Joost van FreeSewing",
  "passwordresetActionText": "Krijg toegang tot uw account",
  "passwordresetCopy1": "U bent uw wachtwoord voor uw account vergeten op <b>freesewing.org</b>.<br><br>Klik op de onderstaande link om uw wachtwoord opnieuw in te stellen:",
  "passwordresetHeaderOpeningLine": "Maak je geen zorgen, deze dingen gebeuren met ons allemaal",
  "passwordresetHiddenIntro": "Krijg toegang tot uw account",
  "passwordresetSubject": "Krijg toegang tot uw account op freesewing.org",
  "passwordresetTitle": "Stel uw wachtwoord opnieuw in en verkrijg opnieuw toegang tot uw account",
  "passwordresetWhy": "U hebt deze e-mail ontvangen omdat u heeft gevraagd om uw wachtwoord opnieuw in te stellen op freesewing.org",
  "questionsJustReply": "Zit je met vragen? Stuur ze dan als antwoord op deze E-mail. Ik ben steeds bereid om een handje te helpen. 🙂",
  "signature": "Liefs,",
  "signupActionText": "Bevestig je E-mail adres",
  "signupCopy1": "Leuk dat je je hebt ingeschreven op <b>freesewing.org</b>.<br><br>Vooraleer we aan de slag kunnen, moeten we eerst je E-mail adres bevestigen. Klik op onderstaande link om dat te doen:",
  "signupHeaderOpeningLine": "We zijn verheugd dat je deel wil uitmaken van de freesewing gemeenschap.",
  "signupHiddenIntro": "Nu gewoon nog even je E-mail adres bevestigen",
  "signupSubject": "Welkom bij freesewing.org",
  "signupTitle": "Welkom aan boord",
  "signupWhy": "Je ontving deze E-mail omdat je je zonet ingeschreven hebt op freesewing.org"
}

export default email
