/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "De pagina waarnaar u op zoek bent, kan niet gevonden worden",
  "confirmationNotFound": "Als u op deze pagina bent aangekomen via de link in een bevestigingsmail, raden we u aan dit probleem te melden.",
  "emailExists": "We hebben al een gebruiker met dat email adres. Misschien wil u zich eerder aanmelden?",
  "networkError": "Backend of netwerk probleem",
  "notAValidImageFormat": "Geen geldig beeldformaat",
  "requestFailedWithStatusCode400": "Verzoek mislukt",
  "requestFailedWithStatusCode401": "Authenticatie mislukt",
  "requestFailedWithStatusCode403": "Verboden",
  "requestFailedWithStatusCode500": "Er was een onverwacht probleem. Rapporteer dit alstublieft.",
  "something": "Er ging iets mis"
}

export default errors
