/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const homepage = {
  "scrollDownToLearnMore": "Scroll down to learn more about FreeSewing and try it for free"
}

export default homepage
