/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const homepage = {
  "scrollDownToLearnMore": "Scroll om meer te weten over FreeSewing en het gratis uit te proberen"
}

export default homepage
