/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "Duits",
  "en": "Engels",
  "es": "Spaans",
  "fr": "Frans",
  "nl": "Nederlands"
}

export default i18n
