/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const intro = {
  "txt-blog": "Nieuws, updates, and mededelingen door het freesewing team",
  "txt-community": "Al het werk word gedaan door vrijwillige medewerkers. Er zijn geen commerciële belangen verbonden aan het project.",
  "txt-different": "Hoe we anders zijn",
  "txt-draft": "Kies één van onze patronen, één van jouw modellen, en kies je opties. Wij doen de rest.",
  "txt-how": "Hoe het werkt",
  "txt-join": "Sluit je aan bij duizenden anderen, en schrijf je gratis in op freesewing.org.",
  "txt-model": "Al onze patronen zijn op maat gemaakt. Het eerste wat je dus moet doen is je lintmeter bij de hand nemen.",
  "txt-newHere": "Ben je hier nieuw? Dan is onze demo de beste plaats om van start te gaan:",
  "txt-opensource": "Ons platform, al onze patronen, en zelfs deze website. Al onze broncode is beschikbaar op GitHub. Pull requests welkom!",
  "txt-patrons": "Freesewing wordt mogelijk gemaakt door de financiële steun van onze mecenassen. Onderaan deze pagina kan je meer lezen over hoe we dit schip drijvende houden.",
  "txt-showcase": "Bekijk de projecten gemaakt door de freesewing gemeenschap"
}

export default intro
