/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "Zie <a href='/docs/sewing/basting/'>Driegen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "coverlock.d": "Zie <a href='/docs/sewing/coverlock/'>Coverlock</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "cutting.d": "Zie <a href='/docs/sewing/cutting/'>Knippen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "darts.d": "Zie <a href='/docs/sewing/darts/'>Nepen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "doubleWeltPockets.d": "Zie <a href='/docs/sewing/double-welt-pockets/'>Dubbele paspelzak</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "ease.d": "Zie <a href='/docs/sewing/ease/'>Overwijdte</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "edgestitch.d": "See <a href='/docs/sewing/edgestitching/'>Edgestitching</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "fabricGrain.d": "Zie <a href='/docs/sewing/fabric-grain/'>Draadrichting</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "goodSidesTogether.d": "Zie <a href='/docs/sewing/good-sides-together/'>Goede kanten op elkaar</a> in de<a href='/docs/sewing/'>Documentatie naaien</a>",
  "onTheFold.d": "Zie <a href='/docs/sewing/on-the-fold/'>Aan de stofvouw</a> bij de <a href='/docs/sewing/'>Documentatie naaien</a>",
  "hemming.d": "Zie <a href='/docs/sewing/hemming/'>Zomen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "jersey.d": "Zie <a href='/docs/sewing/jersey/'>Jersey</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "knitBinding.d": "Zie <a href='/docs/sewing/knit-binding/'>Jersey biezen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "knitFabric.d": "Zie <a href='/docs/sewing/knit-fabric/'>Gebreide stof</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "pinning.d": "Zie <a href='/docs/sewing/pinning/'>Spelden</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "rayon.d": "Zie <a href='/docs/sewing/rayon/'>Rayon</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "sa.d": "Zie <a href='/docs/sewing/seam-allowance/'>Naadtoeslag</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "serger.d": "Zie <a href='/docs/sewing/serger/'>Serger/Overlock</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "slipstitch.d": "See <a href='/docs/sewing/slipstitch/'>Slipstitch</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "topstitching.d": "Zie <a href='/docs/sewing/topstitching/'>Sierstiksel</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "trimming.d": "Zie <a href='/docs/sewing/trimming/'>Bijknippen</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "twinNeedle.d": "Zie <a href='/docs/sewing/twin-neelde/'>Tweelingnaald</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "zigZag.d": "Zie <a href='/docs/sewing/zig-zag-stitch/'>Zigzagsteek</a> in de<a href='/docs/sewing'>Documentatie naaien</a>",
  "freesewing.d": "<b>FreeSewing</b> is een open source platform voor naaipatronen op maat",
  "patternOptions.d": "De <b>patroon opties</b> staan je toe het ontwerp van het patroon aan te passen",
  "draftSettings.d": "De <b>instellingen patroontekening</b> geven je controle over goe een patroon gegenereerd wordt",
  "patrons.d": "Mecenassen ondersteunen FreeSewing financieel. Het zijn loyale supporters die zorgen voor een duurzame toekomst voor freesewing.org, onze code, onze patronen en onze gemeenschap.",
  "msf.d": "Médecins Sans Frontières/Artsen Zonder Grenzen - Zie<a href='https://msf.org/'>msf.org</a>"
}

export default jargon
