/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const measurements = {
  "ankle": "Enkelomtrek",
  "biceps": "Omtrek biceps",
  "bustFront": "Buste voor",
  "bustPointToUnderbust": "Bustpunt tot onderbuste",
  "bustSpan": "Bustewijdte",
  "chest": "Borstomtrek",
  "crossSeam": "Kruisnaad",
  "crossSeamFront": "Kruisnaad vooraan",
  "head": "Hoofdomtrek",
  "heel": "Omtrek Hiel",
  "highBustFront": "Hoge buste vooraan",
  "highBust": "Hoge buste",
  "hips": "Heupomtrek",
  "hpsToBust": "HPS tot buste",
  "hpsToWaistBack": "HPS tot taille achter",
  "hpsToWaistFront": "HPS tot taille voor",
  "inseam": "Binnenbeennaad",
  "knee": "Knieomtrek",
  "neck": "Nekomtrek",
  "seat": "Omtrek zitvlak",
  "seatBack": "Zitvlak achterkant",
  "crotchDepth": "Diepte kruis",
  "shoulderSlope": "Schoulder helling",
  "shoulderToElbow": "Schouder tot elleboog",
  "shoulderToShoulder": "Schouder tot schouder",
  "shoulderToWrist": "Schouder tot pols",
  "underbust": "Onderbuste",
  "upperLeg": "Bovenbeenomtrek",
  "waist": "Omtrek taille",
  "waistBack": "Taille achter",
  "waistToFloor": "Taille tot vloer",
  "waistToHips": "Taille tot heupen",
  "waistToKnee": "Taille tot knie",
  "waistToSeat": "Taille tot zitvlak",
  "waistToUnderbust": "Taille tot onderbuste",
  "waistToUpperLeg": "Taille tot bovenbeen",
  "wrist": "Polsomtrek"
}

export default measurements
