/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Diepte armsgat",
  "armholeDrop.d": "Verlaag het armsgat met deze hoeveelheid. Een negatieve waarde maakt het hoger.",
  "backlineBend.t": "Vorm armsgat achteraan",
  "backlineBend.d": "Bepaalt de vorm/curve van de achterkant van het armsgat.",
  "hipsEase.t": "Overwijdte heup",
  "hipsEase.d": "De hoeveelheid overwijdte aan je heupen.",
  "necklineBend.t": "Vorm halslijn",
  "necklineBend.d": "Bepaalt de vorm/kromming van de halslijn aan het middenvoor.",
  "necklineDrop.t": "Diepte halslijn",
  "necklineDrop.d": "De hoeveelheid waarmee de halslijn vooraan weggesneden wordt.",
  "shoulderStrapPlacement.t": "Plaatsing schouderbandjes",
  "shoulderStrapPlacement.d": "Bepaalt of de schouderbandjes dichter bij de nek (lager cijfer) of dichter bij de schouder (hoger cijfer) geplaatst worden.",
  "shoulderStrapWidth.t": "Breedte schouderband",
  "shoulderStrapWidth.d": "De breedte van de schouderbandjes.",
  "stretchFactor.t": "Rek",
  "stretchFactor.d": "Bepaalt hoeveel kleiner de horizontale omtrek is dan je lichaamsmaten. In andere woorden, hoe strak alles zit."
}

export default o_aaron
