/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Rugopening",
  "backOpening.d": "Bepaalt de opening aan de achterkant van de schort",
  "chestDepth.t": "Lengte van de badjes",
  "chestDepth.d": "Bepaalt de lengte van de bandjes",
  "lengthBonus.t": "Lengtebonus",
  "lengthBonus.d": "Bepaalt de lengte van de schort",
  "bibLength.t": "Lengte slabbetje",
  "bibLength.d": "Bepaalt de lengte van het slabbetje",
  "bibWidth.t": "Breedte slabbetje",
  "bibWidth.d": "Bepaalt de breedte van het slabbetje",
  "strapWidth.t": "Breedte bandjes",
  "strapWidth.d": "Bepaalt de breedte van de bandjes"
}

export default o_albert
