/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Mouw kromming",
  "sleeveBend.d": "Buiging van de mouw aan de elleboog",
  "sleevecapHeight.t": "Hoogte mouwkop",
  "sleevecapHeight.d": "Bepaalt de hoogte van de mouwkop"
}

export default o_bent
