/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Aanpaslintje",
  "adjustmentRibbon.d": "Of je wel of geen aanpaslintje wil",
  "bandLength.t": "Lengte band",
  "bandLength.d": "Lengte van de band",
  "tipWidth.t": "Tip breedte",
  "tipWidth.d": "Breedte van de punten",
  "knotWidth.t": "Knoop breedte",
  "knotWidth.d": "Breedte van de knoop",
  "bowLength.t": "Lengte strik",
  "bowLength.d": "De lengte van gestrikt (gestrikt)",
  "bowStyle.t": "Stijl strik",
  "bowStyle.d": "Stijl van de strik",
  "endStyle.t": "Puntvorm",
  "endStyle.d": "Stijl van de puntjes van de strik",
  "collarEase.t": "Overwijdte kraag",
  "collarEase.d": "The amount of ease at your neck",
  "ribbonWidth.t": "Ribbon width",
  "ribbonWidth.d": "Width of the ribbon"
}

export default o_benjamin
