/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bella = {
  "chestEase.t": "Overwijdte borst",
  "chestEase.d": "Bepaalt de hoeveelheid overwijdte aan het grootste deel van je borst",
  "waistEase.t": "Overwijdte taille",
  "waistEase.d": "Bepaalt de hoeveelheid overwijdte aan je taille",
  "bustSpanEase.t": "Overwijdte bustenwijdte",
  "bustSpanEase.d": "Bepaalt de hoeveelheid (horizontaal) overwijdte die wordt toegevoegd aan uw bustewijdte bij het lokaliseren van het bustepunt.",
  "fullChestEaseReduction.t": "Full chest ease reduction",
  "fullChestEaseReduction.d": "Allows you to independently reduce the ease around the chest to make it fit tight(er) in that area",
  "backDartHeight.t": "Hoogte neep rug",
  "backDartHeight.d": "Bepaalt de hoogte van de achterste neep",
  "bustDartLength.t": "Lengte busteneep",
  "bustDartLength.d": "Bepaalt de lengte van de buste-neep",
  "waistDartLength.t": "Lengte neep taille",
  "waistDartLength.d": "Bepaalt de lengte van de neep van de taille",
  "bustDartCurve.t": "Curve busteneep",
  "bustDartCurve.d": "Bepaalt de kromming van de busteneep",
  "armholeDepth.t": "Diepte armsgat",
  "armholeDepth.d": "Bepaalt de diepte van het armsgat",
  "backArmholeSlant.t": "Schuin armsgat achter",
  "backArmholeSlant.d": "Het armsgat rond zijn toonhoogte roteert enigszins",
  "frontArmholeCurvature.t": "Front armhole curvature",
  "frontArmholeCurvature.d": "Controls how deep the armhole is scooped out at the front bottom",
  "backArmholeCurvature.t": "Kromming armsgat achter",
  "backArmholeCurvature.d": "Bepaalt hoe diep het armsgat aan de achterste onderkant wordt uitgekoopt",
  "frontArmholePitchDepth.t": "Diepte armsgat vooraan",
  "frontArmholePitchDepth.d": "Aanpassen van de horizontale plaatsing van het pitch voorste armsgat",
  "backArmholePitchDepth.t": "Diepte armsgat achteraan",
  "backArmholePitchDepth.d": "Aanpassen van de horizontale plaatsing van het armsgat achterin",
  "backNeckCutout.t": "Hals uitsnijding achteraan",
  "backNeckCutout.d": "Bepaalt hoe diep de halsopening aan de achterkant wordt uitgekoopt",
  "backHemSlope.t": "Lope zoom achter",
  "backHemSlope.d": "Bepaalt de richtingscoëfficiënt van de zoom achteraan",
  "frontShoulderWidth.t": "Schouderbreedte vooraan",
  "frontShoulderWidth.d": "Bepaalt de smalheid van de schouders vooraan ten opzichte van de achterkant",
  "highBustWidth.t": "Hoge buste-breedte",
  "highBustWidth.d": "Stelt je in staat om de breedte van de nachtbust vooraan te wijzigen"
}

export default o_bella
