/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Kruisstuk",
  "bulge.d": "Maak de hoek groter voor meer ruimte in het kruisstuk.",
  "legBonus.t": "Bonus beenlengte",
  "legBonus.d": "Extra lengte om aan de benen toe te voegen.",
  "rise.t": "Hoogte",
  "rise.d": "Hoeveelheid waarmee de taille verhoogd wordt. Een negatieve waarde zal de taille verlagen.",
  "stretch.t": "Rek",
  "stretch.d": "Hoeveel kleiner de omtrek is dan je lichaamsmaten. In andere woorden, hoe strak alles zit.",
  "legStretch.t": "Stretch pijp",
  "legStretch.d": "For best results, you want to fit your legs a bit more snugly — say no to gaping.",
  "backRise.t": "Hoogte achter",
  "backRise.d": "Het percentage waarmee de taille verhoogd wordt aan de rug."
}

export default o_bruce
