/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Schouder neep",
  "shoulderDart.d": "Wel of niet een neep aan de schouder aan de schouder aan de achterkant",
  "shoulderDartSize.t": "Grootte schouder neep",
  "shoulderDartSize.d": "De grootte van de schouderneep",
  "shoulderDartLength.t": "Lengte schouder neep",
  "shoulderDartLength.d": "De lengte van de schouderneep",
  "waistDart.t": "Taille neep",
  "waistDart.d": "Of je een neep aan de taille wilt aanlaten om de achterkant af te ronden",
  "waistDartSize.t": "Grootte neep taille",
  "waistDartSize.d": "De grootte van de neep van de taille",
  "waistDartLength.t": "Lengte neep taille",
  "waistDartLength.d": "De lengte van de neep van de taille",
  "verticalEase.t": "Verticale overwijdte",
  "verticalEase.d": "De hoeveelheid overwijdte om te verdelen over de lengte van het kledingstuk",
  "waistEase.t": "Overwijdte taille",
  "waistEase.d": "De hoeveelheid overwijdte aan de taille",
  "primaryBustDart.t": "Bust neep",
  "primaryBustDart.d": "Waar moet je de buikneep plaatsen om de borst vorm te geven",
  "primaryBustDartLength.t": "Lengte busteneep",
  "primaryBustDartLength.d": "De lengte van de bustenneep",
  "secondaryBustDart.t": "Secundaire bustenneep",
  "secondaryBustDart.d": "Voeg optioneel een secundaire bustenneep toe om de vormgeving van de borst te verdelen",
  "secondaryBustDartLength.t": "Secundaire lengte bustenneep",
  "secondaryBustDartLength.d": "De lengte van de secundaire bustenneep",
  "primaryBustDartShaping.t": "Bust nepen vormgeving",
  "primaryBustDartShaping.d": "Bepaalt het evenwicht tussen de hoofd- en secundaire busteennepen"
}

export default o_breanna
