/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cathrin = {
  "panels.t": "Aantal panelen",
  "panels.d": "Het aantal panelen. Meer panelen werken beter voor een ronder figuur.",
  "waistReduction.t": "Reductie taille",
  "waistReduction.d": "Hoeveel smaller je wil dat het korset je taille maakt.",
  "backOpening.t": "Opening rug",
  "backOpening.d": "Opening aan de sluiting op de middenrug.",
  "backRise.t": "Hoogte achter",
  "backRise.d": "Hoe ver de rugpanden stijgen van je armen tot je middenrug.",
  "backDrop.t": "Verlaging rug",
  "backDrop.d": "Hoeveel lager de rugpanden worden vanaf de heupen tot de middenrug. Een negatieve waarde maakt ze hoger.",
  "frontRise.t": "Hoogte voorpand",
  "frontRise.d": "De hoogte van de panelen middenvoor, tussen je borsten. Een negatieve waarde maakte ze lager.",
  "frontDrop.t": "Verlaging voorpand",
  "frontDrop.d": "Hoeveel de voorpanden verlagen van je heupen tot middenvoor.",
  "hipRise.t": "Hoogte heup",
  "hipRise.d": "Hoe hoog de zijpanelen vallen op je heupen."
}

export default o_cathrin
