/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlton = {
  "seatEase.t": "Overwijdte zitvlak",
  "seatEase.d": "De hoeveelheid overwijdte aan je zitvlak",
  "pocketPlacementHorizontal.t": "Plaatsing zakken (horizontaal)",
  "pocketPlacementHorizontal.d": "De horizontale plaatsing van de zakken",
  "pocketPlacementVertical.t": "Plaatsing zakken (verticaal)",
  "pocketPlacementVertical.d": "De verticale plaatsing van de zakken",
  "collarHeight.t": "Hoogte kraag",
  "collarHeight.d": "De hoogte van de kraag",
  "length.t": "Lengte",
  "length.d": "De totale lengte",
  "pocketFlapRadius.t": "Ronding zak flap",
  "pocketFlapRadius.d": "De mate waarin de flap van de zak is afgerond",
  "pocketRadius.t": "Ronding zak",
  "pocketRadius.d": "De mate waarin de zak is afgerond",
  "chestPocketHeight.t": "Hoogte borstzak",
  "chestPocketHeight.d": "De hoogte van de borstzak",
  "beltWidth.t": "Breedte riem",
  "beltWidth.d": "De breedte van de riem",
  "buttonSpacingHorizontal.t": "Spreiding knopen horizontaal",
  "buttonSpacingHorizontal.d": "De spreiding van de knopen horizontaal. Bepaalt ook de mate waarin de sluiting vooraan overlapt"
}

export default o_carlton
