/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_charlie = {
  "backPocketHorizontalPlacement.t": "Plaatsing horizontale achterzak",
  "backPocketHorizontalPlacement.d": "Bepaalt de horizontale plaatsing van de achterzak",
  "backPocketVerticalPlacement.t": "Verticale plaatsing achterzak",
  "backPocketVerticalPlacement.d": "Bepaalt de verticale plaatsing van de achterzak",
  "backPocketWidth.t": "Breedte achterzak",
  "backPocketWidth.d": "Bepaalt de breedte van de achterzak",
  "backPocketDepth.t": "Diepte achterzak",
  "backPocketDepth.d": "Bepaalt de diepte van de achterzak",
  "backPocketFacing.t": "Back pocket facing",
  "backPocketFacing.d": "Controls whether or not to include facing on the back pockets",
  "frontPocketSlantDepth.t": "Diepte voorzak",
  "frontPocketSlantDepth.d": "Bepaalt de diepte van de voorste zakopening",
  "frontPocketSlantWidth.t": "Schouderstuk voorzak breedte",
  "frontPocketSlantWidth.d": "Bepaalt de breedte van de voorste zakopening",
  "frontPocketSlantRound.t": "Schuine zakdeel rond",
  "frontPocketSlantRound.d": "Bepaalt hoe ver we van het einde van de schuine lijn beginnen met afronden in de outnaad",
  "frontPocketSlantBend.t": "Schuine zakopening",
  "frontPocketSlantBend.d": "Bepaalt de straal waarmee we het zakdeel op de rand afstemmen",
  "frontPocketWidth.t": "Breedte zak",
  "frontPocketWidth.d": "Bepaalt de breedte van het voorste zakdeel",
  "frontPocketDepth.t": "Diepte zak",
  "frontPocketDepth.d": "Bepaalt de diepte van het voorzakdeel",
  "frontPocketFacing.t": "Beleg zak",
  "frontPocketFacing.d": "Bepaalt hoever het beleg van de zak zich uitstrekt tot het zakdeel",
  "beltLoops.t": "Rand lussen",
  "beltLoops.d": "Bepaalt de hoeveelheid riemlusjes",
  "flyCurve.t": "Vlieg curve",
  "flyCurve.d": "Bepaalt de kromming van de gulpnaad",
  "flyLength.t": "Vlieg lengte",
  "flyLength.d": "Bepaalt de lengte van de gulp",
  "flyWidth.t": "Fly width",
  "flyWidth.d": "Bepaalt hoe ver de J-naad van de rand van de gulp af staat",
  "waistbandCurve.t": "Tailleband curve",
  "waistbandCurve.d": "Bepaalt hoe gebogen de tailleband is."
}

export default o_charlie
