/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cornelius = {
  "fullness.t": "Volle",
  "fullness.d": "Bepaalt de volledigheid van de broeders",
  "waistbandBelowWaist.t": "Onderste tailleband",
  "waistbandBelowWaist.d": "Percentage om de tailleband onder de tailleband te bewegen",
  "waistReduction.t": "Reductie taille",
  "waistReduction.d": "Percentage om de tailleband te verminderen",
  "cuffWidth.t": "Cuff width",
  "cuffWidth.d": "Breedte van de manchet",
  "cuffStyle.t": "Stijl manchet",
  "cuffStyle.d": "Stijl van de manchet",
  "bandBelowKnee.t": "Manchet onder knie",
  "bandBelowKnee.d": "Bepaalt de afstand tussen de manchet en de knie",
  "kneeToBelow.t": "Lengte manchet",
  "kneeToBelow.d": "Bepaalt de dikte van de manchet in vergelijking met de knie",
  "ventLength.t": "Vent lengte",
  "ventLength.d": "Bepaalt de lengte van de vent tussen de knie en de manchet"
}

export default o_cornelius
