/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_diana = {
  "shoulderSeamLength.t": "Lengte schoudernaad",
  "shoulderSeamLength.d": "Bepaalt de lengte van de schoudernaad",
  "drapeAngle.t": "Drape angle",
  "drapeAngle.d": "Bepaalt het aantal drape"
}

export default o_diana
