/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florence = {
  "height.t": "Hoogte",
  "height.d": "Bepaalt de hoogte van het mondmasker",
  "length.t": "Lengte",
  "length.d": "Bepaalt de lengte van het mondmasker",
  "curve.t": "Boog",
  "curve.d": "Bepaalt de curve van de bovenrand van het mondmasker"
}

export default o_florence
