/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florent = {
  "headEase.t": "Overwijdte hoofd",
  "headEase.d": "De hoeveelheid overwijdte rond je hoofd"
}

export default o_florent
