/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hortensia = {
  "size.t": "Maat",
  "size.d": "Bepaalt de totale grootte van de handtas",
  "zipperSize.t": "Rits grootte",
  "zipperSize.d": "Welke afmeting van de rits te gebruiken",
  "strapLength.t": "Rep lengte",
  "strapLength.d": "Bepaalt de lengte van de band",
  "handleWidth.t": "Afhandeling breedte",
  "handleWidth.d": "Bepaalt de breedte van het handvat"
}

export default o_hortensia
