/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hugo = {
  "hipsEase.t": "Overwijdte heup",
  "hipsEase.d": "De hoeveelheid overwijdte aan je heupen."
}

export default o_hugo
