/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_huey = {
  "pocket.t": "Zak",
  "pocket.d": "Of een voorzak moet worden toegevoegd of niet",
  "pocketHeight.t": "Zak hoogte",
  "pocketHeight.d": "Bepaalt de hoogte van de zak",
  "hoodHeight.t": "Capuchon hoogte",
  "hoodHeight.d": "Bepaalt de hoogte van de capuchon",
  "hoodCutback.t": "Capuchon inkorting",
  "hoodCutback.d": "Bepaalt hoever de capuchon opening is ingekort",
  "hoodClosure.t": "Capuchon sluiting",
  "hoodClosure.d": "Bepaalt hoeveel van de capuchon deel uitmaakt van de sluiting vooraan",
  "hoodDepth.t": "Capuchon diepte",
  "hoodDepth.d": "Bepaalt de diepte van de capuchon",
  "hoodAngle.t": "Capuchon hoek",
  "hoodAngle.d": "Bepaalt de hoek waaronder de capuchon is geplaatst"
}

export default o_huey
