/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_paco = {
  "heelEase.t": "Overwijdte hiel",
  "heelEase.d": "De hoeveelheid overwijdte aan de hiel (wanneer je je been door de broekspijp steekt)",
  "frontPockets.t": "Voorzakken",
  "frontPockets.d": "Of je al dan niet zakken in de zijnaad wil",
  "backPockets.t": "Achterzakken",
  "backPockets.d": "Of je al dan niet paspelzakken op de achterkant wil",
  "elasticatedHem.t": "Elastische zoom",
  "elasticatedHem.d": "Of je wel of niet elastiek aan de zoom wil",
  "ankleElastic.t": "Breedte enkel/zoom elastiek",
  "ankleElastic.d": "Breedte van de (optionele) elastiek aan de enkel/zoom"
}

export default o_paco
