/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_penelope = {
  "backDartDepthFactor.t": "Factor lengte neep rug",
  "backDartDepthFactor.d": "Hoe ver de neep achteraan naar beneden komt vanaf de tailleband. Dit is een factor van de Natuurlijke Taille Tot Zitvlak-maat.",
  "backVent.t": "Vent achteraan",
  "backVent.d": "Voeg een split toe aan de achterkant van de rok.",
  "backVentLength.t": "Lengte vent achteraan",
  "backVentLength.d": "Lengte van het loopsplit als een percentage van de lengte van de rok.",
  "dartToSideSeamFactor.t": "Factor neep tot zijnaad",
  "dartToSideSeamFactor.d": "Hoeveel van de reductie van heupen naar taille door de nepen ingenomen wordt, tegenover de zijnaad, uitgedrukt in een percentage.",
  "frontDartDepthFactor.t": "Factor lengte neep vooraan",
  "frontDartDepthFactor.d": "Hoe ver de neep vooraan naar beneden komt vanaf de tailleband. Dit is een factor van de Natuurlijke Taille Tot Zitvlak-maat.",
  "hem.t": "Afmeting van de zoom",
  "hem.d": "De afmeting van de zoom. Een maat in absolute waarden.",
  "hemBonus.t": "Bonus zoom",
  "hemBonus.d": "Deze optie maakt de omtrek van de rok aan de zoom kleiner. Percentage van de Omtrek Zitvlak-maat.",
  "lengthBonus.t": "Lengtebonus",
  "lengthBonus.d": "Dit bepaalt de lengte van de rok. Een percentage van de Taille tot Knie-maat.",
  "nrOfDarts.t": "Aantal nepen",
  "nrOfDarts.d": "Het aantal nepen in het patroon. Het maximum is 2. Deze optie kan aangepast worden door het patroon als de berekeningen te kleine nepen als resultaat hebben.",
  "seatEase.t": "Overwijdte zitvlak",
  "seatEase.d": "Hoeveelheid overwijdte aan het zitvlak.",
  "waistBand.t": "Tailleband",
  "waistBand.d": "Voeg een tailleband toe aan het patroon.",
  "waistBandWidth.t": "Breedte tailleband",
  "waistBandWidth.d": "De breedte van de tailleband.",
  "waistEase.t": "Overwijdte taille",
  "waistEase.d": "Hoeveelheid overwijdte aan de taille.",
  "zipperLocation.t": "Locatie rits",
  "zipperLocation.d": "De locatie van de rits."
}

export default o_penelope
