/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sandy = {
  "waistbandWidth.t": "Breedte tailleband",
  "waistbandWidth.d": "De breedte van de tailleband.",
  "waistbandPosition.t": "Positie tailleband",
  "waistbandPosition.d": "Bepaalt de positie van de tailleband.",
  "waistbandShape.t": "Vorm tailleband",
  "waistbandShape.d": "Wil je een rechte of gebogen tailleband?",
  "circleRatio.t": "Cirkel ratio",
  "circleRatio.d": "Hoeveel procent van een cirkel wil je dat de rok is?",
  "waistbandOverlap.t": "Overlap Tailleband",
  "waistbandOverlap.d": "Hoeveel de tailleband overlapt.",
  "gathering.t": "Fronsen",
  "gathering.d": "Met hoeveel procent de bovenrand van de rok langer is dan de onderrand van de tailleband.",
  "seamlessFullCircle.t": "Naadloze volledige cirkel",
  "seamlessFullCircle.d": "Maakt een naadloze volle cirkelrok mogelijk.",
  "hemWidth.t": "Breedte zoom",
  "hemWidth.d": "Breedte van de zoom"
}

export default o_sandy
