/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_shin = {
  "legReduction.t": "Been reductie",
  "legReduction.d": "Maakt de beenopening kleiner zodat ze niet openstaat",
  "elasticWidth.t": "Breedte elastiek",
  "elasticWidth.d": "Breedte van de elastiek aan de taille"
}

export default o_shin
