/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_simone = {
  "bustDartAngle.t": "Hoek busteneep",
  "bustDartAngle.d": "Bepaalt de hoek waarin de busteneep vanuit de zijnaad naar beneden wijst",
  "bustDartLength.t": "Lengte busteneep",
  "bustDartLength.d": "Bepaalt hoe dicht de punt van de busteneep bij het bustepunt komt",
  "contour.t": "Contour",
  "contour.d": "Bepaalt in hoeverre de extra ruimte voor borsten onder de buste verwijderd wordt",
  "frontDarts.t": "Nepen voor",
  "frontDarts.d": "Of je vooraan nepen wil of niet",
  "frontDartLength.t": "Lengte nepen voor",
  "frontDartLength.d": "Bepaalt hoe dicht de punt van de voorste neep bij het bustepunt komt"
}

export default o_simone
