/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sven = {
  "hipsEase.t": "Hips ease",
  "hipsEase.d": "Controls the amount of ease at your hips (the bottom of the sweater)",
  "ribbing.t": "Boordstof",
  "ribbing.d": "Of we boordstof plaatsen aan de zoom en manchetten of niet.",
  "ribbingHeight.t": "Hoogte boord",
  "ribbingHeight.d": "De hoogte van de boordstof aan zoom en manchetten.",
  "ribbingStretch.t": "Stretch boordstof",
  "ribbingStretch.d": "De hoeveelheid stretch in de boordstof voor zoom en manchetten."
}

export default o_sven
