/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tamiko = {
  "flare.t": "Waaier",
  "flare.d": "De mate waarin het kledingstuk van je borst naar beneden uitwaaierd",
  "shoulderseamLength.t": "Lengte schoudernaad",
  "shoulderseamLength.d": "De lengte van de schoudernaad, als een factor van je schouder tot schouder maat",
  "shoulderSlope.t": "Schouderhelling",
  "shoulderSlope.d": "Bepaalt de hoek van de schoudernaden"
}

export default o_tamiko
