/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Teken voor hoge buste",
  "draftForHighBust.d": "Teken het patroon voor de hoge bustemaat (indien beschikbaar) in plaats van de volle borstomtrek. Dit heeft een aansluitender kledingstuk als resultaat voor mensen met borsten.",
  "sleeveEase.t": "Overwijdte mouw",
  "sleeveEase.d": "De hoeveelheid extra ruimte in je mouwen",
  "sleeveLength.t": "Mouwlengte",
  "sleeveLength.d": "Bepaalt de lengte van je mouwen",
  "necklineBend.t": "Curve halslijn",
  "necklineBend.d": "Bepaalt de curve van de halsuitsnijding.",
  "necklineDepth.t": "Diepte halsuitsnijding",
  "necklineDepth.d": "Bepaalt hoe diep de halsopening is.",
  "necklineWidth.t": "Breedte halsuitsnijding",
  "necklineWidth.d": "Bepaalt hoe breed de halsopening is."
}

export default o_teagan
