/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_theo = {
  "wedge.t": "Spie",
  "wedge.d": "Bepaalt de lengte van de kruisnaad",
  "legWidth.t": "Breedte been",
  "legWidth.d": "Bepaalt de breedte van de broekspijpen"
}

export default o_theo
