/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_titan = {
  "kneeEase.t": "Overwijdte knie",
  "kneeEase.d": "Bepaalt de hoeveelheid overwijdte aan de knie",
  "waistHeight.t": "Taillehoogte",
  "waistHeight.d": "Bepaalt de hoogte van de taille, 100% = natuurlijke taille, 0% = heuphoogte",
  "lengthBonus.t": "Bonus lengte",
  "lengthBonus.d": "Bepaalt de lengte van de broek",
  "crotchDrop.t": "Diepte kruis",
  "crotchDrop.d": "Verlaagt het kruis voor een lossere pasvorm",
  "fitKnee.t": "Pas de knie aan",
  "fitKnee.d": "Past de broekspijpen aan gebaseerd op de omtrek van de knie in plaats van de omtrek van het zitvlak",
  "legBalance.t": "Balans been",
  "legBalance.d": "Bepaalt de verhouding tussen de voor-en achterkant van de broekspijp",
  "crossSeamCurveStart.t": "Begin van de curve van de binnenbeennaad",
  "crossSeamCurveStart.d": "Bepaalt hoe ver in de binnenbeennaad de curve start",
  "crossSeamCurveBend.t": "Buiging binnenbeennaad",
  "crossSeamCurveBend.d": "Bepaalt de curve van de binnenbeennaad",
  "crossSeamCurveAngle.t": "Grensoverschrijdende hoek",
  "crossSeamCurveAngle.d": "Bepaalt de hoek van de kruisnaad",
  "crotchSeamCurveStart.t": "Begin van de curve van de kruisnaad",
  "crotchSeamCurveStart.d": "Bepaalt hoe ver in de kruisnaad de curve start",
  "crotchSeamCurveBend.t": "Buiging kruisnaad",
  "crotchSeamCurveBend.d": "Bepaalt de curve van de kruisnaad",
  "crotchSeamCurveAngle.t": "Kruisnaad hoek",
  "crotchSeamCurveAngle.d": "Bepaalt de hoek van de kruisnaad",
  "waistBalance.t": "Balans taille",
  "waistBalance.d": "Bepaalt de horizontale positie van de taille in relatie tot het zitvlak",
  "waistbandWidth.t": "Breedte tailleband",
  "waistbandWidth.d": "De breedte van de tailleband",
  "grainlinePosition.t": "Positie draadrichting",
  "grainlinePosition.d": "Bepaalt de horizontale positie van het been in relatie tot het zitvlak"
}

export default o_titan
