/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_trayvon = {
  "tipWidth.t": "Breedte punten",
  "tipWidth.d": "De breedte van je stropdas aan het uiteinde",
  "knotWidth.t": "Breedte knoop",
  "knotWidth.d": "De breedte van je stropdas aan de knoop"
}

export default o_trayvon
