/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_ursula = {
  "fabricStretch.t": "Stof stretch",
  "fabricStretch.d": "Pas dit aan voor meer of minder elastische stoffen",
  "gussetWidth.t": "Gusset width",
  "gussetWidth.d": "Bepaalt de breedte van de gusset",
  "gussetLength.t": "Gusset lengte",
  "gussetLength.d": "Bepaalt de lengte van de gusset",
  "elasticStretch.t": "Elastische stretch",
  "elasticStretch.d": "Pas dit aan voor meer of minder elastische elastiek",
  "rise.t": "Hoogte",
  "rise.d": "Bepaalt de hoogte van de taille",
  "legOpening.t": "Been opening",
  "legOpening.d": "Bepaalt hoe hoog de broekspijp wordt uitgeknipt",
  "frontDip.t": "Voorste taille dip",
  "frontDip.d": "Bepaalt hoeveel de taillecurven vooraan tonen (min of meer skin)",
  "backDip.t": "Achterste dip taille",
  "backDip.d": "Bepaalt hoeveel de omgekeerde golfcurves (min of meer skin onthullen)",
  "taperToGusset.t": "Blootstelling voorzijde",
  "taperToGusset.d": "Bepaalt de hoeveelheid blootgestelde huid aan de voorkant",
  "backExposure.t": "Blootstelling rug",
  "backExposure.d": "Bepaalt de hoeveelheid gelekte huid aan de achterkant"
}

export default o_ursula
