/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_wahid = {
  "backScyeDart.t": "Achterste armsgat neep",
  "backScyeDart.d": "De hoeveelheid die verwijderd wordt met een neep aan de achterkant van het armsgat.",
  "frontScyeDart.t": "Neep armsgat voor",
  "frontScyeDart.d": "De hoeveelheid die verwijderd wordt met een neep aan de voorkant van het armsgat.",
  "pocketLocation.t": "Locatie van de zak",
  "pocketLocation.d": "Bepaalt de locatie van de zak",
  "pocketWidth.t": "Breedte van de zak",
  "pocketWidth.d": "Bepaalt de breedte van de zak",
  "weltHeight.t": "Hoogte paspel zak",
  "weltHeight.d": "De hoogte van de paspel van de zak",
  "necklineDrop.t": "Hoogte halslijn",
  "necklineDrop.d": "Bepaalt hoe laag de halslijn vooraan wordt",
  "frontStyle.t": "Stijl halsopening",
  "frontStyle.d": "Stijl van de halsopening",
  "hemStyle.t": "Vorm zoom",
  "hemStyle.d": "De vorm van de zoom vooraan",
  "hemRadius.t": "Ronding zoom",
  "hemRadius.d": "De straal van de ronding van de zoom",
  "backInset.t": "Insnede rug",
  "backInset.d": "Hoeveel het armsgat achteraan naar binnen gaat",
  "frontInset.t": "Insnede voorpand",
  "frontInset.d": "Hoeveel het armsgat vooraan naar binnen gaat",
  "shoulderInset.t": "Insnede schouder",
  "shoulderInset.d": "Hoeveel de schoudernaad aan de schouder naar binnen gaat",
  "neckInset.t": "Insnede nek",
  "neckInset.d": "Hoeveel de schoudernaad aan de hals naar binnen gaat",
  "pocketAngle.t": "Hoek zak",
  "pocketAngle.d": "De hoek van de zakopening"
}

export default o_wahid
