/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_waralee = {
  "backPocket.t": "Achterzak",
  "backPocket.d": "Of een achterzak moet worden toegevoegd of niet",
  "frontPocket.t": "Voorzak",
  "frontPocket.d": "Of een voorzak moet worden toegevoegd of niet",
  "hem.t": "Afmeting zoom",
  "hem.d": "De afmeting van de zoom onderaan de broek",
  "waistBand.t": "Tailleband",
  "waistBand.d": "Grootte van de tailleband",
  "waistRaise.t": "Hoogte Taille",
  "waistRaise.d": "Hoeveel hoger de taille zit dan de hoogte zitvlak-maat. Dit beïnvloedt de diepte van het kruis.",
  "crotchBack.t": "Kruis achter",
  "crotchBack.d": "Het percentage van de omtrek zitvlak dat je het kruis achteraan nodig heeft. Dit creëert meer of minder ruimte tussen de zijnaad en de middenachternaad.",
  "crotchFront.t": "Kruis Voor",
  "crotchFront.d": "Het percentage van de omtrek zitvlak dat je het kruis vooraan nodig heeft. Dit creëert meer of minder ruimte tussen de zijnaad en de middenvoornaad.",
  "crotchFactorBackHor.t": "Kruis Achter Factor Horizontaal",
  "crotchFactorBackHor.d": "Wordt gebruikt om de curve van het kruis achteraan horizontaal te verplaatsen",
  "crotchFactorBackVer.t": "Kruis Achter Factor Verticaal",
  "crotchFactorBackVer.d": "Wordt gebruikt om de curve van het kruis achteraan verticaal te verplaatsen",
  "crotchFactorFrontHor.t": "Kruis Voor Factor Horizontaal",
  "crotchFactorFrontHor.d": "Wordt gebruikt om de curve van het kruis vooraan horizontaal te verplaatsen",
  "crotchFactorFrontVer.t": "Kruis Voor Factor Verticaal",
  "crotchFactorFrontVer.d": "Wordt gebruikt om de curve van het kruis vooraan verticaal te verplaatsen",
  "waistOverlap.t": "Overlap Taille",
  "waistOverlap.d": "Dit bepaalt in hoeverre dat je de beenflappen wil laten overlappen aan de taille. Als je 0 instelt komen ze elkaar tegen ze aan de zijnaad, een instelling van 100 zorgt dat ze aan middenvoor/achter tegen elkaar komen.",
  "legShortening.t": "Been Inkorten",
  "legShortening.d": "Dit bepaalt hoe lang de broek zal zijn. Het is een factor van de binnenbeennaad. Hoe groter de waarde, hoe meer van de lengte verwijderd zal worden.",
  "backRaise.t": "Hoogte Rug",
  "backRaise.d": "Deze instelling verhoogt de taille in de rug. Onze taille zit niet horizontaal, maar ligt wat hoger in de rug. Deze instelling staat je toe de rug te verhogen als dit nodig is voor een goede pasvorm."
}

export default o_waralee
