/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const optiongroups = {
  "advanced": "Geavanceerd",
  "armhole": "Harnas",
  "closure": "Sluiting",
  "collar": "Kraag",
  "construction": "Constructie",
  "cuffs": "Manchetten",
  "darts": "Nepen",
  "elastic": "Elastiek",
  "fit": "Pasvorm",
  "pockets": "Zakken",
  "preferences": "Voorkeuren",
  "sleevecap": "Mouwkop",
  "sleeves": "Mouwen",
  "style": "Stijl",
  "backPockets": "Achterzakken",
  "frontPockets": "Voorzakken",
  "waistband": "Tailleband",
  "fly": "Vliegen",
  "bellaDarts": "Bella figuurnaden",
  "bellaArmhole": "Bella armsgat",
  "bellaAdvanced": "Bella geavanceerd",
  "clavi": "Clavi",
  "type": "Type",
  "size": "Size"
}

export default optiongroups
