/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const settings = {
  "advanced.t": "Expert modus",
  "advanced.d": "Bepaalt of de geavanceerde patroonopties wel of niet getoond worden",
  "paperless.t": "Papierloos",
  "paperless.d": "Hiermee tekent u een patroon met alle afmetingen zodat u het op stof of een ander medium kunt overbrengen zonder dat u het hoeft af te drukken",
  "sa.t": "Naadtoeslag",
  "sa.d": "Bepaalt de hoeveelheid naadtoeslag die is inbegrepen in uw patroon",
  "locale.t": "Taal",
  "locale.d": "Bepaalt de taal die op uw patroon wordt gebruikt",
  "only.t": "Inhoud",
  "only.d": "Hiermee kunt u precies bepalen welke patroononderdelen in uw patroon worden opgenomen",
  "units.t": "Eenheden",
  "units.d": "Bepaalt de eenheden die op uw patroon worden gebruikt",
  "margin.t": "Marge",
  "margin.d": "Bepaalt de marge rond patroondelen",
  "complete.t": "Detail",
  "complete.d": "Bepaalt hoe gedetailleerd het patroon is; Ofwel een patroon met alle details, ofwel een eenvoudiger patroon met slechts de contouren van de verschillende patroondelen",
  "layout.t": "Layout",
  "layout.d": "Bepaalt hoe de afzonderlijke patroondelen op uw patroon worden geplaatst",
  "debug.t": "Debug",
  "debug.d": "Schakel debug in om extra informatie te krijgen over hoe je patroon tot stand kwam",
  "scale.t": "Scale",
  "scale.d": "Controls the overall line width, font size, and other elements that do not scale with the pattern's measurements",
  "renderer.t": "Render engine",
  "renderer.d": "Controls how the pattern is rendered (drawn) on the screen",
  "xray.t": "X-ray",
  "xray.d": "Look under the hood with FreeSewing's X-ray mode"
}

export default settings
