/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Selecteer de units die je wil gebruiken",
  "username": "Kies een gebruikersnaam",
  "avatar": "Voeg een profielfoto toe",
  "bio": "Vertel ons een beetje over jezelf",
  "social": "Laat ons weten waar we je kunnen volgen",
  "newsletter": "Geef ons je voorkeur met betrekking tot de nieuwsbrief",
  "letUsSetupYourAccount": "Laten we je account instellen.",
  "walkYouThrough": "We zullen je door de volgende stappen begeleiden:",
  "someOptional": "Hoewel al deze stappen optioneel zijn, raden we je toch aan alles te doen om het meeste uit FreeSewing te halen."
}

export default welcome
