/*
 * FreeSewing uses Docusaurus for its development environment.
 * We also re-use the sidebar navigation for things like the account pages.
 * However, the sidebar navigation is tigtly coupled with the docs plugin in Docusaurus.
 * So we treat all of the account apges like docs pages. We just happen to load React components in them.
 * So this sidebar works for both docs and account
 */
export default {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
}
