/*
 * A header to include in auto-generated files
 */
export const header = `/*
 * This file was auto-generated by the prebuild script
 * Any changes you make to it will be lost on the next (pre)build.
 */
`

export const loadTranslations = async ({ namespaces = [], site, language }) => {
  const translations = {}
  for (const ns of namespaces) {
    const t = await import(`../../${site}/public/locales/${language}/${ns}.json`, {
      assert: { type: 'json' },
    })
    translations[ns] = t.default
  }

  return translations
}
