import pkg from '../package.json' assert { type: 'json' }

const { version } = pkg

export default {
  version,
  name: 'examples',
  design: 'Joost De Cock',
  code: 'Joost De Cock',
  department: 'womenswear',
  type: 'pattern',
  difficulty: 1,
  tags: ['example'],
  optionGroups: {
    fit: ['fixme'],
  },
  measurements: [],
  dependencies: {
    //point_attr: 'path_attr'
  },
  parts: [
    'point_attr',
    'path_move',
    'path_line',
    'path_curve',
    'path__curve',
    'path_curve_',
    'path_close',
    'path_ops',
    'path_attr',
    'path_clone',
    'path_divide',
    'path_edge',
    'path_end',
    'path_intersects',
    'path_intersectsx',
    'path_intersectsy',
    'path_join',
    'path_length',
    'path_noop',
    'path_offset',
    'path_reverse',
    'path_shiftalong',
    'path_shiftfractionalong',
    'path_split',
    'path_start',
    'path_translate',
    'path_trim',
    'plugin_banner',
    'plugin_bartack',
    'plugin_bartackalong',
    'plugin_bartackfractionalong',
    'plugin_buttons',
    'plugin_cutonfold',
    'plugin_dimension',
    'plugin_gore',
    'plugin_grainline',
    'plugin_logo',
    'plugin_mirror',
    'plugin_notches',
    'plugin_round',
    'plugin_scalebox',
    'plugin_sprinkle',
    'plugin_title',
    'point_angle',
    'point_attr',
    'point_clone',
    'point_copy',
    'point_dist',
    'point_dx',
    'point_dy',
    'point_flipx',
    'point_flipy',
    'point_shift',
    'point_shiftfractiontowards',
    'point_shifttowards',
    'point_shiftoutwards',
    'point_sitson',
    'point_sitsroughlyon',
    'point_rotate',
    'point_translate',
    'settings_sa',
    'snippet',
    'snippet_attr',
    'snippet_clone',
    'snippets_bnotch',
    'snippets_notch',
    'snippets_button',
    'snippets_buttonhole',
    'snippets_buttonhole_start',
    'snippets_buttonhole_end',
    'snippets_snapsocket',
    'snippets_snapstud',
    'snippets_logo',
    'utils_linesintersect',
    'utils_beamsintersect',
    'utils_beamintersectsx',
    'utils_beamintersectsy',
    'utils_beamintersectscurve',
    'utils_lineintersectscurve',
    'utils_curvesintersect',
    'utils_pointonbeam',
    'utils_pointonline',
    'utils_pointoncurve',
    'utils_circlesintersect',
    'utils_beamintersectscircle',
    'utils_lineintersectscircle',
    'utils_curveintersectsy',
    'utils_curveintersectsx',
    'utils_splitcurve',
    'docs_overview',
    'docs_coords',
  ],
  options: {
    focus: '',
    // Optiongroups are needed for now, because workbench
    fixme: {
      pct: 50,
      min: 0,
      max: 100,
    },
  },
}
