/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Cuenta",
  "blog": "Blog",
  "community": "Comunidad",
  "designs": "Diseños",
  "docs": "Documentación",
  "showcase": "Escaparate",
  "sloganCome": "Ven por los patrones de costura",
  "sloganStay": "Quédate por la comunidad"
}

export default common
