/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cty = {
  "wafsHashtag": "Costura sin WeAres",
  "weAreACommunityOfMakers": "Somos una comunidad de creadores",
  "weProvideMtmSewingPatterns": "Proporcionamos patrones de costura a medida",
  "isAPatron": "es un patrón",
  "contributesWith": "contribuye con",
  "communityBuilding": "Edificio comunitario",
  "development": "Desarrollo",
  "patternTesting": "Pruebas de patrón",
  "patternDesign": "Diseño de patrón",
  "support": "Soporte",
  "translation": "Traducción",
  "writing": "Escribir",
  "whereToFindUs": "Dónde encontrarnos",
  "whoWeAre": "Quiénes somos",
  "community": "Comunidad",
  "team": "Equipo",
  "teams": "Equipos",
  "contributors": "Colaboradores",
  "calls": "Llamadas de colaborador"
}

export default cty
