/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "La página que estás buscando no se encuentra",
  "confirmationNotFound": "Si llegó a esta página a través del enlace en un correo electrónico de confirmación, le recomendamos que informe de este problema.",
  "emailExists": "Ya tenemos un usuario con esa dirección de correo electrónico. Tal vez le gustaría iniciar sesión en su lugar?",
  "networkError": "El backend o la red parecen estar apagados",
  "notAValidImageFormat": "No es un formato de imagen válido",
  "requestFailedWithStatusCode400": "Solicitud fallida",
  "requestFailedWithStatusCode401": "Autenticación fallida",
  "requestFailedWithStatusCode403": "Prohibido",
  "requestFailedWithStatusCode500": "Hubo un problema inesperado. Por favor informe de esto.",
  "something": "Algo salió mal"
}

export default errors
