/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "Alemán",
  "en": "Inglés",
  "es": "Español",
  "fr": "Francés",
  "nl": "Holandés"
}

export default i18n
