/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const intro = {
  "txt-blog": "Noticias, actualizaciones y anuncios del equipo de freesewing.",
  "txt-community": "Todo es llevado por colaboradores voluntarios. TNo hay ninguna entidad comercial detrás de, o vinculada a, este proyecto.",
  "txt-different": "En qué somos diferentes",
  "txt-draft": "Elige uno de los patrones, elige un model y elige tus opciones. Nosotros hacemos el resto",
  "txt-how": "Cómo funciona",
  "txt-join": "Únete a miles de personas y regístrate en freesewing.org.",
  "txt-model": "Todos nuestros patrones son a medida. Así que lo primero que necesitas es un metro.",
  "txt-newHere": "Si eres nuevo aquí, el mejor lugar para comenzar es nuestra demostración:",
  "txt-opensource": "Nuestra plataforma, nuestros patrones e incluso este sitio web. Todo nuestro código está disponible en GitHub. Modificaciones son bienvenidas!",
  "txt-patrons": "Freesewing es posible por el apoyo económico de nuestros patrocinadores. Desplácese hacia abajo para conocer nuestro modelo de suscripción.",
  "txt-showcase": "Proyectos terminados de la comunidad de freesewing"
}

export default intro
