/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "Ver <a href='/docs/sewing/basting/'>hilvanar</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "coverlock.d": "Ver <a href='/docs/sewing/coverlock/'>Coverlock</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "cutting.d": "Ver <a href='/docs/sewing/cutting/'>Cortando</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "darts.d": "Ver <a href='/docs/sewing/darts/'>Dardos</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "doubleWeltPockets.d": "Vea <a href='/docs/sewing/double-welt-pockets/'>Bolsillos de doble soldadura</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "ease.d": "Ve <a href='/docs/sewing/ease/'>Sube</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "edgestitch.d": "Ver <a href='/docs/sewing/edgestitching/'>pespunte</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "fabricGrain.d": "Ver <a href='/docs/sewing/fabric-grain/'>Grano de tela</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "goodSidesTogether.d": "Ver <a href='/docs/sewing/good-sides-together/'>buenas partes juntas</a> en la <a href='/docs/sewing/'>documentación de costura</a>",
  "onTheFold.d": "Ver <a href='/docs/sewing/on-the-fold/'>En el plegado</a> en la <a href='/docs/sewing/'>documentación de costura</a>",
  "hemming.d": "Ver <a href='/docs/sewing/hemming/'>Hemming</a> en la <a href='/docs/sewing'>documentación de coser</a>",
  "jersey.d": "Ver <a href='/docs/sewing/jersey/'>Jersey</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "knitBinding.d": "Ver <a href='/docs/sewing/knit-binding/'>Enlace de Knit</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "knitFabric.d": "Ver <a href='/docs/sewing/knit-fabric/'>Tela de Knit</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "pinning.d": "Ver <a href='/docs/sewing/pinning/'>Fijar</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "rayon.d": "Ver <a href='/docs/sewing/rayon/'>Rayon</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "sa.d": "Ver <a href='/docs/sewing/seam-allowance/'>Permiso de costura</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "serger.d": "Ver <a href='/docs/sewing/serger/'>Serger</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "slipstitch.d": "Ver <a href='/docs/sewing/slipstitch/'>punto deslizado</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "topstitching.d": "Ver <a href='/docs/sewing/topstitching/'>Topstitching</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "trimming.d": "Ver <a href='/docs/sewing/trimming/'>Trimming</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "twinNeedle.d": "Ver <a href='/docs/sewing/twin-neelde/'>aguja gemela</a> en la <a href='/docs/sewing'>documentación de costura</a>",
  "zigZag.d": "Ver <a href='/docs/sewing/zig-zag-stitch/'>Zig-zag stitch</a> en la <a href='/docs/sewing'>documentación de cobertura</a>",
  "freesewing.d": "<b>FreeSewing</b> es una plataforma de código abierto para patrones de costura hechos a medida",
  "patternOptions.d": "Las <b>opciones de patrón</b> te permiten personalizar el diseño del patrón",
  "draftSettings.d": "Los <b>ajustes del boceto</b> te permiten controlar cómo se genera un patrón",
  "patrons.d": "Los mecenas apoyan a Freesewing económicamente. Son colaboradores fieles que aseguran un futuro sostenible para freesewing.org, nuestro código, nuestros patrones y nuestra comunidad.",
  "msf.d": "Médicos Sin Fronteras/Médecins Sans Frontières - Ver <a href='https://msf.org/'>msf.org</a>"
}

export default jargon
