/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const measurements = {
  "ankle": "circunstancia del tobillo",
  "biceps": "Contorno del brazo",
  "bustFront": "Frente de polvo",
  "bustPointToUnderbust": "Debe apuntar a la base",
  "bustSpan": "Distancia entre pechos",
  "chest": "Contorno de pecho",
  "crossSeam": "Costura cruzada",
  "crossSeamFront": "Costura cruzada frontal",
  "head": "Contorno de cabeza",
  "heel": "Heel circumference",
  "highBustFront": "Frontal de bust alto",
  "highBust": "Contorno de alto pecho",
  "hips": "Contorno de caderas",
  "hpsToBust": "HPS para quebrar",
  "hpsToWaistBack": "HPS a cintura atrás",
  "hpsToWaistFront": "HPS a cintura frontal",
  "inseam": "Tiro",
  "knee": "circunstancia de rodilla",
  "neck": "Contorno de cuello",
  "seat": "Contorno de asiento",
  "seatBack": "Retroceder",
  "crotchDepth": "Profundidad de cromo",
  "shoulderSlope": "Pendiente del hombro",
  "shoulderToElbow": "Hombro a codo",
  "shoulderToShoulder": "Distancia entre hombros",
  "shoulderToWrist": "Codo a muñeca",
  "underbust": "Bajo pecho",
  "upperLeg": "Contorno de alto de pierna",
  "waist": "Circunferencia de Waist",
  "waistBack": "Volver",
  "waistToFloor": "Llave al suelo",
  "waistToHips": "Espera a caderas",
  "waistToKnee": "Espera a rodilla",
  "waistToSeat": "Espera a asiento",
  "waistToUnderbust": "Espera a bajo busto",
  "waistToUpperLeg": "Ira a la pierna superior",
  "wrist": "Contorno de muñeca"
}

export default measurements
