/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Caída de la sisa",
  "armholeDrop.d": "Baja la sisa esta cantidad. Valores negativos la elevan.",
  "backlineBend.t": "Forma posterior de la sisa",
  "backlineBend.d": "Determina la forma/curva de la parte posterior de la sisa.",
  "hipsEase.t": "Holgura de cadera",
  "hipsEase.d": "La cantidad de holgura en la cadera.",
  "necklineBend.t": "Forma del cuello",
  "necklineBend.d": "Determina la forma/curva del cuello en el frente.",
  "necklineDrop.t": "Caída del escote",
  "necklineDrop.d": "La cantidad de cuello que se corta en el frente.",
  "shoulderStrapPlacement.t": "Posición de los tirantes",
  "shoulderStrapPlacement.d": "Determina si los tirantes se colocan cerca del cuello (números más bajos) o del hombro (números más altos).",
  "shoulderStrapWidth.t": "Anchura de los tirantes",
  "shoulderStrapWidth.d": "La anchura de los tirantes.",
  "stretchFactor.t": "Extensión",
  "stretchFactor.d": "Determina la holgura negativa horizontal."
}

export default o_aaron
