/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Abertura de la espalda",
  "backOpening.d": "Controla la apertura en la parte trasera del Profeta",
  "chestDepth.t": "Longitud del Strp",
  "chestDepth.d": "Controla la longitud de las correas",
  "lengthBonus.t": "Bonus de longitud",
  "lengthBonus.d": "Controla la longitud del buque",
  "bibLength.t": "Longitud de bib",
  "bibLength.d": "Controla la longitud de la bib",
  "bibWidth.t": "Ancho bib",
  "bibWidth.d": "Controla el ancho de la bib",
  "strapWidth.t": "Strap width",
  "strapWidth.d": "Controla el ancho de la correa"
}

export default o_albert
