/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Manga doblada",
  "sleeveBend.d": "Curva de la manga en el codo.",
  "sleevecapHeight.t": "Altura de la manga",
  "sleevecapHeight.d": "Controla la altura de la manga."
}

export default o_bent
