/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Cinta de ajuste",
  "adjustmentRibbon.d": "Incluir o no una cinta de ajuste",
  "bandLength.t": "Longitud de la banda",
  "bandLength.d": "Longitud de la banda",
  "tipWidth.t": "Ancho de la punta",
  "tipWidth.d": "Ancho de las puntas",
  "knotWidth.t": "Ancho de nudo",
  "knotWidth.d": "Ancho del nudo",
  "bowLength.t": "Longitud del lazo",
  "bowLength.d": "Longitud del lazo (cuando está anudado)",
  "bowStyle.t": "Estilo del lazo",
  "bowStyle.d": "Estilo del lazo",
  "endStyle.t": "Estilo de las puntas",
  "endStyle.d": "Estilo de las puntas del lazo",
  "collarEase.t": "Facilidad de cuello",
  "collarEase.d": "The amount of ease at your neck",
  "ribbonWidth.t": "Ribbon width",
  "ribbonWidth.d": "Width of the ribbon"
}

export default o_benjamin
