/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bella = {
  "chestEase.t": "Holgura de pecho",
  "chestEase.d": "Controla la cantidad de facilidad en la parte más completa de tu cofre",
  "waistEase.t": "Holgura de cintura",
  "waistEase.d": "Controla la cantidad de facilidad en tu cintura",
  "bustSpanEase.t": "Facilidad de la expansión del polvo",
  "bustSpanEase.d": "Controla la cantidad de facilidad (horizontal) que se agrega a tu superficie de busto al ubicar el punto de busto.",
  "fullChestEaseReduction.t": "Full chest ease reduction",
  "fullChestEaseReduction.d": "Allows you to independently reduce the ease around the chest to make it fit tight(er) in that area",
  "backDartHeight.t": "Altura del dart trasero",
  "backDartHeight.d": "Controla la altura del dart posterior",
  "bustDartLength.t": "Longitud del dart del polvo",
  "bustDartLength.d": "Controla la longitud del polvo",
  "waistDartLength.t": "Longitud del dart de Waist",
  "waistDartLength.d": "Controla la longitud del dardo de la cintura",
  "bustDartCurve.t": "Curva darda de busto",
  "bustDartCurve.d": "Controla la curvatura del polvo",
  "armholeDepth.t": "Profundidad del orificio",
  "armholeDepth.d": "Controla la profundidad del orificio",
  "backArmholeSlant.t": "Slant del orificio trasero",
  "backArmholeSlant.d": "Rota ligeramente el orificio alrededor de su punto de zanja",
  "frontArmholeCurvature.t": "Front armhole curvature",
  "frontArmholeCurvature.d": "Controls how deep the armhole is scooped out at the front bottom",
  "backArmholeCurvature.t": "Curvatura del orificio trasero",
  "backArmholeCurvature.d": "Controla la profundidad del agujero de armadura en la parte trasera",
  "frontArmholePitchDepth.t": "Profundidad del tono del orificio delantero",
  "frontArmholePitchDepth.d": "Modifica la posición horizontal del punto de giro del blindaje frontal",
  "backArmholePitchDepth.t": "Profundidad del tono del orificio trasero",
  "backArmholePitchDepth.d": "Modifica la posición horizontal del punto de giro del orificio trasero",
  "backNeckCutout.t": "Corte trasero del cuello",
  "backNeckCutout.d": "Controla la profundidad de la apertura del cuello en la espalda",
  "backHemSlope.t": "Pendiente trasera",
  "backHemSlope.d": "Controla la pendiente del hem en la espalda",
  "frontShoulderWidth.t": "Ancho del hombro frontal",
  "frontShoulderWidth.d": "Controla la estrechez de los hombros delanteros relativos a la parte trasera",
  "highBustWidth.t": "Ancho de bust alto",
  "highBustWidth.d": "Le permite ajustar el ancho del polvo alto en la parte frontal"
}

export default o_bella
