/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Bulto",
  "bulge.d": "Incrementar el ángulo para crear más espacio en el bolsillo delantero.",
  "legBonus.t": "Extra de longitud de pierna",
  "legBonus.d": "La longitud extra a añadir a las perneras.",
  "rise.t": "Elevación de la cintura",
  "rise.d": "La cantidad a elevar la cintura. Valores negativos la bajan.",
  "stretch.t": "Extensión",
  "stretch.d": "La cantidad de holgura negativa.",
  "legStretch.t": "Estiramiento de la pernera",
  "legStretch.d": "Para mejores resultados, junta tus piernas más; di no a los huecos.",
  "backRise.t": "Elevación de la espalda",
  "backRise.d": "Porcentaje en el que la cintura se elevará en la espalda."
}

export default o_bruce
