/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Dardo de hombro",
  "shoulderDart.d": "Incluir o no un dardo en el hombro para redondear la espalda",
  "shoulderDartSize.t": "Tamaño dart de hombro",
  "shoulderDartSize.d": "El tamaño del dart del hombro",
  "shoulderDartLength.t": "Longitud del dart del hombro",
  "shoulderDartLength.d": "La longitud del dart del hombro",
  "waistDart.t": "Dardo de Waist",
  "waistDart.d": "Incluir o no un dardo en la cintura para redondear la espalda",
  "waistDartSize.t": "Tamaño dart de Waist",
  "waistDartSize.d": "El tamaño del dardo de la cintura",
  "waistDartLength.t": "Longitud del dart de Waist",
  "waistDartLength.d": "La longitud del dardo de la cintura",
  "verticalEase.t": "Fácil vertical",
  "verticalEase.d": "La cantidad de facilidad para distribuir a lo largo de la ropa",
  "waistEase.t": "Holgura de cintura",
  "waistEase.d": "La cantidad de facilidad en la cintura",
  "primaryBustDart.t": "Dardo de busto",
  "primaryBustDart.d": "Donde colocar el polvo para dar forma al cofre",
  "primaryBustDartLength.t": "Longitud del dart del polvo",
  "primaryBustDartLength.d": "La longitud del polvo",
  "secondaryBustDart.t": "Armadura de polvo secundaria",
  "secondaryBustDart.d": "Opcionalmente incluye un polvo secundario para distribuir la forma del cofre",
  "secondaryBustDartLength.t": "Longitud del polvo secundario",
  "secondaryBustDartLength.d": "La longitud del polvo secundario",
  "primaryBustDartShaping.t": "Dardos de busto que conforman",
  "primaryBustDartShaping.d": "Controla el equilibrio entre los dardos principales y secundarios"
}

export default o_breanna
