/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlton = {
  "seatEase.t": "Holgura de asiento",
  "seatEase.d": "Cantidad de facilidad alrededor de tu trasero",
  "pocketPlacementHorizontal.t": "Colocación horizontal del bolsillo",
  "pocketPlacementHorizontal.d": "La ubicación (horizontal) de los bolsillos",
  "pocketPlacementVertical.t": "Colocación vertical del bolsillo",
  "pocketPlacementVertical.d": "La ubicación (vertical) de los bolsillos",
  "collarHeight.t": "Altura del cuello",
  "collarHeight.d": "Altura del cuello",
  "length.t": "Longitud",
  "length.d": "Largo total",
  "pocketFlapRadius.t": "Radio de la tapa del bolsillo",
  "pocketFlapRadius.d": "La cantidad por la cual se redondea la solapa del bolsillo",
  "pocketRadius.t": "Radio de bolsillo",
  "pocketRadius.d": "La cantidad por la cual se redondea el bolsillo",
  "chestPocketHeight.t": "Altura del bolsillo pecho",
  "chestPocketHeight.d": "Altura del bolsillo del pecho",
  "beltWidth.t": "Ancho del cinturón",
  "beltWidth.d": "Ancho del cinturón",
  "buttonSpacingHorizontal.t": "Espaciado horizontal de los botones",
  "buttonSpacingHorizontal.d": "El espaciado horizontal de los botones, también determina la superposición del cierre frontal"
}

export default o_carlton
