/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cathrin = {
  "panels.t": "Número de paneles",
  "panels.d": "La cantidad de paneles a trazar. Más paneles permiten un mejor ajuste para cuerpos con más curvas.",
  "waistReduction.t": "Reducción de cintura",
  "waistReduction.d": "La cantidad en la que quieres que el corset reduzca la cintura.",
  "backOpening.t": "Abertura de la espalda",
  "backOpening.d": "Abertura en el centro del cierre de la espalda.",
  "backRise.t": "Elevación de la espalda",
  "backRise.d": "Cantidad en que los paneles traseros se elevan sobre el centro de la espalda",
  "backDrop.t": "Caída de la espalda",
  "backDrop.d": "En qué medida los paneles posteriores se extienden bajo la cadera. Valores negativos los elevan sobre ella.",
  "frontRise.t": "Elevación frontal",
  "frontRise.d": "Cuánto se eleva el panel frontal entre tus pechos. Valores negativos lo bajan.",
  "frontDrop.t": "Caída frontal",
  "frontDrop.d": "Cuánto los paneles frontales caen bajo la cadera en el centro por delate.",
  "hipRise.t": "Elevación de la cadera",
  "hipRise.d": "Cuánto se elevan los paneles laterales sobre tu cadera."
}

export default o_cathrin
