/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlita = {
  "contour.t": "Contorno",
  "contour.d": "Controla cómo de abrubtamente se ajustan las costuras princesa."
}

export default o_carlita
