/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_charlie = {
  "backPocketHorizontalPlacement.t": "Colocación horizontal del bolsillo trasero",
  "backPocketHorizontalPlacement.d": "Controla la posición horizontal del bolsillo trasero",
  "backPocketVerticalPlacement.t": "Colocación vertical del bolsillo trasero",
  "backPocketVerticalPlacement.d": "Controla la posición vertical del bolsillo trasero",
  "backPocketWidth.t": "Ancho del bolsillo trasero",
  "backPocketWidth.d": "Controla el ancho del bolsillo trasero",
  "backPocketDepth.t": "Profundidad del bolsillo trasero",
  "backPocketDepth.d": "Controla la profundidad del bolsillo trasero",
  "backPocketFacing.t": "Back pocket facing",
  "backPocketFacing.d": "Controls whether or not to include facing on the back pockets",
  "frontPocketSlantDepth.t": "Profundidad delantera de bolsillo",
  "frontPocketSlantDepth.d": "Controla la profundidad de la capa delantera del bolsillo",
  "frontPocketSlantWidth.t": "Anchura del bolsillo delantero",
  "frontPocketSlantWidth.d": "Controla el ancho de la franja del bolsillo (delante)",
  "frontPocketSlantRound.t": "Pócket delantero slant round",
  "frontPocketSlantRound.d": "Controla qué tan lejos del final del esclavizado empezamos a redondear hacia el exterior",
  "frontPocketSlantBend.t": "Pócket delantero inclinado",
  "frontPocketSlantBend.d": "Controla el radio por el cual redondeamos el bolsillo hacia el exterior",
  "frontPocketWidth.t": "Ancho bolsillo frontal",
  "frontPocketWidth.d": "Controla el ancho de la bolsa de bolsillo frontal",
  "frontPocketDepth.t": "Profundidad de bolsillo frontal",
  "frontPocketDepth.d": "Controla la profundidad de la bolsa de bolsillo frontal",
  "frontPocketFacing.t": "Pócket frontal",
  "frontPocketFacing.d": "Controla hasta qué punto la cara del bolsillo se extiende a la bolsa de bolsillo",
  "beltLoops.t": "Bucles de cinturón",
  "beltLoops.d": "Controla la cantidad de bucles de cinta",
  "flyCurve.t": "Curva de vuelo",
  "flyCurve.d": "Controla la curvatura de la mosca J-costura",
  "flyLength.t": "Longitud del vuelo",
  "flyLength.d": "Controla la longitud de la mosca",
  "flyWidth.t": "Fly width",
  "flyWidth.d": "Controla hasta qué punto la costura J del desplazamiento del borde de la mosca",
  "waistbandCurve.t": "Curva de Waistband",
  "waistbandCurve.d": "Controla lo curvada que es la banda de cintura."
}

export default o_charlie
