/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cornelius = {
  "fullness.t": "Cumplimiento",
  "fullness.d": "Controla la integridad de los breeches",
  "waistbandBelowWaist.t": "Banda inferior",
  "waistbandBelowWaist.d": "Porcentaje para mover la cintura debajo de la cintura actual",
  "waistReduction.t": "Reducción de cintura",
  "waistReduction.d": "Porcentaje para reducir la cintura",
  "cuffWidth.t": "Cuff width",
  "cuffWidth.d": "Ancho del corte de la pierna",
  "cuffStyle.t": "Estilo del puño",
  "cuffStyle.d": "Estilo del corte de la pierna",
  "bandBelowKnee.t": "Corta debajo de la rodilla",
  "bandBelowKnee.d": "Controla la distancia del corte desde la rodilla",
  "kneeToBelow.t": "Longitud del puño",
  "kneeToBelow.d": "Controla la rigidez del corte en comparación con la rodilla",
  "ventLength.t": "Longitud del ventilador",
  "ventLength.d": "Controla la longitud del ventilador entre la rodilla y el corte"
}

export default o_cornelius
