/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_diana = {
  "shoulderSeamLength.t": "Longitud de la costura de hombro",
  "shoulderSeamLength.d": "Controla la longitud de la costura de hombro",
  "drapeAngle.t": "Ángulo del drapeado",
  "drapeAngle.d": "Controla la cantidad de drapeado"
}

export default o_diana
