/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florent = {
  "headEase.t": "Holgura de cabeza",
  "headEase.d": "La cantidad de holgura alrededor de la cabeza"
}

export default o_florent
