/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florence = {
  "height.t": "Altura",
  "height.d": "Controla la altura de la mascarilla",
  "length.t": "Longitud",
  "length.d": "Controla la longitud de la mascarilla",
  "curve.t": "Curva",
  "curve.d": "Controla la curvatura del borde superior de la mascarilla"
}

export default o_florence
