/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hortensia = {
  "size.t": "Tamaño",
  "size.d": "Controla el tamaño total del bolso",
  "zipperSize.t": "Tamaño Zipper",
  "zipperSize.d": "Qué tamaño de zipper usar",
  "strapLength.t": "Longitud del Strp",
  "strapLength.d": "Controla la longitud de la correa",
  "handleWidth.t": "Anchura del Manejo",
  "handleWidth.d": "Controla el ancho del asa"
}

export default o_hortensia
