/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hugo = {
  "hipsEase.t": "Holgura de cadera",
  "hipsEase.d": "La cantidad de holgura en la cadera."
}

export default o_hugo
