/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_huey = {
  "pocket.t": "Bolsillo",
  "pocket.d": "Si se añade un bolsillo delantero o no",
  "pocketHeight.t": "Altura de bolsillo",
  "pocketHeight.d": "Controla la altura del bolsillo",
  "hoodHeight.t": "Altura de capucha",
  "hoodHeight.d": "Controla la altura del capucha",
  "hoodCutback.t": "Recorta capucha",
  "hoodCutback.d": "Controla cómo abrir el capó se recorta",
  "hoodClosure.t": "Cierre de capucha",
  "hoodClosure.d": "Controla la parte del capó que forma parte del cierre frontal",
  "hoodDepth.t": "Profundidad de capucha",
  "hoodDepth.d": "Controla la profundidad del capucha",
  "hoodAngle.t": "Angulo de capucha",
  "hoodAngle.d": "Controla el ángulo en el que la capucha es unida"
}

export default o_huey
