/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_noble = {
  "dartPosition.t": "Dart position",
  "dartPosition.d": null,
  "chestEase.t": "Chest ease",
  "chestEase.d": "Controls the amount of ease at the chest",
  "waistEase.t": "Waist ease",
  "waistEase.d": "Controls the amount of ease at the waist",
  "bustSpanEase.t": "Bust span ease",
  "bustSpanEase.d": "Controls the amount of ease along the bust span",
  "backDartHeight.t": "Controls the height of the back dart",
  "backDartHeight.d": "Back dart height",
  "waistDartLength.t": "Waist dart length",
  "waistDartLength.d": "Controls the length of the waist dart",
  "shoulderDartPosition.t": "Shoulder dart position",
  "shoulderDartPosition.d": "Controls the position of the shoulder dart",
  "upperDartLength.t": "Upper dart length",
  "upperDartLength.d": "Controls the length of the upper dart",
  "armholeDartPosition.t": "Armhole dart position",
  "armholeDartPosition.d": "Controls the position of the armhole dart",
  "armholeDepth.t": "Armhole depth",
  "armholeDepth.d": "Controls the depth of the armhole",
  "backArmholeSlant.t": "FIXMe",
  "backArmholeSlant.d": "FIXME",
  "backArmholeCurvature.t": "FIXME",
  "backArmholeCurvature.d": "FIXME",
  "frontArmholePitchDepth.t": "FIXME",
  "frontArmholePitchDepth.d": "FIXME",
  "backArmholePitchDepth.t": null,
  "backArmholePitchDepth.d": null,
  "backNeckCutout.t": "Back neck cutout",
  "backNeckCutout.d": "Controls how deep the neck is cutout in the back",
  "backHemSlope.t": "Back hem slope",
  "backHemSlope.d": "Constrols the slope of the back hem",
  "frontShoulderWidth.t": null,
  "frontShoulderWidth.d": null,
  "highBustWidth.t": null,
  "highBustWidth.d": null,
  "shoulderToShoulderEase.t": "Shoulder to shoulder ease",
  "shoulderToShoulderEase.d": "Controls the amount of ease long the shoulder to shoulder measurement"
}

export default o_noble
