/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_paco = {
  "heelEase.t": "Heel ease",
  "heelEase.d": "La cantidad de facilidad en tu talón (cuando pisas la pierna)",
  "frontPockets.t": "Pockets delanteros",
  "frontPockets.d": "Añadir o no bolsillos frontales en la costura lateral",
  "backPockets.t": "Paquetes de retroceso",
  "backPockets.d": "Añadir o no bolsillos de soldadura a la espalda",
  "elasticatedHem.t": "Hilo Elasticado",
  "elasticatedHem.d": "Si desea o no un llavero elasticado",
  "ankleElastic.t": "Anchura elástica Ancla/Hem",
  "ankleElastic.d": "Ancho de elástico (opcional) en el ancla/hem"
}

export default o_paco
