/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_penelope = {
  "backDartDepthFactor.t": "Factor de la pinza trasera",
  "backDartDepthFactor.d": "Hasta dónde llega la pinza trasera desde la cintura. Es proporción de la medida cintura natural a asiento.",
  "backVent.t": "Ventilación posterior",
  "backVent.d": "Añade una avertura en la parte trasera de la falda.",
  "backVentLength.t": "Longitud de ventilación posterior",
  "backVentLength.d": "Longitud de la abertura trasera como porcentaje de la longitud de la falda.",
  "dartToSideSeamFactor.t": "Factor pinza a costura lateral",
  "dartToSideSeamFactor.d": "Porcentaje de cuánta de la reducción de cadera a cintura se toma de las pinzas con respecto a las costuras laterales.",
  "frontDartDepthFactor.t": "Factor de la pinza delantera",
  "frontDartDepthFactor.d": "Hasta dónde llega la pinza delantera desde la cintura. Es proporción de la medida cintura natural a asiento.",
  "hem.t": "Anchura del dobladillo",
  "hem.d": "El tamaño del dobladillo. Medida en valores absolutos.",
  "hemBonus.t": "Bonus del dobladillo",
  "hemBonus.d": "Esta opción reduce la circunferencia de la falda en el dobladillo. Porcentaje de la medida de asiento.",
  "lengthBonus.t": "Extra de longitud",
  "lengthBonus.d": "Esto ajusta la longitud de la falda. Porcentaje de la medida de cintura natural a rodilla.",
  "nrOfDarts.t": "Número de pinzas",
  "nrOfDarts.d": "El número de pinzas usadas en el patrón. El máximo es 2. Esta opción puede ser reducida por el patrón si los cálculos crean pinzas demasiado pequeñas.",
  "seatEase.t": "Facilidad de asiento",
  "seatEase.d": "La holgura al nivel del asiento.",
  "waistBand.t": "Cinturilla",
  "waistBand.d": "Añade una cinturilla al patrón.",
  "waistBandWidth.t": "Anchura de la cinturilla",
  "waistBandWidth.d": "La anchura de la cinturilla.",
  "waistEase.t": "Holgura de cintura",
  "waistEase.d": "La holgura al nivel de la cintura.",
  "zipperLocation.t": "Ubicación de la cremallera",
  "zipperLocation.d": "La ubicación de la cremallera."
}

export default o_penelope
