/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sandy = {
  "waistbandWidth.t": "Anchura de la cinturilla",
  "waistbandWidth.d": "Controla la anchura de la cinturilla.",
  "waistbandPosition.t": "Posición de la cinturilla",
  "waistbandPosition.d": "Controla la posición de la cinturilla.",
  "waistbandShape.t": "Forma de la cinturilla",
  "waistbandShape.d": "Si quieres una cinturilla recta o curvada.",
  "circleRatio.t": "Porcentaje de círculo",
  "circleRatio.d": "El porcentaje de círculo que quieres que tenga la falda.",
  "waistbandOverlap.t": "Superposición de la cinturilla",
  "waistbandOverlap.d": "La cantidad en la que los extremos de la cinturilla se superponen.",
  "gathering.t": "Fruncido",
  "gathering.d": "El porcentaje por el que la parte superior de la falda es más largo que la parte inferior de la cinturilla.",
  "seamlessFullCircle.t": "Círculo completo sin costura",
  "seamlessFullCircle.d": "Permite una falda de círculo completo sin costuras.",
  "hemWidth.t": "Hem width",
  "hemWidth.d": "Anchura del dobladillo"
}

export default o_sandy
