/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_shin = {
  "legReduction.t": "Reducción de pierna",
  "legReduction.d": "Reduce la apertura de la pierna para prevenir que se abra",
  "elasticWidth.t": "Elastic width",
  "elasticWidth.d": "Width of the elastic at the waist"
}

export default o_shin
