/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_simone = {
  "bustDartAngle.t": "Ángulo de dardos de polvo",
  "bustDartAngle.d": "Controla el ángulo por el cual el (lado) dardos de polvo tiene pendiente descendente",
  "bustDartLength.t": "Longitud del dart del polvo",
  "bustDartLength.d": "Controla cómo se acerca el polvo al punto de busto",
  "contour.t": "Contorno",
  "contour.d": "Controla cómo se elimina de nuevo el espacio extra para los senos debajo del cofre",
  "frontDarts.t": "Dardos delanteros",
  "frontDarts.d": "Incluya o no las artes frontales",
  "frontDartLength.t": "Longitud del dart frontal",
  "frontDartLength.d": "Controla cómo se acerca el dardo frontal al punto de polvo"
}

export default o_simone
