/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sven = {
  "hipsEase.t": "Holgura de cadera",
  "hipsEase.d": "Controla la cantidad de holgura en las caderas (en la parte de abajo de la sudadera)",
  "ribbing.t": "Tejido acanalado",
  "ribbing.d": "Ya sea para terminar el dobladillo y los puños con tejido acanalado.",
  "ribbingHeight.t": "Altura de tejido acanalado",
  "ribbingHeight.d": "La altura del tejido acanalado en los puños y el dobladillo.",
  "ribbingStretch.t": "Extensión de tejido acanalado",
  "ribbingStretch.d": "La cantidad de holgura negativa de tejido acanalado."
}

export default o_sven
