/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tamiko = {
  "flare.t": "Ensanchamiento",
  "flare.d": "La cantidad por la cual la prenda se ensancha desde tu pecho hacia abajo.",
  "shoulderseamLength.t": "Longitud de la costura de hombro",
  "shoulderseamLength.d": "La longitud de la costura del hombro, como un factor de la medida de su hombro a hombro.",
  "shoulderSlope.t": "Inclinación de hombro",
  "shoulderSlope.d": "Controla el ángulo de las costuras del hombro"
}

export default o_tamiko
