/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Borrador para alta caída",
  "draftForHighBust.d": "Borra el patrón para la medición alta del polvo (si está disponible) en lugar del cofre (completo). Esto dará lugar a una prenda más ajustada para las personas con senos.",
  "sleeveEase.t": "Manga fácil",
  "sleeveEase.d": "Cantidad de facilidad de sus mangas",
  "sleeveLength.t": "Longitud de la manga",
  "sleeveLength.d": "Controla la longitud de las mangas",
  "necklineBend.t": "Curvatura neckline",
  "necklineBend.d": "Controla la curvatura del cuello.",
  "necklineDepth.t": "Profundidad del cuello",
  "necklineDepth.d": "Controla la profundidad de la abertura del cuello.",
  "necklineWidth.t": "Neckline width",
  "necklineWidth.d": "Controla el ancho de la abertura del cuello."
}

export default o_teagan
