/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_theo = {
  "wedge.t": "Cuña",
  "wedge.d": "Controla la longitud de la costura cruzada",
  "legWidth.t": "Ancho de la pierna",
  "legWidth.d": "Controla la anchura de la pernera"
}

export default o_theo
