/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_titan = {
  "kneeEase.t": "Facilidad de rodilla",
  "kneeEase.d": "Controla el amout de la facilidad en la rodilla",
  "waistHeight.t": "Altura de la muñeca",
  "waistHeight.d": "Controla la altura de la cintura, 100% = altura de la cintura, 0% = altura de la cadera",
  "lengthBonus.t": "Bonus de longitud",
  "lengthBonus.d": "Controla la longitud de los pantalones",
  "crotchDrop.t": "Gota de cromo",
  "crotchDrop.d": "Reduce el cromo para un ajuste más relajado",
  "fitKnee.t": "Ajustar la rodilla",
  "fitKnee.d": "Se ajusta a las piernas en base a la circunstancia de la rodilla, en lugar de la circunstancia del asiento",
  "legBalance.t": "Saldo de pierna",
  "legBalance.d": "Controla la relación entre el panel frontal y trasero de la pierna",
  "crossSeamCurveStart.t": "Inicio de la curva de costura cruzada",
  "crossSeamCurveStart.d": "Controla hasta qué punto en la costura cruzada empezamos a curvar",
  "crossSeamCurveBend.t": "curva de costura cruzada",
  "crossSeamCurveBend.d": "Controla la curvatura de la costura cruzada",
  "crossSeamCurveAngle.t": "Ángulo de costura cruzada",
  "crossSeamCurveAngle.d": "Controla el ángulo de la costura cruzada",
  "crotchSeamCurveStart.t": "Inicio de la curva de costura de cromo",
  "crotchSeamCurveStart.d": "Controla hasta qué punto en la costura del cromo empezamos a curva",
  "crotchSeamCurveBend.t": "curva de costura cruda",
  "crotchSeamCurveBend.d": "Controla la curvatura de la costura del cromo",
  "crotchSeamCurveAngle.t": "Ángulo de costura cruda",
  "crotchSeamCurveAngle.d": "Controla el ángulo de la costura del cromo",
  "waistBalance.t": "Balance de Waist",
  "waistBalance.d": "Controla la posición horizontal de la cintura relativa al asiento",
  "waistbandWidth.t": "Anchura de la cinturilla",
  "waistbandWidth.d": "El ancho de la cintura",
  "grainlinePosition.t": "Posición en línea",
  "grainlinePosition.d": "Controla la posición horizontal de la pierna relativa al asiento"
}

export default o_titan
