/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_trayvon = {
  "tipWidth.t": "Ancho de la punta",
  "tipWidth.d": "El ancho de tu corbata en la punta",
  "knotWidth.t": "Ancho de nudo",
  "knotWidth.d": "El ancho de tu corbata en el nudo"
}

export default o_trayvon
