/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_unice = {
  "fabricStretchX.t": "Elasticidad de la tela (horizontal)",
  "fabricStretchX.d": "Ajusta esto para telas más o menos elásticas",
  "fabricStretchY.t": "Elasticidad de la tela (vertical)",
  "fabricStretchY.d": "Ajusta esto para telas más o menos elásticas",
  "adjustStretch.t": "Ajuste por elasticidad",
  "adjustStretch.d": "En esta opción puedes poner la elasticidad total del tejido tanto en horizontal como en vertical. Cuando se deshabilita, los valores de elasticidad se usan tal cual",
  "useCrossSeam.t": "Usa el tiro completo",
  "useCrossSeam.d": "Cuando se habilita, la altura total de las piezas del patrón combinadas será la misma que la medida del tiro completo menos las elevaciones frontales y traseras. Cuando se deshabilita, la altura total dependerá de la opción del molde medio o pieza de refuerzo."
}

export default o_unice
