/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_ursula = {
  "fabricStretch.t": "estiramiento de tela",
  "fabricStretch.d": "Ajustar esto para más o menos tela estirada",
  "gussetWidth.t": "Gusset width",
  "gussetWidth.d": "Controla el ancho del set de ráfaga",
  "gussetLength.t": "Longitud del Gusset",
  "gussetLength.d": "Controla la longitud del set de ráfaga",
  "elasticStretch.t": "Estiramiento elástico",
  "elasticStretch.d": "Ajustar esto para elástico más o menos estirado",
  "rise.t": "Elevación de la cintura",
  "rise.d": "Controla la altura de la cintura",
  "legOpening.t": "Apertura de la pierna",
  "legOpening.d": "Controla hasta qué punto se corta la pierna",
  "frontDip.t": "Buceo de cintura frontal",
  "frontDip.d": "Controla cuánto son las curvas de la cintura frontal (revelando más o menos la piel)",
  "backDip.t": "Buceo de cintura trasera",
  "backDip.d": "Controla cuánto son las curvas de la cintura trasera (revelando más o menos la piel)",
  "taperToGusset.t": "Exposición frontal",
  "taperToGusset.d": "Controla la cantidad de piel expuesta en la parte frontal",
  "backExposure.t": "Exposición trasera",
  "backExposure.d": "Controla la cantidad de piel expuesta en la espalda"
}

export default o_ursula
