/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_wahid = {
  "backScyeDart.t": "Pinza posterior de la sisa",
  "backScyeDart.d": "La cantidad a reducir en una pinza en la parte posterior de la sisa.",
  "frontScyeDart.t": "Pinza frontal de la sisa",
  "frontScyeDart.d": "La cantidad a reducir en una pinza en el frente de la sisa.",
  "pocketLocation.t": "Ubicación de bolsillo",
  "pocketLocation.d": "Determina la colocación del bolsillo",
  "pocketWidth.t": "Anchura de bolsillo",
  "pocketWidth.d": "La anchura del bolsillo",
  "weltHeight.t": "Altura de verdugón del bolsillo",
  "weltHeight.d": "La altura de verdugón del bolsillo.",
  "necklineDrop.t": "Caída del cuello",
  "necklineDrop.d": "Determina lo bajo que cae la línea de cuello en la parte delantera",
  "frontStyle.t": "Estilo de la apertura del cuello",
  "frontStyle.d": "Estilo de apertura del cuello",
  "hemStyle.t": "Estilo del dobladillo",
  "hemStyle.d": "Estilo del dobladillo delantero",
  "hemRadius.t": "Radio del dobladillo",
  "hemRadius.d": "Radio por el que el dobladillo es redondeado",
  "backInset.t": "Inserción trasera",
  "backInset.d": "Cuánto de la parte de atrás de la sisa se corta hacia el interior",
  "frontInset.t": "Inserción delantera",
  "frontInset.d": "Cuánto de la parte de delante de la sisa se corta hacia el interior",
  "shoulderInset.t": "Inserción de hombro",
  "shoulderInset.d": "Cuánto la costura del hombro se recorta hacia el interior en el hombro",
  "neckInset.t": "Inserción de cuello",
  "neckInset.d": "Cuánto de la costura del hombro se corta hacia el interior en el cuello",
  "pocketAngle.t": "Ángulo del bolsillo",
  "pocketAngle.d": "Ángulo del forro del bolsillo"
}

export default o_wahid
