/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_waralee = {
  "backPocket.t": "Bolsillo trasero",
  "backPocket.d": "Si se añade un bolsillo trasero o no",
  "frontPocket.t": "Bolsillo delantero",
  "frontPocket.d": "Si se añado un bolsillo frontal o no",
  "hem.t": "Hem size",
  "hem.d": "Tamaño de la temperatura en la parte inferior de los pantalones",
  "waistBand.t": "Banda de Waist",
  "waistBand.d": "Tamaño de la banda de cintura",
  "waistRaise.t": "Aumento de Waist",
  "waistRaise.d": "Cuánto elevar la cintura a partir de la medición de profundidad del asiento, lo que influye en la profundidad del corte de los cojines.",
  "crotchBack.t": "Retroceso",
  "crotchBack.d": "El porcentaje de la circunstancia del asiento que el cráneo de la espalda tiene que ocupar. Esto crea más o menos espacio entre la costura lateral y la espalda.",
  "crotchFront.t": "Frente de cruz",
  "crotchFront.d": "El porcentaje de la circunstancia del asiento que el cráneo delantero debe ocupar. Esto crea más o menos espacio entre la costura lateral y la parte delantera.",
  "crotchFactorBackHor.t": "Factor Horizontal de espalda",
  "crotchFactorBackHor.d": "Utilizado para mover la curva del cromo en la parte trasera horizontalmente",
  "crotchFactorBackVer.t": "Factor horizontal trasero",
  "crotchFactorBackVer.d": "Utilizado para mover verticalmente la curva de la parte trasera",
  "crotchFactorFrontHor.t": "Factor horizontal frontal de cromo",
  "crotchFactorFrontHor.d": "Utilizado para mover la curva del cromo en la parte frontal horizontalmente",
  "crotchFactorFrontVer.t": "Factor vertical delantero de cromo",
  "crotchFactorFrontVer.d": "Utilizado para mover la curva del cromo en el frente verticalmente",
  "waistOverlap.t": "Superposición de Waist",
  "waistOverlap.d": "Esto dicta cuánto quieres que las aletas de las piernas se superpongan a la cintura. Un ajuste de 0 los haría reunirse en la costura lateral y un ajuste de 100 los hace reunirse en la parte delantera/trasera.",
  "legShortening.t": "Acortamiento de la pierna",
  "legShortening.d": "Esto dicta el tiempo que van a ser los pantalones y es un factor de la medición de las costuras. Cuanto más grande sea el valor, más se quitará de la longitud.",
  "backRaise.t": "Ataque trasero",
  "backRaise.d": "Este ajuste levanta la cintura en la espalda. Nuestra cintura no se sienta horizontalmente, sino que está enmarcada en la espalda. Este ajuste le permite levantar esto en la espalda si lo necesita para un buen ajuste."
}

export default o_waralee
