/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const optiongroups = {
  "advanced": "Avanzado",
  "armhole": "Agujero armado",
  "closure": "Cierre",
  "collar": "Cuello",
  "construction": "Construcción",
  "cuffs": "Puños",
  "darts": "Dardos",
  "elastic": "Elástico",
  "fit": "Ajuste",
  "pockets": "Bolsillos",
  "preferences": "Preferencias",
  "sleevecap": "Manga corta",
  "sleeves": "Mangas",
  "style": "Estilo",
  "backPockets": "Paquetes de retroceso",
  "frontPockets": "Pockets delanteros",
  "waistband": "Pretina",
  "fly": "Vuela",
  "bellaDarts": "Pinzas de Bella",
  "bellaArmhole": "Sisa de Bella",
  "bellaAdvanced": "Bella advanced",
  "clavi": "Clavi"
}

export default optiongroups
