/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const patrons = {
  "becomeAPatron": "Conviértete en un mecenas",
  "supportFreesewing": "Apoyo de FreeSewing"
}

export default patrons
