/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const posts = {
  "xMadeThis": "{x} made this",
  "xWroteThis": "{x} wrote this"
}

export default posts
