/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const settings = {
  "advanced.t": "Modo experto",
  "advanced.d": "Controla si mostrar o no la configuración avanzada y las opciones de patrón",
  "paperless.t": "Sin papel",
  "paperless.d": "Dibuja un patrón con todas las dimensiones incluidas para que puedas transferirlo sobre tela u otro medio sin la necesidad de imprimir",
  "sa.t": "Margen de costura",
  "sa.d": "Controla la cantidad de margen de costura incluido en tu patrón",
  "locale.t": "Idioma",
  "locale.d": "Determina el lenguaje utilizado en tu patrón",
  "only.t": "Contenidos",
  "only.d": "Le permite controlar qué partes del patrón se incluirán en su patrón",
  "units.t": "Unidades",
  "units.d": "Controla las unidades utilizadas en tu patrón",
  "margin.t": "Margen",
  "margin.d": "Controla el margen alrededor de las partes del patrón",
  "complete.t": "Detalle",
  "complete.d": "Controla qué tan detallado es el patrón. Ya sea un patrón completo con todos los detalles, o un esquema básico de las partes del patrón",
  "layout.t": "Disposición",
  "layout.d": "Controla cómo se colocan las partes individuales del patrón en tu patrón",
  "debug.t": "Debug",
  "debug.d": "Habilita la depuración para obtener información adicional sobre cómo se creó tu patrón",
  "scale.t": "Escala",
  "scale.d": "Controla el ancho de línea general, el tamaño de fuente y otros elementos que no cambian de escala junto a las medidas del patrón",
  "renderer.t": "Render engine",
  "renderer.d": "Controls how the pattern is rendered (drawn) on the screen",
  "xray.t": "X-ray",
  "xray.d": "Look under the hood with FreeSewing's X-ray mode"
}

export default settings
