/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Selecciona las unidades que deseas utilizar",
  "username": "Elige un nombre de usuario",
  "avatar": "Añade una foto de perfil",
  "bio": "Cuéntanos un poco acerca de ti",
  "social": "Háganos saber dónde podemos seguirle",
  "newsletter": "Danos tu preferencia al boletín de noticias",
  "letUsSetupYourAccount": "Permítanos configurar su cuenta.",
  "walkYouThrough": "Te guiaremos a través de los siguientes pasos:",
  "someOptional": "Aunque todos estos pasos son opcionales, te recomendamos que los recorras para sacar el máximo provecho de FreeSewing."
}

export default welcome
