import { Term as SharedTerm } from 'shared/components/jargon.mjs'

/*
 * This object holds jargon terminology for FreeSewing.dev
 *
 * This object holds key/value pairs per language where:
 *   - key: holds the jargon term (make sure to lowercase it and strip dots)
 *   - value: holds the path to the documentation page as when browsing the website
 *
 * To be clear:
 *   - You need to first create a markdown page explaining the term.
 *   - Only afterwards can you add it here
 *   - Since this uses dynamic MDX loaded from GitHub,it won't work until pushed
 */
// prettier-ignore
const jargon = {
  en: {
    // Sewing
    'basic sewing supplies':     'docs/sewing/basic-sewing-supplies',
    'basting':                   'docs/sewing/basting',
    'coverlock':                 'docs/sewing/coverlock',
    'cutting':                   'docs/sewing/cutting',
    'darts':                     'docs/sewing/darts',
    'double welt pockets':       'docs/sewing/double-welt-pockets',
    'ease':                      'docs/sewing/ease',
    'edgestitching':             'docs/sewing/edgestitching',
    'fabric grain':              'docs/sewing/fabric-grain',
    'good sides together':       'docs/sewing/good-sides-together',
    'hemming':                   'docs/sewing/hemming',
    'highpoint shoulder':        'docs/sewing/hps',
    'hps':                       'docs/sewing/hps',
    'jersey':                    'docs/sewing/jersey',
    'knit binding':              'docs/sewing/knit-binding',
    'knit fabric':               'docs/sewing/knit-fabric',
    'on the fold':               'docs/sewing/on-the-fold',
    'pinning':                   'docs/sewing/pinning',
    'rayon':                     'docs/sewing/rayon',
    'sa':                        'docs/sewing/seam-allowance',
    'seam allowance':            'docs/sewing/seam-allowance',
    'serger':                    'docs/sewing/serger',
    'slipstitch':                'docs/sewing/slipstitch',
    'topstitching':              'docs/sewing/topstitching',
    'trimming':                  'docs/sewing/trimming',
    'twin needle':               'docs/sewing/twin-needle',
    'zig-zag stitch':            'docs/sewing/zig-zag-stitch',
    // Account
    id: 'docs/about/site/account/id',
    uid: 'docs/about/site/account/id',
    'user id': 'docs/about/site/account/id',
    'role': 'docs/about/site/account/role',
  },
  de: {
    // Sewing
    'abnäher':                   'docs/sewing/darts',
    'coverlock':                 'docs/sewing/coverlock',
    'doppelpaspeltaschen':       'docs/sewing/double-welt- pockets',
    'fadenlauf':                 'docs/sewing/fabric-grain',
    'grundlegendes nähzubehör':  'docs/sewing/basic-sewing-supplies',
    'gute seiten zusammen':      'docs/sewing/good-sides-together',
    'heften':                    'docs/sewing/basting',
    'hochpunkt schulter':        'docs/sewing/hps',
    'hps':                       'docs/sewing/hps',
    'im stoffbruch':             'docs/sewing/on-the-fold',
    'jersey':                    'docs/sewing/jersey',
    'nahtzugabe':                'docs/sewing/seam-allowance',
    'randnaht':                  'docs/sewing/edgestitching',
    'rayon':                     'docs/sewing/rayon',
    'serger':                    'docs/sewing/serger',
    'stecken':                   'docs/sewing/pinning',
    'steppstich':                'docs/sewing/slipstitch',
    'strickbindung':             'docs/sewing/knit-binding',
    'strickstoff':               'docs/sewing/knit-fabric',
    'säumen':                    'docs/sewing/hemming',
    'topstitching':              'docs/sewing/topstitching',
    'zickzackstich':             'docs/sewing/zig-zag-stitch',
    'zugabe':                    'docs/sewing/ease',
    'zurückschneiden':           'docs/sewing/trimming',
    'zuschnitt':                 'docs/sewing/cutting',
    'zwillingsnadel':            'docs/sewing/twin-needle',
    // Account
    id:                  'docs/about/site/account/id',
    uid:                 'docs/about/site/account/id',
    'benutzerkennung':   'docs/about/site/account/id',
    'benutzer-id':       'docs/about/site/account/id',
    'benutzer id':       'docs/about/site/account/id',
    'rolle':             'docs/about/site/account/role',
  },
  es: {
    // Sewing
    'aguja gemela':                     "docs/sewing/twin-needle",
    'basting':                          "docs/sewing/basting",
    'bolsillos de doble soldadura':     "docs/sewing/double-welt-pockets",
    'buenas partes juntas':             "docs/sewing/good-sides-together",
    'cobertura':                        "docs/sewing/coverlock",
    'corte':                            "docs/sewing/cutting",
    'costura de bordes':                "docs/sewing/edgestitching",
    'dardos':                           "docs/sewing/darts",
    'en el pliegue':                    "docs/sewing/on-the-fold",
    'fijar':                            "docs/sewing/pinning",
    'grano de tela':                    "docs/sewing/fabric-grain",
    'hemming':                          "docs/sewing/hemming",
    'hombro de punto alto':             "docs/sewing/hps",
    'hps':                              "docs/sewing/hps",
    'jersey':                           "docs/sewing/jersey",
    'margen de costura':                "docs/sewing/seam-allowance",
    'punto elástico':                   "docs/sewing/slipstitch",
    'rayon':                            "docs/sewing/rayon",
    'sargento':                         "docs/sewing/serger",
    'suministros básicos de costura':   "docs/sewing/basic-sewing-supplies",
    'tela de tejidos':                  "docs/sewing/knit-fabric",
    'topstitching':                     "docs/sewing/topstitching",
    'trampa':                           "docs/sewing/trimming",
    'vinculación de nudo':              "docs/sewing/knit-binding",
    'zig-zag stitch':                   "docs/sewing/zig-zag-stitch",
    'único':                            "docs/sewing/ease",
    // Account
    id:                           'docs/about/site/account/id',
    uid:                          'docs/about/site/account/id',
    'id de usuario':              'docs/about/site/account/id',
    'identificador de usuario':   'docs/about/site/account/id',
    'id usuario':                 'docs/about/site/account/id',
    'papel':                      'docs/about/site/account/role',
  },
  fr: {
    // Sewing
    'aiguilles doubles':                   "docs/sewing/twin-needle",
    'aisance':                             "docs/sewing/ease",
    'au pli':                              "docs/sewing/on-the-fold",
    'biais de jersey':                     "docs/sewing/knit-binding",
    'bâtir':                               "docs/sewing/basting",
    'coupe':                               "docs/sewing/cutting",
    'droit fil':                           "docs/sewing/fabric-grain",
    'dégarnir':                            "docs/sewing/trimming",
    'endroit contre endroit':              "docs/sewing/good-sides-together",
    'fourniture de base pour la couture':  "docs/sewing/basic-sewing-supplies",
    'jersey':                              "docs/sewing/jersey",
    'marge de couture':                    "docs/sewing/seam-allowance",
    'ourlet':                              "docs/sewing/hemming",
    'pinces':                              "docs/sewing/darts",
    'poche passepoilée':                   "docs/sewing/double-welt-pockets",
    'point glissé':                        "docs/sewing/slipstitch",
    'point zig-zag':                       "docs/sewing/zig-zag-stitch",
    'rayonne':                             "docs/sewing/rayon",
    'viscose':                             "docs/sewing/rayon",
    'recouvreuse':                         "docs/sewing/coverlock",
    'sommet de l’épaule':                  "docs/sewing/hps",
    'phe':                                 "docs/sewing/hps",
    'surjeteuse':                          "docs/sewing/serger",
    'surpiqûre':                           "docs/sewing/topstitching",
    'surpiqûre nervure':                   "docs/sewing/edgestitching",
    'tissu maille':                        "docs/sewing/knit-fabric",
    'épingler':                            "docs/sewing/pinning",
    // Account
    id:                               'docs/about/site/account/id',
    uid:                              'docs/about/site/account/id',
    "id de l'utilisateur":            'docs/about/site/account/id',
    "identifiant de l'utilisateur":   'docs/about/site/account/id',
    'rôle':                           'docs/about/site/account/role',
  },
  nl: {
    // Sewing
    'aan de stofvouw':           "docs/sewing/on-the-fold",
    'basis naaimateriaal':       "docs/sewing/basic-sewing-supplies",
    'bijknippen':                "docs/sewing/trimming",
    'coverlock':                 "docs/sewing/coverlock",
    'draadrichting':             "docs/sewing/fabric-grain",
    'driegen':                   "docs/sewing/basting",
    'dubbele paspelzak':         "docs/sewing/double-welt-pockets",
    'gebreide stof':             "docs/sewing/knit-fabric",
    'goede kanten op elkaar':    "docs/sewing/good-sides-together",
    'hoog punt schouder':        "docs/sewing/hps",
    'hps':                       "docs/sewing/hps",
    'jersey':                    "docs/sewing/jersey",
    'jersey biezen':             "docs/sewing/knit-binding",
    'knippen':                   "docs/sewing/cutting",
    'naadtoeslag':               "docs/sewing/seam-allowance",
    'nepen':                     "docs/sewing/darts",
    'overwijdte':                "docs/sewing/ease",
    'rayon':                     "docs/sewing/rayon",
    'serger/overlock':           "docs/sewing/serger",
    'sierstiksel':               "docs/sewing/topstitching",
    'spelden':                   "docs/sewing/pinning",
    'stiksels':                  "docs/sewing/edgestitching",
    'stiksteek':                 "docs/sewing/slipstitch",
    'tweelingnaald':             "docs/sewing/twin-needle",
    'zigzagsteek':               "docs/sewing/zig-zag-stitch",
    'zomen':                     "docs/sewing/hemming",
    // Account
    id:                          'docs/about/site/account/id',
    uid:                         'docs/about/site/account/id',
    "gebruikersid":              'docs/about/site/account/id',
    "gebruikers id":             'docs/about/site/account/id',
    "gebruiker id":              'docs/about/site/account/id',
    'rol':                       'docs/about/site/account/role',
  },
  uk: {
    // Sewing
    'базові матеріали для шиття':      'docs/sewing/basic-sewing-supplies',
    'виточки':                         'docs/sewing/darts',
    'джерсі':                          'docs/sewing/jersey',
    'закріплення':                     'docs/sewing/pinning',
    'зметування':                      'docs/sewing/basting',
    'кишеня з подвійною листочкою':    'docs/sewing/double-welt-pockets',
    'коверлок':                        'docs/sewing/coverlock',
    'крайовий шов':                    'docs/sewing/edgestitching',
    'крій':                            'docs/sewing/cutting',
    'лицьові сторони одна до одної':   'docs/sewing/good-sides-together',
    'на згині':                        'docs/sewing/on-the-fold',
    'найвища точка плеча':             'docs/sewing/hps',
    'обрізка':                         'docs/sewing/trimming',
    'поверхневий шов':                 'docs/sewing/topstitching',
    'подвійна голка':                  'docs/sewing/twin-needle',
    'припуск на шов':                  'docs/sewing/seam-allowance',
    'підшивання краю':                 'docs/sewing/hemming',
    'район':                           'docs/sewing/rayon',
    'свобода облягання':               'docs/sewing/ease',
    'сергер':                          'docs/sewing/serger',
    'строчка зигзаг':                  'docs/sewing/zig-zag-stitch',
    'ткацьке переплетення':            'docs/sewing/fabric-grain',
    'трикотажна бийка':                'docs/sewing/knit-binding',
    'трикотажна тканина':              'docs/sewing/knit-fabric',
    'шовний стібок':                   'docs/sewing/slipstitch',
    // Account
    id:                                'docs/about/site/account/id',
    uid:                               'docs/about/site/account/id',
    "ідентифікатор користувача":       'docs/about/site/account/id',
    "ім'я користувача":                'docs/about/site/account/id',
    "ID користувача":                  'docs/about/site/account/id',
    'роль':                            'docs/about/site/account/role',
  },
}

/*
 * DO NOT CHANGE ANYTHING BELOW THIS LINE
 */
export const Term = ({ children }) => <SharedTerm {...{ jargon, children }} site="org" />
