export const collarEase = 0.05
export const armholeDepthFactor = 0.5
export const shoulderEase = 0
export const shoulderSlopeReduction = 0
export const frontArmholeDeeper = 0
export const s3Collar = 0
export const s3Armhole = 0
export const chestEase = { pct: 8, min: 4, max: 20 }
export const hipsEase = { pct: 12, min: 4, max: 20 }
export const cuffEase = { pct: 20, min: 10, max: 50 }
export const lengthBonus = { pct: 10, min: 0, max: 20 }
export const sleeveLengthBonus = { pct: 2, min: 0, max: 10 }
export const ribbingStretch = { pct: 5, min: 0, max: 10 }
export const ribbingHeight = { pct: 10, min: 4, max: 20 }
