export { default as options } from './prebuild/options'
export { default as optionGroups } from './prebuild/option-groups'
export { default as parts } from './prebuild/parts'
export { default as measurements } from './prebuild/measurements'
export { default as optionalMeasurements } from './prebuild/optional-measurements'
export { default as versions } from './prebuild/versions'
export { default as info } from './prebuild/info'

export const list = [
  'aaron',
  'albert',
  'bee',
  'bella',
  'benjamin',
  'bent',
  'bob',
  'breanna',
  'brian',
  'bruce',
  'carlita',
  'carlton',
  'cathrin',
  'charlie',
  'cornelius',
  'diana',
  'florent',
  'florence',
  'hi',
  'holmes',
  'hortensia',
  'huey',
  'hugo',
  'jaeger',
  'lucy',
  'lunetius',
  'noble',
  'octoplushy',
  'paco',
  'penelope',
  'sandy',
  'shin',
  'simon',
  'simone',
  'sven',
  'tamiko',
  'teagan',
  'theo',
  'tiberius',
  'titan',
  'unice',
  'ursula',
  'trayvon',
  'wahid',
  'walburga',
  'waralee',
  'yuri',
]

export const withoutBreasts = [
  'aaron',
  'albert',
  'benjamin',
  'bent',
  'bob',
  'brian',
  'bruce',
  'carlton',
  'charlie',
  'cornelius',
  'florent',
  'florence',
  'hi',
  'holmes',
  'hortensia',
  'huey',
  'hugo',
  'jaeger',
  'lucy',
  'lunetius',
  'octoplushy',
  'paco',
  'penelope',
  'sandy',
  'shin',
  'simon',
  'sven',
  'tamiko',
  'teagan',
  'theo',
  'tiberius',
  'titan',
  'trayvon',
  'unice',
  'ursula',
  'wahid',
  'walburga',
  'waralee',
  'yuri',
]

export const withBreasts = ['bee', 'bella', 'breanna', 'cathrin', 'carlita', 'diana', 'noble', 'simone']
