export const base = {
  name: 'pluginstest.base',
  hide: true,
  draft: ({ part }) => part,
  options: {
    plugin: {
      dflt: 'all',
      list: [
        'all',
        'banner',
        'bartack',
        'buttons',
        'cutonfold',
        'dimension',
        'flip',
        'gore',
        'grainline',
        'i18n',
        'logo',
        'measurements',
        'mirror',
        'notches',
        'round',
        'scalebox',
        'sprinkle',
        'title',
        'versionfreeSvg',
      ],
      menu: 'tests',
    },
  },
}
