// Used in static paths
import { mdxPaths } from 'site/prebuild/mdx-paths.en.mjs'
// Dependencies
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
// Hooks
import { useState, useEffect } from 'react'
import { useNavigation } from 'site/hooks/use-navigation.mjs'
// Components
import Head from 'next/head'
import { PageWrapper, ns } from 'shared/components/wrappers/page.mjs'
import { Spinner } from 'shared/components/spinner.mjs'
import { components } from 'shared/components/mdx/index.mjs'
import { MdxWrapper } from 'shared/components/wrappers/mdx.mjs'
import { Toc } from 'shared/components/mdx/toc.mjs'
import { MdxMetaData } from 'shared/components/mdx/meta.mjs'
import { PrevNext } from 'shared/components/prev-next.mjs'
import { ReadMore } from 'shared/components/mdx/read-more.mjs'
import { NavLinks, Breadcrumbs, MainSections } from 'shared/components/navigation/sitenav.mjs'

/*
 * This page is auto-generated by the prebuild script.
 * Any changes you make will be overwritten on the next (pre)build.
 *
 * See the page-templates folder for more info.
 */
const DocsPage = ({ page, slug }) => {
  const [frontmatter, setFrontmatter] = useState({ title: 'FreeSewing.dev' })
  const [MDX, setMDX] = useState(<Spinner />)
  /*
   * Get the siteNav object from the useNavigation hook
   * FIXME: ignorecontrol is not yet implmented here
   */
  const { siteNav } = useNavigation({ ignoreControl: true })

  /* Load MDX dynamically */
  useEffect(() => {
    const loadMDX = async () => {
      import(`../../../markdown/dev/${slug}/en.md`).then((mod) => {
        setFrontmatter(mod.frontmatter)
        const Component = mod.default
        setMDX(<Component components={components('dev')} />)
      })
    }
    loadMDX()
  }, [slug])

  return (
    <PageWrapper {...page} title={frontmatter.title}>
      <Head>
        <meta property="og:title" content={frontmatter.title} key="title" />
        <meta property="og:type" content="article" key="type" />
        <meta property="og:description" content={``} key="type" />
        <meta property="og:article:author" content="Joost De Cock" key="author" />
        <meta
          property="og:image"
          content={`https://canary.backend.freesewing.org/og-img/en/org/${slug}}`}
          key="image"
        />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:url" content={`https://freesewing.dev/${slug}`} key="url" />
        <meta property="og:locale" content="en" key="locale" />
        <meta property="og:site_name" content="freesewing.dev" key="site" />
        <title>{frontmatter.title} - FreeSewing.dev</title>
      </Head>
      <div className="flex flex-row items-start mt-8 w-full justify-between 2xl:px-36 xl:px-12 px-4">
        <div className="max-w-96 w-1/4 mt-8 hidden lg:block">
          <MainSections {...{ siteNav, slug }} />
          <NavLinks {...{ siteNav, slug }} />
        </div>
        <div className="grow w-full m-auto max-w-prose mt-0 mb-8">
          <div className="w-full">
            <Breadcrumbs {...{ siteNav, slug }} />
            <h1 className="break-words searchme">{frontmatter.title}</h1>
            <div className="block xl:hidden">
              <Toc toc={frontmatter.toc} wrap />
            </div>
          </div>
          <MdxWrapper>{MDX}</MdxWrapper>
          <PrevNext slug={slug} />
        </div>
        <div className="max-w-96 w-1/4 mt-8 hidden xl:block">
          <MdxMetaData frontmatter={frontmatter} slug={slug} locale="en" />
          <div className="hidden xl:block">
            <Toc toc={frontmatter.toc} wrap />
          </div>
        </div>
      </div>
    </PageWrapper>
  )
}

export default DocsPage

/*
 * getStaticProps() is used to fetch data at build-time.
 * To learn more, see: https://nextjs.org/docs/basic-features/data-fetching
 */
export async function getStaticProps({ params }) {
  return {
    props: {
      ...(await serverSideTranslations('en', ['docs', ...ns])),
      slug: params.slug.join('/'),
      page: {
        locale: 'en',
        path: params.slug,
      },
    },
  }
}

/*
 * getStaticPaths() is used to specify for which routes (think URLs)
 * this page should be used to generate the result.
 *
 * On this page, it is returning a list of routes (think URLs) for all
 * the mdx (markdown) content.
 *
 * To learn more, see: https://nextjs.org/docs/basic-features/data-fetching
 */
export async function getStaticPaths() {
  return {
    paths: mdxPaths.map((slug) => '/' + slug),
    fallback: false,
  }
}
