/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cfp = {
  "author": "Author",
  "githubRepo": "GitHub repository",
  "packageManager": "Package manager",
  "patternName": "Pattern name",
  "patternType": "Pattern type",
  "patternCreated": "Your pattern skeleton has been created at",
  "runTheseCommands": "To get started, run this command",
  "startRollup": "In one terminal, start the rollup bundler in watch mode",
  "startWebpack": "It will enter the 'example' folder, and start the development environment.",
  "devDocsAvailableAt": "Developer documentation is available at",
  "talkToUs": "For questions, feedback or suggestions, join our Discord server",
  "draftYourPattern": "Draft your pattern",
  "testYourPattern": "Test your pattern",
  "draftThing": "Draft {thing}",
  "testThing": "Test {thing}",
  "renderInBrowser": "Click below to render your pattern in the browser.",
  "weWillReRender": "When you make changes, we will re-render for you.",
  "youCan": "You can",
  "enterMeasurements": "Enter measurements by hand",
  "preloadMeasurements": "Preload a set of measurements",
  "size": "Size",
  "noRequiredMeasurements": "This pattern has no required measurements",
  "howtoAddMeasurements": "To require measurements, add them to the <b>measurements</b> section of the pattern's configuration file.",
  "seeDocsAt": "Documentation on this topic is available at",
  "clearDesignMode": "Clear design mode",
  "designMode": "Design mode",
  "exportMode": "Export mode",
  "thingIsEnabled": "{thing} is enabled",
  "thingIsDisabled": "{thing} is disabled",
  "turnOn": "Turn on",
  "turnOff": "Turn off",
  "validNameWarning": "Please pick a different name as this name would cause problems.\nWe (re-)use the pattern name as the NPM package name.\nPackage names must be lowercase and cannot contain special characters.\nSo please name your pattern accordingly, like:"
}

export default cfp
