/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "designs": "Designs",
  "sloganCome": "Come for the sewing patterns",
  "sloganStay": "Stay for the community"
}

export default common
