/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Account",
  "blog": "Blog",
  "commumity": "Community",
  "designs": "Designs",
  "docs": "Documentation",
  "showcase": "Showcase",
  "sloganCome": "Come for the sewing patterns",
  "sloganStay": "Stay for the community"
}

export default common
