/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cty = {
  "wafsHashtag": "WeAreFreeSewing",
  "weAreACommunityOfMakers": "We are a community of makers",
  "weProvideMtmSewingPatterns": "We provide made-to-measure sewing patterns",
  "isAPatron": "is a patron",
  "contributesWith": "contributes with",
  "communityBuilding": "Community building",
  "development": "Development",
  "patternTesting": "Pattern testing",
  "patternDesign": "Pattern design",
  "support": "Support",
  "translation": "Translation",
  "writing": "Writing",
  "whereToFindUs": "Where to find us",
  "whoWeAre": "Who we are",
  "community": "Community",
  "team": "Team",
  "teams": "Teams",
  "contributors": "Contributors",
  "calls": "Contributor calls"
}

export default cty
