/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const email = {
  "chatWithUs": "Chat with us",
  "emailchangeActionText": "Confirm your new E-mail address",
  "emailchangeCopy1": "You requested to change the E-mail address linked to your account at <b>freesewing.org</b>.<br><br>Before we do that, you need to confirm your new E-mail address. Please click the link below to do that:",
  "emailchangeHeaderOpeningLine": "Just making sure we can reach you when needed",
  "emailchangeHiddenIntro": "Let's confirm your new E-mail address",
  "emailchangeSubject": "Please confirm your new E-mail address",
  "emailchangeTitle": "Please confirm your new E-mail address",
  "emailchangeWhy": "You received this E-mail because you changed the E-mail address linked to your account on freesewing.org",
  "footerCredits": "Made by joost & contributors with the financial support of our patrons ❤️ ",
  "footerSlogan": "Freesewing is an open source platform for made-to-measure sewing patterns",
  "goodbyeCopy1": "If you'd like to share why you're leaving, you can reply to this message.<br>From our side, we won't bother you again.",
  "goodbyeHeaderOpeningLine": "Just know that you can always come back",
  "goodbyeHiddenIntro": "Thank you for giving freesewing a chance",
  "goodbyeSubject": "Farewell 👋",
  "goodbyeTitle": "Thank you for giving freesewing a chance",
  "goodbyeWhy": "You received this E-mail as a final adieu after removing your account on freesewing.org",
  "joostFromFreesewing": "Joost from Freesewing",
  "passwordresetActionText": "Re-gain access to your account",
  "passwordresetCopy1": "You forgot your password for your account at <b>freesewing.org</b>.<br><br>Click click the link below to reset your password:",
  "passwordresetHeaderOpeningLine": "Don't worry, these things happen to all of us",
  "passwordresetHiddenIntro": "Re-gain access to your account",
  "passwordresetSubject": "Re-gain access to your account on freesewing.org",
  "passwordresetTitle": "Reset your password, and re-gain access to your account",
  "passwordresetWhy": "You received this E-mail because you requested to reset your password on freesewing.org",
  "questionsJustReply": "If you have any questions, just reply to this E-mail. I'm always happy to help out. 🙂",
  "signature": "Love,",
  "signupActionText": "Confirm your E-mail address",
  "signupCopy1": "Thank you for signing up at <b>freesewing.org</b>.<br><br>Before we get started, you need to confirm your E-mail address. Please click the link below to do that:",
  "signupHeaderOpeningLine": "We're really happy you're joining the freesewing community.",
  "signupHiddenIntro": "Let's confirm your E-mail address",
  "signupSubject": "Welcome to freesewing.org",
  "signupTitle": "Welcome aboard",
  "signupWhy": "You received this E-mail because you just signed up for an account on freesewing.org"
}

export default email
