/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "The page you are looking for cannot be found",
  "confirmationNotFound": "If you arrived at this page via the link in a confirmation Email, we encourage you to report this problem.",
  "emailExists": "We already have a user with that Email address. Perhaps you'd like to log in instead?",
  "networkError": "Backend or network seems down",
  "notAValidImageFormat": "Not a valid image format",
  "requestFailedWithStatusCode400": "Request failed",
  "requestFailedWithStatusCode401": "Authentication failed",
  "requestFailedWithStatusCode403": "Forbidden",
  "requestFailedWithStatusCode500": "There was an unexpected problem. Please report this.",
  "something": "Something went wrong"
}

export default errors
