/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "German",
  "en": "English",
  "es": "Spanish",
  "fr": "French",
  "nl": "Dutch"
}

export default i18n
