/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const intro = {
  "txt-blog": "News, updates, and announcements from the freesewing team",
  "txt-community": "Everything is run by voluntary contributors. There is no commercial entity behind, or attached to, the freesewing project.",
  "txt-different": "How we're different",
  "txt-draft": "Choose from one of your patterns, choose a model, and pick your options. We'll do the rest.",
  "txt-how": "How it works",
  "txt-join": "Join thousands of others and sign up for a free account on freesewing.org.",
  "txt-model": "All our patterns are made-to-measure. So first thing to do is grab your measuring tape.",
  "txt-newHere": "If you're new here, the best place to start is our demo:",
  "txt-opensource": "Our platform, our patterns, and even this website. All our code is available on GitHub. Pull requests welcome!",
  "txt-patrons": "Freesewing is made possible by the financial support of our Patrons. Scroll down to learn about our subscription model.",
  "txt-showcase": "Finished projects from the freesewing community"
}

export default intro
