/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "See <a href='/docs/sewing/basting/'>Basting</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "coverlock.d": "See <a href='/docs/sewing/coverlock/'>Coverlock</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "cutting.d": "See <a href='/docs/sewing/cutting/'>Cutting</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "darts.d": "See <a href='/docs/sewing/darts/'>Darts</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "doubleWeltPockets.d": "See <a href='/docs/sewing/double-welt-pockets/'>Double welt pockets</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "ease.d": "See <a href='/docs/sewing/ease/'>Ease</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "edgestitch.d": "See <a href='/docs/sewing/edgestitching/'>Edgestitching</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "fabricGrain.d": "See <a href='/docs/sewing/fabric-grain/'>Fabric grain</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "goodSidesTogether.d": "See <a href='/docs/sewing/good-sides-together/'>Good sides together</a> in the <a href='/docs/sewing/'>Sewing documentation</a>",
  "onTheFold.d": "See <a href='/docs/sewing/on-the-fold/'>On the fold</a> in the <a href='/docs/sewing/'>Sewing documentation</a>",
  "hemming.d": "See <a href='/docs/sewing/hemming/'>Hemming</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "jersey.d": "See <a href='/docs/sewing/jersey/'>Jersey</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "knitBinding.d": "See <a href='/docs/sewing/knit-binding/'>Knit binding</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "knitFabric.d": "See <a href='/docs/sewing/knit-fabric/'>Knit fabric</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "pinning.d": "See <a href='/docs/sewing/pinning/'>Pinning</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "rayon.d": "See <a href='/docs/sewing/rayon/'>Rayon</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "sa.d": "See <a href='/docs/sewing/seam-allowance/'>Seam allowance</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "serger.d": "See <a href='/docs/sewing/serger/'>Serger</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "slipstitch.d": "See <a href='/docs/sewing/slipstitch/'>Slipstitch</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "topstitching.d": "See <a href='/docs/sewing/topstitching/'>Topstitching</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "trimming.d": "See <a href='/docs/sewing/trimming/'>Trimming</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "twinNeedle.d": "See <a href='/docs/sewing/twin-neelde/'>Twin needle</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "zigZag.d": "See <a href='/docs/sewing/zig-zag-stitch/'>Zig-zag stitch</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "freesewing.d": "<b>FreeSewing</b> is an open source platform for made-to-measure sewing patterns",
  "patternOptions.d": "The <b>pattern options</b> allow you to customize the design of the pattern",
  "draftSettings.d": "The <b>draft settings</b> give you control of how a pattern is generated",
  "patrons.d": "Patrons support Freesewing financially. They are loyal supporters who ensure a sustainable future for freesewing.org, our code, our patterns, and our community.",
  "msf.d": "Médecins Sans Frontières/Doctors Without Borders - See <a href='https://msf.org/'>msf.org</a>"
}

export default jargon
