/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Armhole drop",
  "armholeDrop.d": "Lower the armhole by this amount. Negative values will raise it.",
  "backlineBend.t": "Back armhole shape",
  "backlineBend.d": "Determines the shape/bend of the back of the armholes.",
  "hipsEase.t": "Hips ease",
  "hipsEase.d": "The amount of ease at your hips.",
  "necklineBend.t": "Neckline shape",
  "necklineBend.d": "Determines the shape/bend of the neckline at the front.",
  "necklineDrop.t": "Neckline drop",
  "necklineDrop.d": "The amount the neck is cutout at the front.",
  "shoulderStrapPlacement.t": "Shoulderstrap placement",
  "shoulderStrapPlacement.d": "Determines whether the shoulder strap is placed closer to the neck (lower numbers) or the shoulder (higher numbers).",
  "shoulderStrapWidth.t": "Shoulderstrap width",
  "shoulderStrapWidth.d": "The width of the shoulder straps.",
  "stretchFactor.t": "Stretch",
  "stretchFactor.d": "Determines the horizontal negative ease."
}

export default o_aaron
