/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Back opening",
  "backOpening.d": "Controls the opening at the back of the apron",
  "chestDepth.t": "Strap length",
  "chestDepth.d": "Controls the length of the straps",
  "lengthBonus.t": "Length bonus",
  "lengthBonus.d": "Controls the length of the apron",
  "bibLength.t": "Bib length",
  "bibLength.d": "Controls the length of the bib",
  "bibWidth.t": "Bib width",
  "bibWidth.d": "Controls the width of the bib",
  "strapWidth.t": "Strap width",
  "strapWidth.d": "Controls the width of the strap"
}

export default o_albert
