/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Sleeve bend",
  "sleeveBend.d": "Controls the bend of the sleeve at the elbow.",
  "sleevecapHeight.t": "Sleevecap height",
  "sleevecapHeight.d": "Controls the height of the sleevecap."
}

export default o_bent
