/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Adjustment ribbon",
  "adjustmentRibbon.d": "Whether or not to include an adjustment ribbon",
  "bandLength.t": "Band length",
  "bandLength.d": "Length of the band",
  "tipWidth.t": "Tip width",
  "tipWidth.d": "Width of the tips",
  "knotWidth.t": "Knot width",
  "knotWidth.d": "Width of the knot",
  "bowLength.t": "Bow length",
  "bowLength.d": "Length of the bow (when knotted)",
  "bowStyle.t": "Bow style",
  "bowStyle.d": "Style of the bow",
  "endStyle.t": "End style",
  "endStyle.d": "Style of the bow ends",
  "collarEase.t": "Collar ease",
  "collarEase.d": "The amount of ease at your neck",
  "ribbonWidth.t": "Ribbon width",
  "ribbonWidth.d": "Width of the ribbon"
}

export default o_benjamin
