/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bella = {
  "chestEase.t": "Chest ease",
  "chestEase.d": "Controls the amount of ease at the fullest part of your chest",
  "waistEase.t": "Waist ease",
  "waistEase.d": "Controls the amount of ease at your waist",
  "bustSpanEase.t": "Bust span ease",
  "bustSpanEase.d": "Controls the amount of (horizontal) ease added to your bust span when locating the bust point.",
  "fullChestEaseReduction.t": "Full chest ease reduction",
  "fullChestEaseReduction.d": "Allows you to independently reduce the ease around the chest to make it fit tight(er) in that area",
  "backDartHeight.t": "Back dart height",
  "backDartHeight.d": "Controls the height of the back dart",
  "bustDartLength.t": "Bust dart length",
  "bustDartLength.d": "Controls the length of the bust dart",
  "waistDartLength.t": "Waist dart length",
  "waistDartLength.d": "Controls the length of the waist dart",
  "bustDartCurve.t": "Bust dart curve",
  "bustDartCurve.d": "Controls the curvature of the bust dart",
  "armholeDepth.t": "Armhole depth",
  "armholeDepth.d": "Controls the depth of the armhole",
  "backArmholeSlant.t": "Back armhole slant",
  "backArmholeSlant.d": "Slightly rotates the armhole around its pitch point",
  "frontArmholeCurvature.t": "Front armhole curvature",
  "frontArmholeCurvature.d": "Controls how deep the armhole is scooped out at the front bottom",
  "backArmholeCurvature.t": "Back armhole curvature",
  "backArmholeCurvature.d": "Controls how deep the armhole is scooped out at the back bottom",
  "frontArmholePitchDepth.t": "Front armhole pitch depth",
  "frontArmholePitchDepth.d": "Tweaks the horizontal placement of the front armhole pitch point",
  "backArmholePitchDepth.t": "Back armhole pitch depth",
  "backArmholePitchDepth.d": "Tweaks the horizontal placement of the back armhole pitch point",
  "backNeckCutout.t": "Back neck cutout",
  "backNeckCutout.d": "Controls how deep the neck opening is scooped out at at the back",
  "backHemSlope.t": "Back hem slope",
  "backHemSlope.d": "Controls the slope of the hem at the back",
  "frontShoulderWidth.t": "Front shoulder width",
  "frontShoulderWidth.d": "Controls the narrowness of the front shoulders relative to the back",
  "highBustWidth.t": "High bust width",
  "highBustWidth.d": "Allows you to tweak the hight bust width at the front"
}

export default o_bella
