/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Shoulder dart",
  "shoulderDart.d": "Whether or not to inlude a dart at the shoulder to round the back",
  "shoulderDartSize.t": "Shoulder dart size",
  "shoulderDartSize.d": "The size of the shoulder dart",
  "shoulderDartLength.t": "Shoulder dart length",
  "shoulderDartLength.d": "The length of the shoulder dart",
  "waistDart.t": "Waist dart",
  "waistDart.d": "Whether or not to inlude a dart at the waist to round the back",
  "waistDartSize.t": "Waist dart size",
  "waistDartSize.d": "The size of the waist dart",
  "waistDartLength.t": "Waist dart length",
  "waistDartLength.d": "The length of the waist dart",
  "verticalEase.t": "Vertical ease",
  "verticalEase.d": "The amount of ease to distribute along the length of the garment",
  "waistEase.t": "Waist ease",
  "waistEase.d": "The amount of ease at the waist",
  "primaryBustDart.t": "Bust dart",
  "primaryBustDart.d": "Where to place the bust dart to shape the chest",
  "primaryBustDartLength.t": "Bust dart length",
  "primaryBustDartLength.d": "The length of the bust dart",
  "secondaryBustDart.t": "Secondary bust dart",
  "secondaryBustDart.d": "Optionally include a secondary bust dart to distribute the shaping of the chest",
  "secondaryBustDartLength.t": "Secondary bust dart length",
  "secondaryBustDartLength.d": "The length of the secondary bust dart",
  "primaryBustDartShaping.t": "Bust darts shaping",
  "primaryBustDartShaping.d": "Controls the balance between the main and secondary bust darts"
}

export default o_breanna
