/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Bulge",
  "bulge.d": "Increase angle to create more room in the front pouch.",
  "legBonus.t": "Leg length bonus",
  "legBonus.d": "Extra length to add to the legs.",
  "rise.t": "Rise",
  "rise.d": "Amount to raise the waist. A negative value will lower it.",
  "stretch.t": "Stretch",
  "stretch.d": "The amount of negative ease.",
  "legStretch.t": "Leg stretch",
  "legStretch.d": "For best results, you want to fit your legs a bit more snugly — say no to gaping.",
  "backRise.t": "Back rise",
  "backRise.d": "Percentage by which the waist will be raised at the back."
}

export default o_bruce
