/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cornelius = {
  "fullness.t": "Fullness",
  "fullness.d": "Controls the fullness of the breeches",
  "waistbandBelowWaist.t": "Lower waistband",
  "waistbandBelowWaist.d": "Percentage to move the waistband below the actual waist",
  "waistReduction.t": "Waist reduction",
  "waistReduction.d": "Percentage to reduce the waistband",
  "cuffWidth.t": "Cuff width",
  "cuffWidth.d": "Width of the leg cuff",
  "cuffStyle.t": "Cuff style",
  "cuffStyle.d": "Style of the leg cuff",
  "bandBelowKnee.t": "Cuff below knee",
  "bandBelowKnee.d": "Controls the cuff distance from the knee",
  "kneeToBelow.t": "Cuff length",
  "kneeToBelow.d": "Controls the tightness of the cuff as compared to the knee",
  "ventLength.t": "Vent length",
  "ventLength.d": "Controls the length of the vent between knee and cuff"
}

export default o_cornelius
