/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_diana = {
  "shoulderSeamLength.t": "Shoulder seam length",
  "shoulderSeamLength.d": "Controls the length of the shoulder seam",
  "drapeAngle.t": "Drape angle",
  "drapeAngle.d": "Controls the amount of drape"
}

export default o_diana
