/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florence = {
  "height.t": "Height",
  "height.d": "Controls the height of the face mask",
  "length.t": "Length",
  "length.d": "Controls the length of the face mask",
  "curve.t": "Curve",
  "curve.d": "Controls the curvature of the upper edge of the face mask"
}

export default o_florence
