/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florent = {
  "headEase.t": "Head ease",
  "headEase.d": "The amound of ease around your head"
}

export default o_florent
