/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hi = {
  "hungry.t": "Hungry",
  "hungry.d": "Changes the mouth shape to convey Hi is hungry",
  "nosePointiness.t": "Nose pointiness",
  "nosePointiness.d": "Controls how pointy Hi's nose is",
  "aggressive.t": "Aggressive",
  "aggressive.d": "Give Hi pointy teeth, or not",
  "size.t": "Size",
  "size.d": "Sharks come in all sizes, and so does Hi"
}

export default o_hi
