/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hortensia = {
  "size.t": "Size",
  "size.d": "Controls the overall size of the handbag",
  "zipperSize.t": "Zipper size",
  "zipperSize.d": "Which size of zipper to use",
  "strapLength.t": "Strap length",
  "strapLength.d": "Controls the length of the strap",
  "handleWidth.t": "Handle width",
  "handleWidth.d": "Controls the width of the handle"
}

export default o_hortensia
