/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hugo = {
  "hipsEase.t": "Hips ease",
  "hipsEase.d": "The amount of ease at your hips."
}

export default o_hugo
