/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_huey = {
  "pocket.t": "Pocket",
  "pocket.d": "Whether to include a front pocket or not",
  "pocketHeight.t": "Pocket height",
  "pocketHeight.d": "Controls the height of the pocket",
  "hoodHeight.t": "Hood height",
  "hoodHeight.d": "Controls the height of the hood",
  "hoodCutback.t": "Hood cutback",
  "hoodCutback.d": "Controls how far the hood opening is cut back",
  "hoodClosure.t": "Hood closure",
  "hoodClosure.d": "Controls how much of the hood is part of the front closure",
  "hoodDepth.t": "Hood depth",
  "hoodDepth.d": "Controls the depth of the hood",
  "hoodAngle.t": "Hood angle",
  "hoodAngle.d": "Controls the angle at which the hood is attached"
}

export default o_huey
