/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_lunetius = {
  "lengthRatio.t": "Length ratio",
  "lengthRatio.d": "Controls the length of the garment",
  "widthRatio.t": "Width ratio",
  "widthRatio.d": "Controls the width of the garment",
  "length.t": "Length",
  "length.d": "Choose from the different length styles"
}

export default o_lunetius
