/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_paco = {
  "heelEase.t": "Heel ease",
  "heelEase.d": "The amount of ease at your heel (when stepping into the leg)",
  "frontPockets.t": "Front pockets",
  "frontPockets.d": "Whether or not to add front pockets on the side seam",
  "backPockets.t": "Back pockets",
  "backPockets.d": "Whether or not to add welt pockets to the back",
  "elasticatedHem.t": "Elasticated hem",
  "elasticatedHem.d": "Whether or not you want an elasticated hem",
  "ankleElastic.t": "Ankle/Hem elastic width",
  "ankleElastic.d": "Width of the (optional) elastic at the ankle/hem"
}

export default o_paco
