/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_penelope = {
  "backDartDepthFactor.t": "Back dart depth factor",
  "backDartDepthFactor.d": "How far down does the back dart go from the waistband. This is a factor of the Natural Waist To Seat measurement.",
  "backVent.t": "Back vent",
  "backVent.d": "Add a vent in the back of the skirt.",
  "backVentLength.t": "Back vent length",
  "backVentLength.d": "Length of the Back Vent as a percentage of the skirt length.",
  "dartToSideSeamFactor.t": "Dart to side seam factor",
  "dartToSideSeamFactor.d": "Percentage of how much of the hip to waist reduction has to be taken in by the darts versus the side seam.",
  "frontDartDepthFactor.t": "Front dart depth factor",
  "frontDartDepthFactor.d": "How far down does the front dart go from the waistband. This is a factor of the Natural Waist To Seat measurement.",
  "hem.t": "Size of the hem",
  "hem.d": "The size of the hem. Measurement in absolute values.",
  "hemBonus.t": "Hem bonus",
  "hemBonus.d": "This option will reduce the circumference of the skirt at the hem. Percentage of the Seat measurement.",
  "lengthBonus.t": "Length bonus",
  "lengthBonus.d": "This sets the length of the skirt. Percentage of the Natural Waist to Knee measurement.",
  "nrOfDarts.t": "Number of darts",
  "nrOfDarts.d": "The number of darts used in the pattern. Maximum is 2. This option can be reduced by the pattern if the calculations create darts that are too small.",
  "seatEase.t": "Seat ease",
  "seatEase.d": "Amount of ease at the seat level.",
  "waistBand.t": "Waist band",
  "waistBand.d": "Add a waistband to the pattern.",
  "waistBandWidth.t": "Waist band width",
  "waistBandWidth.d": "The width of the waist band.",
  "waistEase.t": "Waist ease",
  "waistEase.d": "Amount of ease at the waist level.",
  "zipperLocation.t": "Zipper location",
  "zipperLocation.d": "The location of the zipper."
}

export default o_penelope
