/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_shin = {
  "legReduction.t": "Leg reduction",
  "legReduction.d": "Reduces the leg opening to prevent gaping",
  "elasticWidth.t": "Elastic width",
  "elasticWidth.d": "Width of the elastic at the waist"
}

export default o_shin
