/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_simone = {
  "bustDartAngle.t": "Bust dart angle",
  "bustDartAngle.d": "Controls the angle by which the (side) bust dart slopes downward",
  "bustDartLength.t": "Bust dart length",
  "bustDartLength.d": "Controls how close the bust dart approaches the bust point",
  "contour.t": "Contour",
  "contour.d": "Controls how sharply the extra room for breasts is removed again below the chest",
  "frontDarts.t": "Front darts",
  "frontDarts.d": "Whether to include front darts or not",
  "frontDartLength.t": "Front dart length",
  "frontDartLength.d": "Controls how close the front dart approaches the bust point"
}

export default o_simone
