/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sven = {
  "hipsEase.t": "Hips ease",
  "hipsEase.d": "Controls the amount of ease at your hips (the bottom of the sweater)",
  "ribbing.t": "Ribbing",
  "ribbing.d": "Whether to finish the hem and cuffs with ribbing or not.",
  "ribbingHeight.t": "Ribbing height",
  "ribbingHeight.d": "The height of the ribbing on cuffs and hem.",
  "ribbingStretch.t": "Ribbing stretch",
  "ribbingStretch.d": "The amount of negative ease to apply to the ribbing used for cuffs and hem."
}

export default o_sven
