/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Draft for high bust",
  "draftForHighBust.d": "Draft the pattern for the high bust measurement (if available) rather than the (full) chest. This will result in a more fitted garment for people with breasts.",
  "sleeveEase.t": "Sleeve ease",
  "sleeveEase.d": "Amount of ease of your sleeves",
  "sleeveLength.t": "Sleeve length",
  "sleeveLength.d": "Controls the length of your sleeves",
  "necklineBend.t": "Neckline curvature",
  "necklineBend.d": "Controls the curvature of the neckline.",
  "necklineDepth.t": "Neckline depth",
  "necklineDepth.d": "Controls how deep the neck opening plunges down.",
  "necklineWidth.t": "Neckline width",
  "necklineWidth.d": "Controls the width of the neck opening."
}

export default o_teagan
