/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_ursula = {
  "fabricStretch.t": "Fabric stretch",
  "fabricStretch.d": "Adjust this for more or less stretchy fabrics",
  "gussetWidth.t": "Gusset width",
  "gussetWidth.d": "Controls the width of the gusset",
  "gussetLength.t": "Gusset length",
  "gussetLength.d": "Controls the length of the gusset",
  "elasticStretch.t": "Elastic stretch",
  "elasticStretch.d": "Adjust this for more or less stretchy elastic",
  "rise.t": "Rise",
  "rise.d": "Controls the height of the waist",
  "legOpening.t": "Leg opening",
  "legOpening.d": "Controls how high the leg is cut out",
  "frontDip.t": "Front waist dip",
  "frontDip.d": "Controls how much the front waist curves (revealing more or less skin)",
  "backDip.t": "Back waist dip",
  "backDip.d": "Controls how much the back waist curves (revealing more or less skin)",
  "taperToGusset.t": "Front exposure",
  "taperToGusset.d": "Controls the amount of exposed skin on the front",
  "backExposure.t": "Back exposure",
  "backExposure.d": "Controls the amount of exposed skin on the back"
}

export default o_ursula
