/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_waralee = {
  "backPocket.t": "Back pocket",
  "backPocket.d": "Whether to include a back pocket or not",
  "frontPocket.t": "Front pocket",
  "frontPocket.d": "Whether to include a front pocket or not",
  "hem.t": "Hem size",
  "hem.d": "Size of the hem at the bottom of the pants",
  "waistBand.t": "Waist Band",
  "waistBand.d": "Size of the waist band",
  "waistRaise.t": "Waist Raise",
  "waistRaise.d": "How much to raise the waist from the seat depth measurement. This influences the depth of the crotch cut-out.",
  "crotchBack.t": "Crotch Back",
  "crotchBack.d": "The percentage of the seat circumference that the back crotch needs to occupy. This creates more or less space between the side seam and the back.",
  "crotchFront.t": "Crotch Front",
  "crotchFront.d": "The percentage of the seat circumference that the front crotch needs to occupy. This creates more or less space between the side seam and the front.",
  "crotchFactorBackHor.t": "Back Crotch Factor Horizontal",
  "crotchFactorBackHor.d": "Used to move the curve of the crotch in the back horizontally",
  "crotchFactorBackVer.t": "Back Crotch Factor Vertical",
  "crotchFactorBackVer.d": "Used to move the curve of the crotch in the back vertically",
  "crotchFactorFrontHor.t": "Front Crotch Factor Horizontal",
  "crotchFactorFrontHor.d": "Used to move the curve of the crotch in the front horizontally",
  "crotchFactorFrontVer.t": "Front Crotch Factor Vertical",
  "crotchFactorFrontVer.d": "Used to move the curve of the crotch in the front vertically",
  "waistOverlap.t": "Waist Overlap",
  "waistOverlap.d": "This dicates how much you want the leg flaps to overlap at the waist. A setting of 0 would have them meet at the side seam, and a setting of 100 makes them meet at the front/back.",
  "legShortening.t": "Leg Shortening",
  "legShortening.d": "This dictates how long the pants will be. It is a factor of the inseam measurement. The larger the value, the more that will be taken off the length.",
  "backRaise.t": "Back Raise",
  "backRaise.d": "This setting raises the waist in the back. Our waist does not sit horizontally, but is angled up at the back. This seting allows you to raise this in the back if you need it for a good fit."
}

export default o_waralee
