/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_wahid = {
  "backScyeDart.t": "Back scye dart",
  "backScyeDart.d": "The amount to take out in a dart at the back of the armhole.",
  "frontScyeDart.t": "Front scye dart",
  "frontScyeDart.d": "The amount to take out in a dart at the front of the armhole.",
  "pocketLocation.t": "Pocket location",
  "pocketLocation.d": "Determines the placement of the pocket",
  "pocketWidth.t": "Pocket width",
  "pocketWidth.d": "Determines the width of the pocket",
  "weltHeight.t": "Welt height",
  "weltHeight.d": "Determines the height of the welt",
  "necklineDrop.t": "Neckline drop",
  "necklineDrop.d": "Determines how low the neckline drops at the front",
  "frontStyle.t": "Neck opening style",
  "frontStyle.d": "Style of the neck opening",
  "hemStyle.t": "Hem style",
  "hemStyle.d": "Style of the front hem",
  "hemRadius.t": "Hem radius",
  "hemRadius.d": "Radius by which the hem is rounded",
  "backInset.t": "Back inset",
  "backInset.d": "How much the back of the armhole is cut inwards",
  "frontInset.t": "Front inset",
  "frontInset.d": "How much the front of the armhole is cut inwards",
  "shoulderInset.t": "Shoulder inset",
  "shoulderInset.d": "How much the shoulder seam is cut inwards at the shoulder",
  "neckInset.t": "Neck inset",
  "neckInset.d": "How much the shoulder seam is cut inwards at the neck",
  "pocketAngle.t": "Pocket angle",
  "pocketAngle.d": "Angle of the pocket slant"
}

export default o_wahid
