/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const og = {
  "orgTitle": "Welcome to FreeSewing.org",
  "devTitle": "Welcome to FreeSewing.dev",
  "labTitle": "Welcome to lab.FreeSewing.lab",
  "orgDescription": "Documentation and tutorials for FreeSewing developers and contributors. Plus our Developers Blog",
  "devDescription": "Documentation and tutorials for FreeSewing developers and contributors. Plus our Developers Blog"
}

export default og
