/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const optiongroups = {
  "advanced": "Advanced",
  "armhole": "Armhole",
  "closure": "Closure",
  "collar": "Collar",
  "construction": "Construction",
  "cuffs": "Cuffs",
  "darts": "Darts",
  "elastic": "Elastic",
  "fit": "Fit",
  "pockets": "Pockets",
  "preferences": "Preferences",
  "sleevecap": "Sleevecap",
  "sleeves": "Sleeves",
  "style": "Style",
  "backPockets": "Back pockets",
  "frontPockets": "Front pockets",
  "waistband": "Waistband",
  "fly": "Fly",
  "bellaDarts": "Bella darts",
  "bellaArmhole": "Bella armhole",
  "bellaAdvanced": "Bella advanced",
  "clavi": "Clavi"
}

export default optiongroups
