/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const settings = {
  "advanced.t": "Expert mode",
  "advanced.d": "Controls whether or not to display advanced settings and pattern options",
  "paperless.t": "Paperless",
  "paperless.d": "Drafts a pattern with all dimensions included so you can transfer it on fabric or another medium without the need to print",
  "sa.t": "Seam allowance",
  "sa.d": "Controls the amount of seam allowance included in your pattern",
  "locale.t": "Language",
  "locale.d": "Determines the language used on your pattern",
  "only.t": "Contents",
  "only.d": "Allows you to control which pattern parts will be included in your pattern",
  "units.t": "Units",
  "units.d": "Controls the units used on your pattern",
  "margin.t": "Margin",
  "margin.d": "Controls the margin around pattern parts",
  "complete.t": "Detail",
  "complete.d": "Controls how detailed the pattern is; Either a complete pattern with all details, or a basic outline of the pattern parts",
  "layout.t": "Layout",
  "layout.d": "Controls how the individual pattern parts are placed on your pattern",
  "debug.t": "Debug",
  "debug.d": "Enable debug to gain additional info about how your pattern was created",
  "scale.t": "Scale",
  "scale.d": "Controls the overall line width, font size, and other elements that do not scale with the pattern's measurements",
  "renderer.t": "Render engine",
  "renderer.d": "Controls how the pattern is rendered (drawn) on the screen",
  "xray.t": "X-ray",
  "xray.d": "Look under the hood with FreeSewing's X-ray mode"
}

export default settings
