/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Select the units you want to use",
  "username": "Pick a username",
  "avatar": "Add a profile picture",
  "bio": "Tell us a little bit about yourself",
  "social": "Let us know where we can follow you",
  "newsletter": "Give us your newsletter preference",
  "letUsSetupYourAccount": "Let us set up your account.",
  "walkYouThrough": "We'll walk you through the following steps:",
  "someOptional": "While all these steps are optional, we recommend you go through them to get the most out of FreeSewing."
}

export default welcome
