env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides:
  - files: ["*.yaml", "*.yml"]
    plugins: ["yaml"]
    extends: ["plugin:yaml/recommended"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
globals:
  it: readonly
  describe: readonly
  process: readonly
  __dirname: readonly

