---
- hosts: '!localhost'
  gather_facts: false
  become: true
  tasks:
    - name: Copy backup script to host
      copy:
        src: fs_backup_mongo.sh
        dest: /usr/sbin
        owner: root
        group: root
        mode: '0755'

    - name: Backup mongo database
      shell:
        cmd: "/usr/sbin/fs_backup_mongo.sh {{ db }}"
      args:
        executable: /bin/bash


