---
# Hardcoding this to prevent accidentally migrating the production database
- hosts: next.backend.freesewing.org
  gather_facts: false
  become: true
  tasks:
    - name: Create temporary directory
      file:
        path: "{{tmp}}"
        state: directory
        mode: '0755'
    - name: Copy migration file to remote host
      copy:
        src: migrate_data.js
        dest: "{{tmp}}"
        owner: root
        group: root
        mode: '0755'
    - name: Migrate 2.6 data to 2.7
      shell: "mongo next_freesewing {{tmp}}/migrate_data.js"


