/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cfp = {
  "author": "Auteur",
  "githubRepo": "Répertoire GitHub",
  "packageManager": "Gestionnaire de package",
  "patternName": "Nom de patron",
  "patternType": "Type de patron",
  "patternCreated": "Le squelette de votre patron a été créé sur",
  "runTheseCommands": "Pour commencer, exécutez cette commande",
  "startRollup": "Dans un terminal, démarrez le bundler rollup en mode watch",
  "startWebpack": "Il entrera dans le dossier 'exemple' et démarrera l'environnement de développement.",
  "devDocsAvailableAt": "La documentation pour développeur est disponible sur",
  "talkToUs": "Pour des questions, commentaires ou suggestions, rejoignez notre serveur Discord",
  "draftYourPattern": "Dessiner votre patron",
  "testYourPattern": "Tester votre patron",
  "draftThing": "Ébauche de {thing}",
  "testThing": "Tester {thing}",
  "renderInBrowser": "Cliquer ci-dessous pour afficher votre patron dans votre navigateur.",
  "weWillReRender": "Lorsque vous effectuez des modifications, nous mettons à jour le rendu pour vous.",
  "youCan": "Vous pouvez",
  "enterMeasurements": "Entrer des mesures manuellement",
  "preloadMeasurements": "Pré-charger un set de mesures",
  "size": "Taille",
  "noRequiredMeasurements": "Ce patron n'a pas de mesure requise",
  "howtoAddMeasurements": "Pour rendre des mesures nécessaires, ajoutez-les à la section <b>measurements</b> du fichier de configuration du patron.",
  "seeDocsAt": "La documentation à ce sujet est disponible sur",
  "clearDesignMode": "Vider le mode design",
  "designMode": "Mode design",
  "exportMode": "Mode d'export",
  "thingIsEnabled": "{thing} est activé",
  "thingIsDisabled": "{thing} est désactivé",
  "turnOn": "Activer",
  "turnOff": "Désactiver",
  "validNameWarning": "Veuillez choisir un nom différent car ce nom causerait des problèmes.\nNous (ré-)utilisons le nom du modèle comme nom de paquet NPM.\nLes noms de paquets doivent être en minuscule et ne peuvent pas contenir de caractères spéciaux.\nVeuillez donc nommer votre patron en conséquence, comme :"
}

export default cfp
