/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Mon Compte",
  "blog": "Blog",
  "community": "Communauté",
  "designs": "Designs",
  "docs": "Documentation",
  "patternInstructions": "Documentation du patron",
  "patternOptions": "Options du patron",
  "requiredMeasurements": "Mensurations requises",
  "showcase": "Galerie",
  "sloganCome": "Venez pour les patrons de couture",
  "sloganStay": "Restez pour la communauté"
}

export default common
