/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cty = {
  "wafsHashtag": "WeAreFreeSewing",
  "weAreACommunityOfMakers": "Nous sommes une communauté de créateurs",
  "weProvideMtmSewingPatterns": "Nous fournissons des patrons de couture sur mesure",
  "isAPatron": "est un.e mécène",
  "contributesWith": "contribue en",
  "communityBuilding": "Développement communautaire",
  "development": "Développement",
  "patternTesting": "Tests de patron",
  "patternDesign": "Design de patron",
  "support": "Soutien",
  "translation": "Traduction",
  "writing": "Rédaction",
  "whereToFindUs": "Où nous trouver",
  "whoWeAre": "Qui nous sommes",
  "community": "Communauté",
  "team": "Équipe",
  "teams": "Équipes",
  "contributors": "Contributeurs",
  "calls": "Appels des contributeurs"
}

export default cty
