/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const docs = {
  "thingIsDeprecated": "{thing} est obsolète",
  "weRecommendThingInstead": "Nous recommandons {thing} à la place"
}

export default docs
