/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "La page que vous recherchez est introuvable.",
  "confirmationNotFound": "Si vous êtes arrivé sur cette page via le lien figurant dans un e-mail de confirmation, nous vous encourageons à signaler ce problème.",
  "emailExists": "Nous avons déjà un utilisateur avec cette adresse mail. Peut-être aimeriez-vous plutôt vous connecter ?",
  "networkError": "Le backend ou le réseau semblent en panne",
  "notAValidImageFormat": "Format d'image non valide",
  "requestFailedWithStatusCode400": "Échec de la demande",
  "requestFailedWithStatusCode401": "Échec de l'authentification",
  "requestFailedWithStatusCode403": "Interdit",
  "requestFailedWithStatusCode500": "Il y a eu un problème inattendu. Veuillez le signaler.",
  "something": "Une erreur s'est produite"
}

export default errors
