/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "Allemand",
  "en": "Anglais",
  "es": "Espagnol",
  "fr": "Français",
  "nl": "Néerlandais"
}

export default i18n
