/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
import account from "./account.mjs"
import app from "./app.mjs"
import cfp from "./cfp.mjs"
import common from "./common.mjs"
import workbench from "./workbench.mjs"
import cty from "./cty.mjs"
import email from "./email.mjs"
import errors from "./errors.mjs"
import filter from "./filter.mjs"
import gdpr from "./gdpr.mjs"
import i18n from "./i18n.mjs"
import intro from "./intro.mjs"
import jargon from "./jargon.mjs"
import measurements from "./measurements.mjs"
import optiongroups from "./optiongroups.mjs"
import o_aaron from "./o_aaron.mjs"
import o_albert from "./o_albert.mjs"
import o_bee from "./o_bee.mjs"
import o_bella from "./o_bella.mjs"
import o_benjamin from "./o_benjamin.mjs"
import o_bent from "./o_bent.mjs"
import o_breanna from "./o_breanna.mjs"
import o_brian from "./o_brian.mjs"
import o_bruce from "./o_bruce.mjs"
import o_carlita from "./o_carlita.mjs"
import o_carlton from "./o_carlton.mjs"
import o_cathrin from "./o_cathrin.mjs"
import o_charlie from "./o_charlie.mjs"
import o_cornelius from "./o_cornelius.mjs"
import o_diana from "./o_diana.mjs"
import o_florence from "./o_florence.mjs"
import o_florent from "./o_florent.mjs"
import o_holmes from "./o_holmes.mjs"
import o_hortensia from "./o_hortensia.mjs"
import o_huey from "./o_huey.mjs"
import o_hugo from "./o_hugo.mjs"
import o_jaeger from "./o_jaeger.mjs"
import o_lunetius from "./o_lunetius.mjs"
import o_paco from "./o_paco.mjs"
import o_penelope from "./o_penelope.mjs"
import o_sandy from "./o_sandy.mjs"
import o_shin from "./o_shin.mjs"
import o_simon from "./o_simon.mjs"
import o_simone from "./o_simone.mjs"
import o_sven from "./o_sven.mjs"
import o_tamiko from "./o_tamiko.mjs"
import o_teagan from "./o_teagan.mjs"
import o_theo from "./o_theo.mjs"
import o_tiberius from "./o_tiberius.mjs"
import o_titan from "./o_titan.mjs"
import o_trayvon from "./o_trayvon.mjs"
import o_ursula from "./o_ursula.mjs"
import o_wahid from "./o_wahid.mjs"
import o_walburga from "./o_walburga.mjs"
import o_waralee from "./o_waralee.mjs"
import parts from "./parts.mjs"
import patterns from "./patterns.mjs"
import plugin from "./plugin.mjs"
import settings from "./settings.mjs"
import welcome from "./welcome.mjs"

const allNamespaces = {
  account,
  app,
  cfp,
  common,
  workbench,
  cty,
  email,
  errors,
  filter,
  gdpr,
  i18n,
  intro,
  jargon,
  measurements,
  optiongroups,
  o_aaron,
  o_albert,
  o_bee,
  o_bella,
  o_benjamin,
  o_bent,
  o_breanna,
  o_brian,
  o_bruce,
  o_carlita,
  o_carlton,
  o_cathrin,
  o_charlie,
  o_cornelius,
  o_diana,
  o_florence,
  o_florent,
  o_holmes,
  o_hortensia,
  o_huey,
  o_hugo,
  o_jaeger,
  o_lunetius,
  o_paco,
  o_penelope,
  o_sandy,
  o_shin,
  o_simon,
  o_simone,
  o_sven,
  o_tamiko,
  o_teagan,
  o_theo,
  o_tiberius,
  o_titan,
  o_trayvon,
  o_ursula,
  o_wahid,
  o_walburga,
  o_waralee,
  parts,
  patterns,
  plugin,
  settings,
  welcome
}

export default allNamespaces
