/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const intro = {
  "txt-blog": "Nouvelles, mises à jour et annonces de l'équipe freesewing",
  "txt-community": "Tout est géré par des contributeurs bénévoles. Il n'y a pas d'entité commerciale, ou assimilée, derrière ce projet.",
  "txt-different": "Ce en quoi nous sommes différents",
  "txt-draft": "Choisissez parmi l'un de vos patrons, choisissez un modèle, et sélectionnez vos options. Nous ferons le reste.",
  "txt-how": "Comment ça marche",
  "txt-join": "Rejoignez des milliers d'autres personnes en vous inscrivant gratuitement sur freesewing.org.",
  "txt-model": "Tous nos patrons sont faits sur mesure, donc la première chose à faire est de vous munir de votre mètre-ruban.",
  "txt-newHere": "Si vous êtes nouveau ici, le meilleur endroit pour commencer est notre démo :",
  "txt-opensource": "Notre plateforme, nos patrons, et même ce site web. Tout notre code est disponible sur GitHub. Les \"Pull requests\" sont les bienvenues !",
  "txt-patrons": "Freesewing existe grâce au soutien financier de nos Mécènes. Faites défiler vers le bas pour en savoir plus sur nos modes de souscription.",
  "txt-showcase": "Projets terminés de la communauté freesewing"
}

export default intro
