/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "Voir <a href='/docs/sewing/basting/'>Bâtir</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "coverlock.d": "Voir <a href='/docs/sewing/coverlock/'>Recouvreuse</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "cutting.d": "Voir <a href='/docs/sewing/cutting/'>Coupe</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "darts.d": "Voir <a href='/docs/sewing/darts/'>Pinces</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "doubleWeltPockets.d": "Voir <a href='/docs/sewing/double-welt-pockets/'>Poches passepoilées</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "ease.d": "Voir <a href='/docs/sewing/ease/'>Aisance</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "edgestitch.d": "Voir <a href='/docs/sewing/edgestitching/'>Couture nervure</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "fabricGrain.d": "Voir <a href='/docs/sewing/fabric-grain/'>Droit fil</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "goodSidesTogether.d": "Voir <a href='/docs/sewing/good-sides-together/'>Endroit contre endroit</a> dans la <a href='/docs/sewing/'>documentation de Couture</a>",
  "onTheFold.d": "Voir <a href='/docs/sewing/on-the-fold/'>Au pli</a> dans la <a href='/docs/sewing/'>documentation de couture</a>",
  "hemming.d": "Voir <a href='/docs/sewing/hemming/'>Ourlet</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "jersey.d": "Voir <a href='/docs/sewing/jersey/'>Jersey</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "knitBinding.d": "Voir <a href='/docs/sewing/knit-binding/'>Biais de jersey</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "knitFabric.d": "Voir <a href='/docs/sewing/knit-fabric/'>Tissu maille</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "pinning.d": "Voir <a href='/docs/sewing/pinning/'>Épingler</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "rayon.d": "Voir <a href='/docs/sewing/rayon/'>Rayonne ou Viscose</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "sa.d": "Voir <a href='/docs/sewing/seam-allowance/'>Marge de couture</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "serger.d": "Voir <a href='/docs/sewing/serger/'>Surgeteuse</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "slipstitch.d": "Voir <a href='/docs/sewing/slipstitch/'>Point glissé</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "topstitching.d": "Voir <a href='/docs/sewing/topstitching/'>Surpiqûre</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "trimming.d": "Voir <a href='/docs/sewing/trimming/'>Dégarnir</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "twinNeedle.d": "Voir <a href='/docs/sewing/twin-neelde/'>Aiguilles doubles</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "zigZag.d": "Voir <a href='/docs/sewing/zig-zag-stitch/'>Point zig-zag</a> dans la <a href='/docs/sewing'>documentation de Couture</a>",
  "freesewing.d": "<b>FreeSewing</b> est une plate-forme open source pour des patrons de couture sur-mesure",
  "patternOptions.d": "Les <b>options de patron</b> vous permettent de personnaliser le design du patron",
  "draftSettings.d": "Les <b>paramètres de patrons générés</b> vous donnent le contrôle de la manière dont un patron est généré",
  "patrons.d": "Les mécènes soutiennent financièrement Freesewing. Ce sont des partisans fidèles qui assurent un avenir durable à freesewing.org, à notre code, à nos patrons et à notre communauté.",
  "msf.d": "Médecins Sans Frontières/Doctors Sans Frontières - Voir <a href='https://msf.org/'>msf.org</a>"
}

export default jargon
