/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const lab = {
  "slogan": "The FreeSewing lab provides",
  "slogan1": "All our pattern designs",
  "slogan2": "New & old version",
  "slogan3": "Bleeding edge code",
  "slogan4": "Unreleased designs"
}

export default lab
