/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const measurements = {
  "ankle": "Tour de cheville",
  "biceps": "Tour de bras",
  "bustFront": "Largeur de poitrine avant",
  "bustPointToUnderbust": "Point de buste vers le buste inférieur",
  "bustSpan": "Écart de poitrine",
  "chest": "Tour de poitrine",
  "crossSeam": "Profondeur de fourche",
  "crossSeamFront": "Enfourchure devant",
  "head": "Tour de tête",
  "heel": "Tour de talon",
  "highBustFront": "Largeur de buste supérieur",
  "highBust": "Tour de buste supérieur",
  "hips": "Tour des petites hanches",
  "hpsToBust": "Hauteur de poitrine",
  "hpsToWaistBack": "Longueur épaule-taille dos",
  "hpsToWaistFront": "Longueur épaule-taille devant",
  "inseam": "Longueur d'entrejambe",
  "knee": "Tour de genou",
  "neck": "Tour de cou",
  "seat": "Tour de bassin",
  "seatBack": "Bassin arrière",
  "crotchDepth": "Hauteur de fourche",
  "shoulderSlope": "Pente des épaules",
  "shoulderToElbow": "Longueur épaule au coude",
  "shoulderToShoulder": "Largeur d'épaules",
  "shoulderToWrist": "Longueur de bras",
  "underbust": "Tour sous poitrine",
  "upperLeg": "Tour de cuisse",
  "waist": "Tour de taille",
  "waistBack": "Taille arrière",
  "waistToFloor": "Hauteur de taille",
  "waistToHips": "Hauteur taille hanches",
  "waistToKnee": "Hauteur taille genou",
  "waistToSeat": "Hauteur taille bassin",
  "waistToUnderbust": "Hauteur taille sous-poitrine",
  "waistToUpperLeg": "Hauteur taille cuisse",
  "wrist": "Tour de poignet"
}

export default measurements
