/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Abaissement d'emmanchure",
  "armholeDrop.d": "Il s'agit d'abaisser l'emmanchure avec cette valeur. Les valeurs négatives la remonteront.",
  "backlineBend.t": "Forme de l'arrière des emmanchures",
  "backlineBend.d": "Détermine la forme/courbure de l'arrière des emmanchures.",
  "hipsEase.t": "Aisance des hanches",
  "hipsEase.d": "La marge d'aisance aux hanches.",
  "necklineBend.t": "Forme de l'encolure",
  "necklineBend.d": "Détermine la forme/courbure du devant de l'encolure.",
  "necklineDrop.t": "Profondeur d'encolure",
  "necklineDrop.d": "Détermine de combien abaisser l’encolure l'avant.",
  "shoulderStrapPlacement.t": "Position de la bretelle",
  "shoulderStrapPlacement.d": "Détermine si la bretelle est placée plus près du cou (chiffres les plus bas) ou de l’épaule (chiffres les plus élevés).",
  "shoulderStrapWidth.t": "Largeur de la bretelle",
  "shoulderStrapWidth.d": "Détermine la largeur des bretelles.",
  "stretchFactor.t": "Élasticité",
  "stretchFactor.d": "Détermine a quantité d'aisance négative en largeur."
}

export default o_aaron
