/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Ouverture arrière",
  "backOpening.d": "Contrôle l'ouverture à l'arrière du tablier",
  "chestDepth.t": "Longueur de l'anse",
  "chestDepth.d": "Contrôle la longueur des liens",
  "lengthBonus.t": "Supplément de longueur",
  "lengthBonus.d": "Contrôle la longueur du tablier",
  "bibLength.t": "Longueur du plastron",
  "bibLength.d": "Contrôle la longueur du plastron",
  "bibWidth.t": "Largeur du plastron",
  "bibWidth.d": "Contrôle la largeur du plastron",
  "strapWidth.t": "Largeur du lien",
  "strapWidth.d": "Contrôle la largeur des liens"
}

export default o_albert
