/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Ruban d'ajustement",
  "adjustmentRibbon.d": "Si vous souhaitez inclure ou non un ruban d'ajustement",
  "bandLength.t": "Longueur de bande",
  "bandLength.d": "Longueur de la bande",
  "tipWidth.t": "Largeur de pointe",
  "tipWidth.d": "Largeur des pointes",
  "knotWidth.t": "Largeur du noeud",
  "knotWidth.d": "Largeur du nœud",
  "bowLength.t": "Longueur de nœud",
  "bowLength.d": "Longueur du nœud (lorsqu'il est noué)",
  "bowStyle.t": "Style de nœud",
  "bowStyle.d": "Style du nœud",
  "endStyle.t": "Style de l'extrémité",
  "endStyle.d": "Style des extrémités du noeud",
  "collarEase.t": "Aisance du col",
  "collarEase.d": "La quantité d'aisance à votre cou",
  "ribbonWidth.t": "Largeur du ruban d'ajustement",
  "ribbonWidth.d": "Largeur du ruban"
}

export default o_benjamin
