/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bella = {
  "chestEase.t": "Aisance de poitrine",
  "chestEase.d": "Contrôle la quantité d'aisance au niveau le plus large de votre buste",
  "waistEase.t": "Aisance à la taille",
  "waistEase.d": "Contrôle la quantité d'aisance au niveau de la taille",
  "bustSpanEase.t": "Aisance de l'écart poitrine",
  "bustSpanEase.d": "Contrôle la quantité d'aisance (horizontale) ajoutée à votre poitrine entre les 2 pointes de la poitrine.",
  "fullChestEaseReduction.t": "Réduction de l'aisance de la poitrine",
  "fullChestEaseReduction.d": "Vous permet de réduire l'aisance de la poitrine indépendamment pour rendre plus seyant cette zone",
  "backDartHeight.t": "Hauteur de pince dos",
  "backDartHeight.d": "Contrôle la hauteur de pince dans le dos",
  "bustDartLength.t": "Longueur des pinces poitrine",
  "bustDartLength.d": "Contrôle la longueur de la pince dos",
  "waistDartLength.t": "Longueur de la pince de taille",
  "waistDartLength.d": "Contrôle la longueur de la pince de taille",
  "bustDartCurve.t": "Courbe de la pince poitrine",
  "bustDartCurve.d": "Contrôle la courbure de la pince poitrine",
  "armholeDepth.t": "Profondeur d'emmanchure",
  "armholeDepth.d": "Contrôle la profondeur de l'emmanchure",
  "backArmholeSlant.t": "Inclinaison d'emmanchure dos",
  "backArmholeSlant.d": "Modifie légèrement l'inclinaison de courbe de l'emmanchure autour de son point de pivot",
  "frontArmholeCurvature.t": "Coube de l'emmanchure avant",
  "frontArmholeCurvature.d": "Contrôle la profondeur du bas de la courbure d'emmanchure sur le devant",
  "backArmholeCurvature.t": "Courbure de l'emmanchure arrière",
  "backArmholeCurvature.d": "Contrôle la profondeur du bas de la courbure d'emmanchure dans le dos",
  "frontArmholePitchDepth.t": "Profondeur du point de pivot de l'emmanchure avant",
  "frontArmholePitchDepth.d": "Modifie la position horizontale du point de pivot de l'emmanchure avant",
  "backArmholePitchDepth.t": "Profondeur du point de pivot de l'emmanchure dos",
  "backArmholePitchDepth.d": "Modifie la position horizontale du point de pivot de l'emmanchure dos",
  "backNeckCutout.t": "Arrondi de l'encolure au dos",
  "backNeckCutout.d": "Contrôle la profondeur de l'encolure à l'arrière du cou",
  "backHemSlope.t": "Pente de l'ourlet dos",
  "backHemSlope.d": "Contrôle la pente de l'ourlet à l'arrière",
  "frontShoulderWidth.t": "Largeur d'épaule devant",
  "frontShoulderWidth.d": "Contrôle l'étroitesse des longueurs d'épaules de devant par rapport au dos",
  "highBustWidth.t": "Largeur de buste supérieur",
  "highBustWidth.d": "Permet de modifier la largeur de buste supérieur à l'avant"
}

export default o_bella
