/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Courbe de manche",
  "sleeveBend.d": "Contrôle la courbure de la manche au niveau du coude.",
  "sleevecapHeight.t": "Hauteur du tête de manche",
  "sleevecapHeight.d": "Contrôle la hauteur du tête de manche"
}

export default o_bent
