/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Renflement",
  "bulge.d": "Augmentez l'angle pour créer plus d'espace dans la poche avant.",
  "legBonus.t": "Bonus de longueur de jambes",
  "legBonus.d": "Longueur supplémentaire à ajouter aux jambes.",
  "rise.t": "Élévation de ceinture",
  "rise.d": "Montant d'élévation pour la ceinture vers la taille. Une valeur négative l'abaissera.",
  "stretch.t": "Élasticité",
  "stretch.d": "La quantité d'aisance négative.",
  "legStretch.t": "Élasticité des jambes",
  "legStretch.d": "Pour de meilleurs résultats, vous souhaitez ajuster vos jambes plus étroites - choisissez non à l'écart.",
  "backRise.t": "Élévation arrière",
  "backRise.d": "Pourcentage selon lequel la taille sera relevée à l'arrière."
}

export default o_bruce
