/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Pince d'épaule",
  "shoulderDart.d": "S'il faut ou non inclure une pince à l'épaule pour arrondir le dos",
  "shoulderDartSize.t": "Taille de la pince de l'épaule",
  "shoulderDartSize.d": "La taille de la pince d'épaule",
  "shoulderDartLength.t": "Longueur de la pince de l'épaule",
  "shoulderDartLength.d": "La longueur de la pince d'épaule",
  "waistDart.t": "Pince de taille",
  "waistDart.d": "S'il faut ou non inclure une pince à la taille pour arrondir le dos",
  "waistDartSize.t": "Taille de la pince de taille",
  "waistDartSize.d": "La taille de la pince de taille",
  "waistDartLength.t": "Longueur de la pince de taille",
  "waistDartLength.d": "La longueur de la pince de taille",
  "verticalEase.t": "Aisance verticale",
  "verticalEase.d": "La quantité d'aisance à répartir sur la longueur du vêtement",
  "waistEase.t": "Aisance à la taille",
  "waistEase.d": "L'ampleur d'aisance à votre taille",
  "primaryBustDart.t": "Pince poitrine",
  "primaryBustDart.d": "Où placer la pince poitrine pour s'adapter à la poitrine",
  "primaryBustDartLength.t": "Longueur des pinces poitrine",
  "primaryBustDartLength.d": "La longueur de la pince de poitrine",
  "secondaryBustDart.t": "Pince poitrine secondaire",
  "secondaryBustDart.d": "Inclut éventuellement une poitrine secondaire pour répartir la mise en forme de la poitrine",
  "secondaryBustDartLength.t": "Longueur de la pince poitrine secondaire",
  "secondaryBustDartLength.d": "La longueur de la pince poitrine secondaire",
  "primaryBustDartShaping.t": "Forme des pinces poitrine",
  "primaryBustDartShaping.d": "Contrôle l'équilibre entre les pinces de buste principale et secondaire"
}

export default o_breanna
