/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlton = {
  "seatEase.t": "Aisance d'assise",
  "seatEase.d": "Quantité d'aisance autour de vos fesses",
  "pocketPlacementHorizontal.t": "Placement horizontal des poches",
  "pocketPlacementHorizontal.d": "L'emplacement (horizontal) des poches",
  "pocketPlacementVertical.t": "Placement vertical des poches",
  "pocketPlacementVertical.d": "L'emplacement (vertical) des poches",
  "collarHeight.t": "Hauteur du col",
  "collarHeight.d": "Hauteur du col",
  "length.t": "Longueur",
  "length.d": "Longueur totale",
  "pocketFlapRadius.t": "Angle de rabat de poche",
  "pocketFlapRadius.d": "Le montant par lequel le rabat de poche est arrondi",
  "pocketRadius.t": "Arrondi de poche",
  "pocketRadius.d": "Le montant par lequel la poche est arrondie",
  "chestPocketHeight.t": "Hauteur de la poche de poitrine",
  "chestPocketHeight.d": "Hauteur de la poche de poitrine",
  "beltWidth.t": "Largeur de ceinture",
  "beltWidth.d": "Largeur de ceinture",
  "buttonSpacingHorizontal.t": "Espacement horizontal des boutons",
  "buttonSpacingHorizontal.d": "L'espacement horizontal des boutons détermine également le chevauchement de la fermeture avant"
}

export default o_carlton
