/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlita = {
  "contour.t": "Contour",
  "contour.d": "Contrôle à quel point la courbe de la découpe princesse sera saillante ou adoucie."
}

export default o_carlita
