/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cathrin = {
  "panels.t": "Nombre de pièces",
  "panels.d": "Le nombre de pièces à tracer. Plus il y a de pièces, mieux c'est pour l'ajustement des modèles avec courbes.",
  "waistReduction.t": "Réduction de la taille",
  "waistReduction.d": "Le montant par lequel vous voulez que le corset resserre votre taille.",
  "backOpening.t": "Ouverture arrière",
  "backOpening.d": "Ouverture au centre de la fermeture du dos.",
  "backRise.t": "Élévation dos",
  "backRise.d": "À quel point les panneaux arrière s’élèvent de vos bras au centre de votre dos.",
  "backDrop.t": "Abaissement du dos",
  "backDrop.d": "Combien les panneaux arrière s'abaissent de vos hanches vers votre centre arrière Les valeurs négatives vont lever le dos.",
  "frontRise.t": "Élévation avant",
  "frontRise.d": "Élévation des panneaux avant au centre avant, entre vos seins. Les valeurs négatives les diminueront.",
  "frontDrop.t": "Abaissement avant",
  "frontDrop.d": "Combien les panneaux avant s'abaissent de vos hanches vers votre centre avant.",
  "hipRise.t": "Élévation des hanches",
  "hipRise.d": "Combien les panneaux latéraux montent sur vos hanches."
}

export default o_cathrin
