/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_charlie = {
  "backPocketHorizontalPlacement.t": "Placement horizontal de la poche arrière",
  "backPocketHorizontalPlacement.d": "Contrôle le placement horizontal de la poche arrière",
  "backPocketVerticalPlacement.t": "Placement vertical de la poche arrière",
  "backPocketVerticalPlacement.d": "Contrôle le placement vertical de la poche arrière",
  "backPocketWidth.t": "Largeur de la poche arrière",
  "backPocketWidth.d": "Contrôle la largeur de la poche arrière",
  "backPocketDepth.t": "Profondeur de la poche arrière",
  "backPocketDepth.d": "Contrôle la profondeur de la poche arrière",
  "backPocketFacing.t": "Fond de poche arrière",
  "backPocketFacing.d": "Contrôle s'il faut inclure ou non un fond dans les poches arrière",
  "frontPocketSlantDepth.t": "Profondeur de la poche avant",
  "frontPocketSlantDepth.d": "Contrôle la profondeur de la poche (frontale)",
  "frontPocketSlantWidth.t": "Largeur de la poche frontale",
  "frontPocketSlantWidth.d": "Contrôle la largeur de la fenêtre de poche (frontale)",
  "frontPocketSlantRound.t": "Arrondi de poche avant",
  "frontPocketSlantRound.d": "Contrôle à quelle distance de la fin de l'objectif nous commençons à arrondir dans le dehors",
  "frontPocketSlantBend.t": "courbure de la poche avant",
  "frontPocketSlantBend.d": "Contrôle le rayon par lequel on arrondit la poche enfoncée dans la sortie",
  "frontPocketWidth.t": "Largeur des poches avant",
  "frontPocketWidth.d": "Contrôle la largeur du sac de poche avant",
  "frontPocketDepth.t": "Profondeur des poches avant",
  "frontPocketDepth.d": "Contrôle la profondeur du sac de poche avant",
  "frontPocketFacing.t": "Poche avant face",
  "frontPocketFacing.d": "Contrôle la distance à laquelle la poche est orientée dans le sac de poche",
  "beltLoops.t": "Boucles de ceinture",
  "beltLoops.d": "Contrôle la quantité de boucles de ceinture",
  "flyCurve.t": "Voler la courbe",
  "flyCurve.d": "Contrôle la courbure de la couture J-fly",
  "flyLength.t": "Longueur de la mouche",
  "flyLength.d": "Contrôle la longueur de la mouche",
  "flyWidth.t": "Fly width",
  "flyWidth.d": "Contrôle à quelle distance le J-couture de décalage par rapport au bord de la volée",
  "waistbandCurve.t": "Courbe de la ceinture",
  "waistbandCurve.d": "Contrôle la courbure de la ceinture."
}

export default o_charlie
