/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cornelius = {
  "fullness.t": "Ampleur",
  "fullness.d": "Contrôle l'ampleur de la culotte",
  "waistbandBelowWaist.t": "Abaissement de la ceinture",
  "waistbandBelowWaist.d": "Pourcentage pour déplacer la ceinture sous la taille réelle",
  "waistReduction.t": "Réduction de la taille",
  "waistReduction.d": "Pourcentage de réduction de la ceinture",
  "cuffWidth.t": "Largeur du bracelet",
  "cuffWidth.d": "Largeur du bracelet de la jambe",
  "cuffStyle.t": "Style de poignet",
  "cuffStyle.d": "Style du bracelet de la jambe",
  "bandBelowKnee.t": "Bracelet sous le genou",
  "bandBelowKnee.d": "Contrôle la distance du bracelet sous le genou",
  "kneeToBelow.t": "Longueur de poignet",
  "kneeToBelow.d": "Contrôle l'épaisseur du bracelet par rapport au genou",
  "ventLength.t": "Longueur de la fente",
  "ventLength.d": "Contrôle la longueur de la fente entre le genou et le bracelet"
}

export default o_cornelius
