/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_diana = {
  "shoulderSeamLength.t": "Longueur de couture d'épaule",
  "shoulderSeamLength.d": "Contrôle la longueur de la couture d'épaule",
  "drapeAngle.t": "Angle du drapé",
  "drapeAngle.d": "Contrôle le montant du drapé"
}

export default o_diana
