/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florent = {
  "headEase.t": "Aisance de tour de tête",
  "headEase.d": "La quantité d'aisance autour de votre tête"
}

export default o_florent
