/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florence = {
  "height.t": "Hauteur",
  "height.d": "Contrôle la hauteur du masque",
  "length.t": "Longeur",
  "length.d": "Contrôle la longueur du masque",
  "curve.t": "Courbe",
  "curve.d": "Contrôle la courbe du bord supérieur du masque"
}

export default o_florence
