/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hortensia = {
  "size.t": "Taille",
  "size.d": "Contrôle la taille globale du sac à main",
  "zipperSize.t": "Taille du Zip",
  "zipperSize.d": "Quelle taille de zip utliser",
  "strapLength.t": "Longueur du lien",
  "strapLength.d": "Contrôle la longueur des anses",
  "handleWidth.t": "Largeur d'anse",
  "handleWidth.d": "Contrôle la largeur de l'anse"
}

export default o_hortensia
