/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_holmes = {
  "headEase.t": "Aisance du tour de tête",
  "headEase.d": "La quantité d'aisance autour de votre tête.",
  "lengthRatio.t": "Profondeur de tête",
  "lengthRatio.d": "Contrôle la longueur de la couronne et des rabats d'oreilles",
  "gores.t": "Nombre de pans",
  "gores.d": "Le nombre de pans utilisés pour construire la couronne",
  "visorAngle.t": "Angle de la visière",
  "visorAngle.d": "L'angle d'arc utilisé pour tracer la courbe intérieure de la visière",
  "visorWidth.t": "Largeur de la visière",
  "visorWidth.d": "Contrôle la largeur de la visière",
  "earLength.t": "Longueur du rabat de l'oreille",
  "earLength.d": "Contrôle la longueur des rabats de l'oreille indépendamment des autres pièces de contour",
  "earWidth.t": "Largeur du rabat de l'oreille",
  "earWidth.d": "Contrôle la largeur des rabats de l'oreille",
  "buttonhole.t": "Guide des boutonnières",
  "buttonhole.d": "Ajoute une boutonnière au rabat d'oreille pour vous aider à tracer la variante du rabat de l'oreille avec boutonnière",
  "visorLength.t": "Longueur de la visière",
  "visorLength.d": "Contrôle la longueur de la visière"
}

export default o_holmes
