/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hugo = {
  "hipsEase.t": "Aisance des hanches",
  "hipsEase.d": "La marge d'aisance aux hanches."
}

export default o_hugo
