/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_huey = {
  "pocket.t": "Poche",
  "pocket.d": "S'il faut inclure une poche avant ou non",
  "pocketHeight.t": "Hauteur de la poche",
  "pocketHeight.d": "Contrôle la hauteur de la poche",
  "hoodHeight.t": "Hauteur de capuche",
  "hoodHeight.d": "Contrôle la hauteur de la capuche",
  "hoodCutback.t": "Coupe arrière de capuche",
  "hoodCutback.d": "Contrôle la courbure à l'arrière de la capuche",
  "hoodClosure.t": "Fermeture de capuche",
  "hoodClosure.d": "Contrôle la quantité de capuche sur la partie avant",
  "hoodDepth.t": "Profondeur du capuche",
  "hoodDepth.d": "Contrôle la profondeur de la capuche",
  "hoodAngle.t": "Angle de capuche",
  "hoodAngle.d": "Contrôle l'angle de fixation de la capuche"
}

export default o_huey
