/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_lucy = {
  "width.t": "Width",
  "width.d": "Width of the pocket",
  "length.t": "Length",
  "length.d": "Length (depth) of the pocket",
  "edge.t": "Taper",
  "edge.d": "Controls how much the pocket opening tapers inwards"
}

export default o_lucy
