/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_lunetius = {
  "lengthRatio.t": "Ratio de longueur",
  "lengthRatio.d": "Contrôle la longueur du vêtement",
  "widthRatio.t": "Ratio de largeur",
  "widthRatio.d": "Contrôle la largeur du vêtement",
  "length.t": "Longueur",
  "length.d": "Choisit parmi les différents styles de longueur"
}

export default o_lunetius
