/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_paco = {
  "heelEase.t": "Aisance de talon",
  "heelEase.d": "La quantité d'aisance à votre talon (au passage la jambe de pantalon)",
  "frontPockets.t": "Poches avant",
  "frontPockets.d": "Si oui ou non ajouter des poches avant sur la couture latérale",
  "backPockets.t": "Poches arrière",
  "backPockets.d": "Si oui ou non ajouter des poches à l'arrière",
  "elasticatedHem.t": "Ourlet élastiqué",
  "elasticatedHem.d": "Si vous voulez ou non un ourlet élastiqué",
  "ankleElastic.t": "Largeur élastique de cheville/ourlet",
  "ankleElastic.d": "Largeur de l'élastique (optionnel) à la cheville/ourlet"
}

export default o_paco
