/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_penelope = {
  "backDartDepthFactor.t": "Profondeur de la pince dos",
  "backDartDepthFactor.d": "Jusqu'où va la pince arrière depuis la ceinture, facteur de la mensuration \"Hauteur taille bassin\".",
  "backVent.t": "Fentes arrière",
  "backVent.d": "Ajouter une fente au dos de la jupe.",
  "backVentLength.t": "Longueur de fente arrière",
  "backVentLength.d": "Longueur de la fente dos par rapport à la longueur de la jupe.",
  "dartToSideSeamFactor.t": "Pince de côté",
  "dartToSideSeamFactor.d": "Pourcentage de la part de la réduction de la hanche à la taille par rapport à la couture latérale.",
  "frontDartDepthFactor.t": "Profondeur de la pince avant",
  "frontDartDepthFactor.d": "Jusqu'où va la pince avant depuis la ceinture, facteur de la mensuration \"Hauteur taille bassin\".",
  "hem.t": "Taille de l'ourlet",
  "hem.d": "La taille de l'ourlet. Mesure en valeurs absolues.",
  "hemBonus.t": "Bonus d'ourlet",
  "hemBonus.d": "Cette option réduira la circonférence de la jupe à l'ourlet. Pourcentage de la mesure de l'assise.",
  "lengthBonus.t": "Supplément de longueur",
  "lengthBonus.d": "Ceci définit la longueur de la jupe. Pourcentage de la mensuration \"Hauteur taille genou\".",
  "nrOfDarts.t": "Nombre de pinces",
  "nrOfDarts.d": "Le nombre de pinces utilisées dans le patron. Maximum de 2. Cette option peut être réduite par le patron si les calculs créent des pinces trop petites.",
  "seatEase.t": "Aisance d'assise",
  "seatEase.d": "Quantité d'aisance au niveau de l'assise.",
  "waistBand.t": "Ceinture",
  "waistBand.d": "Ajouter une ceinture au patron.",
  "waistBandWidth.t": "Largeur de ceinture",
  "waistBandWidth.d": "La largeur de la ceinture.",
  "waistEase.t": "Aisance à la taille",
  "waistEase.d": "Quantité d'aisance au niveau de la taille.",
  "zipperLocation.t": "Emplacement du Zip",
  "zipperLocation.d": "L'emplacement du zip (fermeture éclair)."
}

export default o_penelope
