/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sandy = {
  "waistbandWidth.t": "Largeur de ceinture",
  "waistbandWidth.d": "Contrôle la largeur de la ceinture.",
  "waistbandPosition.t": "Position de ceinture",
  "waistbandPosition.d": "Contrôle la position de la ceinture.",
  "waistbandShape.t": "Forme de ceinture",
  "waistbandShape.d": "Si vous voulez une ceinture droite ou bien de forme particulière.",
  "circleRatio.t": "Ratio circulaire",
  "circleRatio.d": "Le pourcentage d'un cercle auquel vous souhaitez que la jupe corresponde.",
  "waistbandOverlap.t": "Chevauchement de la ceinture",
  "waistbandOverlap.d": "Le montant par lequel la taille se chevauche.",
  "gathering.t": "Fronçage",
  "gathering.d": "Le pourcent par lequel le tissu du haut de la jupe est plus long que celui du bas de la ceinture.",
  "seamlessFullCircle.t": "Cercle entier sans couture",
  "seamlessFullCircle.d": "Permet une jupe totalement circulaire sans couture.",
  "hemWidth.t": "Hem width",
  "hemWidth.d": "Largeur de l'ourlet"
}

export default o_sandy
