/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_shin = {
  "legReduction.t": "Réduction de jambe",
  "legReduction.d": "Réduit l'ouverture de la jambe pour éviter les effets de flottement",
  "elasticWidth.t": "Largeur d'élastique",
  "elasticWidth.d": "Largeur de l'élastique à la taille"
}

export default o_shin
