/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_simone = {
  "bustDartAngle.t": "Angle des pinces poitrine",
  "bustDartAngle.d": "Contrôle l'angle par lequel la pince poitrine (sur le côté) s'incline vers le bas",
  "bustDartLength.t": "Longueur des pinces poitrine",
  "bustDartLength.d": "Contrôle à quel point la pince poitrine sera proche de l'apex du buste (la pointe des seins)",
  "contour.t": "Angle des découpes princesses",
  "contour.d": "Contrôle à quel point le volume sera réduit sous les seins",
  "frontDarts.t": "Pinces de taille",
  "frontDarts.d": "Inclure ou non des pinces de taille",
  "frontDartLength.t": "Longueur des pinces de taille",
  "frontDartLength.d": "Contrôle à quel point la pince de taille sera proche de l'apex du buste (la pointe des seins)"
}

export default o_simone
