/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sven = {
  "hipsEase.t": "Aisance des hanches",
  "hipsEase.d": "Contrôle la quantité d'aisance à vos hanches (au bas du sweat)",
  "ribbing.t": "Bord côte",
  "ribbing.d": "Faut-il finir l'ourlet et les poignets avec un tissu pour bordures",
  "ribbingHeight.t": "Hauteur de bord côte",
  "ribbingHeight.d": "La hauteur du tissu pour le bord côte sur les poignets et le bas du sweat.",
  "ribbingStretch.t": "Élasticité du bord côte",
  "ribbingStretch.d": "L'élasticité du bord côte sur les poignets et le bas."
}

export default o_sven
