/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tamiko = {
  "flare.t": "Évasement",
  "flare.d": "La quantité par laquelle le vêtement s'évase de votre poitrine vers le bas",
  "shoulderseamLength.t": "Longueur de couture d'épaule",
  "shoulderseamLength.d": "La longueur de la couture d'épaule, en tant que facteur de la mesure d'épaule à épaule",
  "shoulderSlope.t": "Pente d'épaule",
  "shoulderSlope.d": "Contrôle l'angle des coutures d'épaule"
}

export default o_tamiko
