/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Tracé pour le buste supérieur",
  "draftForHighBust.d": "Tracer le patron pour la mesure de tour de poitrine supérieure (si disponible) plutôt que la poitrine (pleine). Il en résultera un vêtement plus ajusté pour les personnes qui ont des seins.",
  "sleeveEase.t": "Aisance des manches",
  "sleeveEase.d": "Quantité d'aisance de vos manches",
  "sleeveLength.t": "Longueur des manches",
  "sleeveLength.d": "Contrôle la longueur de vos manches",
  "necklineBend.t": "Courbure de l'encolure",
  "necklineBend.d": "Contrôle la courbure de l'encolure.",
  "necklineDepth.t": "Profondeur de l'encolure",
  "necklineDepth.d": "Contrôle la profondeur de l'encolure.",
  "necklineWidth.t": "Largeur d'encolure",
  "necklineWidth.d": "Contrôle la largeur de l'encolure."
}

export default o_teagan
