/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_theo = {
  "wedge.t": "Fourche",
  "wedge.d": "Contrôle la longueur de la couture croisée",
  "legWidth.t": "Largeur de jambe",
  "legWidth.d": "Contrôle la largeur des jambes"
}

export default o_theo
