/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tiberius = {
  "headRatio.t": "Ratio tête",
  "headRatio.d": "Contrôle la taille de l'ouverture de la tête",
  "armholeDrop.t": "Abaissement d'emmanchure",
  "armholeDrop.d": "Contrôle la profondeur de l'emmanchure",
  "lengthBonus.t": "Supplément de longueur",
  "lengthBonus.d": "Permet de varier la longueur du vêtement",
  "widthBonus.t": "Bonus de largeur",
  "widthBonus.d": "Permet de varier la largeur du vêtement",
  "clavi.t": "Bande de pourpre",
  "clavi.d": "Inclure ou non des guides pour la bande de pourpre",
  "clavusLocation.t": "Emplacement de la bande de pourpre",
  "clavusLocation.d": "Contrôle la localisation de la bande de pourpre",
  "clavusWidth.t": "Largeur de la bande de pourpre",
  "clavusWidth.d": "Contrôle la largeur de la bande de pourpre",
  "length.t": "Longueur",
  "length.d": "Contrôle la longueur du vêtement",
  "width.t": "Largeur",
  "width.d": "Contrôle la largeur du vêtement",
  "forceWidth.t": "Forcer la largeur",
  "forceWidth.d": "Appliquer les paramètres de largeur indépendamment des contraintes"
}

export default o_tiberius
