/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_titan = {
  "kneeEase.t": "Aisance du genou",
  "kneeEase.d": "Contrôle la quantité d'aisance au genou",
  "waistHeight.t": "Hauteur de la taille",
  "waistHeight.d": "Contrôle la hauteur de la taille, 100% = hauteur de la taille, 0% = hauteur de la hanche",
  "lengthBonus.t": "Supplément de longueur",
  "lengthBonus.d": "Contrôle la longueur du pantalon",
  "crotchDrop.t": "Hauteur d'enfourchure",
  "crotchDrop.d": "Abaisse la fourche pour un tombé plus décontracté",
  "fitKnee.t": "Ajuster au genou",
  "fitKnee.d": "Ajuste les jambes à partir de la circonférence du genou plutôt que de la circonférence du bassin",
  "legBalance.t": "Équilibre des jambes",
  "legBalance.d": "Contrôle le ratio entre le panneau avant et arrière de la jambe",
  "crossSeamCurveStart.t": "Début de la courbe de l'enfourchure dos",
  "crossSeamCurveStart.d": "Contrôle la distance à partir de laquelle la courbe démarre pour l'enfourchure dos",
  "crossSeamCurveBend.t": "Courbure de l'enfourchure dos",
  "crossSeamCurveBend.d": "Contrôle la courbure de la couture de fourche dos",
  "crossSeamCurveAngle.t": "Angle de couture croisée",
  "crossSeamCurveAngle.d": "Contrôle l'angle de la couture de croix",
  "crotchSeamCurveStart.t": "Début de la courbe de l'enfourchure avant",
  "crotchSeamCurveStart.d": "Contrôle la distance à partir de laquelle la courbe démarre pour l'enfourchure avant",
  "crotchSeamCurveBend.t": "Courbure de la fourche avant",
  "crotchSeamCurveBend.d": "Contrôle la courbure de la couture de fourche avant",
  "crotchSeamCurveAngle.t": "Angle de couture",
  "crotchSeamCurveAngle.d": "Contrôle l'angle de la couture de crotch",
  "waistBalance.t": "Équilibre de la taille",
  "waistBalance.d": "Contrôle la position horizontale de la taille par rapport au bassin",
  "waistbandWidth.t": "Largeur de ceinture",
  "waistbandWidth.d": "La largeur de la ceinture",
  "grainlinePosition.t": "Position de la ligne de droit fil",
  "grainlinePosition.d": "Contrôle la position horizontale de la jambe par rapport au bassin"
}

export default o_titan
