/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_trayvon = {
  "tipWidth.t": "Largeur de la pointe",
  "tipWidth.d": "La largeur de votre cravate au niveau de la pointe",
  "knotWidth.t": "Largeur du nœud",
  "knotWidth.d": "La largeur de votre cravate au niveau du noeud"
}

export default o_trayvon
