/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_ursula = {
  "fabricStretch.t": "Étendue en tissu",
  "fabricStretch.d": "Ajuster ceci pour des tissus plus ou moins extensifs",
  "gussetWidth.t": "Gusset width",
  "gussetWidth.d": "Contrôle la largeur du gusset",
  "gussetLength.t": "Longueur du Gusset",
  "gussetLength.d": "Contrôle la longueur du gusset",
  "elasticStretch.t": "Etendue élastique",
  "elasticStretch.d": "Ajuster ceci pour un élastique plus ou moins extensif",
  "rise.t": "Élévation de ceinture",
  "rise.d": "Contrôle la hauteur de la taille",
  "legOpening.t": "Ouverture des jambes",
  "legOpening.d": "Contrôle la hauteur de la jambe découpée",
  "frontDip.t": "tremper la taille de la taille avant",
  "frontDip.d": "Contrôle la quantité de courbes de la taille avant (révélant plus ou moins la peau)",
  "backDip.t": "trempette à taille arrière",
  "backDip.d": "Contrôle la quantité de courbes de la taille arrière (révélant plus ou moins la peau)",
  "taperToGusset.t": "Exposition frontale",
  "taperToGusset.d": "Contrôle la quantité de peau exposée à l'avant",
  "backExposure.t": "Exposition au dos",
  "backExposure.d": "Contrôle la quantité de peau exposée au dos"
}

export default o_ursula
