/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_wahid = {
  "backScyeDart.t": "Pince de carrure",
  "backScyeDart.d": "La valeur à retirer dans une pince de carrure (à l'emmanchure arrière).",
  "frontScyeDart.t": "Pince d'emmanchure",
  "frontScyeDart.d": "La quantité à retirer de la pince à l'avant de l'emmanchure.",
  "pocketLocation.t": "Emplacement de poche",
  "pocketLocation.d": "Détermine l'emplacement de la poche",
  "pocketWidth.t": "Largeur de poche",
  "pocketWidth.d": "Détermine la largeur de la poche",
  "weltHeight.t": "Hauteur du revers de poche",
  "weltHeight.d": "Détermine la hauteur du revers de poche",
  "necklineDrop.t": "Décolleté",
  "necklineDrop.d": "Détermine la profondeur d'encolure sur le devant",
  "frontStyle.t": "Style d'encolure",
  "frontStyle.d": "Style de l'encolure",
  "hemStyle.t": "Type d'ourlet",
  "hemStyle.d": "Style de l'ourlet avant",
  "hemRadius.t": "Arrondi d'ourlet",
  "hemRadius.d": "Rayon avec lequel l'ourlet est arrondi",
  "backInset.t": "Échancrure emmanchure arrière",
  "backInset.d": "A quel point l'arrière de l'emmanchure est coupée vers l'intérieur",
  "frontInset.t": "Échancrure emmanchure avant",
  "frontInset.d": "A quel point l'avant de l'emmanchure est coupée vers l'intérieur",
  "shoulderInset.t": "Réduction d'épaule",
  "shoulderInset.d": "A quel point la couture d'épaule est éloignée des épaules",
  "neckInset.t": "Échancrure cou",
  "neckInset.d": "A quel point la couture d'épaule est éloignée du cou",
  "pocketAngle.t": "Angle de poche",
  "pocketAngle.d": "Angle de l'ouverture de poche"
}

export default o_wahid
