/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_waralee = {
  "backPocket.t": "Poche arrière",
  "backPocket.d": "S'il faut inclure une poche arrière ou non",
  "frontPocket.t": "Poche avant",
  "frontPocket.d": "Inclure ou non des poches avant",
  "hem.t": "Taille de l'ourlet",
  "hem.d": "Taille de l'ourlet au bas du pantalon",
  "waistBand.t": "Bande de taille",
  "waistBand.d": "Taille de la bande de taille",
  "waistRaise.t": "Hauteur de taille",
  "waistRaise.d": "Combien il faut élever la taille de la mesure de hauteur d'assise, ce qui influence la profondeur de la coupe de l'entre-jambe.",
  "crotchBack.t": "Fourche arrière",
  "crotchBack.d": "Le pourcentage de la circonférence d'assise à l'arrière. Cela crée plus ou moins d'espace entre la couture latérale et le dos.",
  "crotchFront.t": "Fourche avant",
  "crotchFront.d": "Le pourcentage de la circonférence d'assise à l'avant. Cela crée plus ou moins d'espace entre la couture latérale et le devant.",
  "crotchFactorBackHor.t": "Reculer la fourche arrière",
  "crotchFactorBackHor.d": "Utilisé pour déplacer la courbe de la fourche arrière horizontalement",
  "crotchFactorBackVer.t": "Remonter la fourche arrière",
  "crotchFactorBackVer.d": "Utilisé pour déplacer la courbe de la fourche arrière verticalement",
  "crotchFactorFrontHor.t": "Avancer la fourche avant",
  "crotchFactorFrontHor.d": "Utilisé pour déplacer la courbe de la fourche avant horizontalement",
  "crotchFactorFrontVer.t": "Remonter la fourche avant",
  "crotchFactorFrontVer.d": "Utilisé pour déplacer la courbe de la fourche avant verticalement",
  "waistOverlap.t": "Chevauchement de la ceinture",
  "waistOverlap.d": "Cela indique combien vous voulez que les pans de la jambe se chevauchent à la taille. Un réglage de 0 les ferait rencontrer à la couture latérale, et un cadre de 100 les fait se rencontrer à l'avant/arrière.",
  "legShortening.t": "Réduction des jambes",
  "legShortening.d": "Cela indique la longueur du pantalon. C'est un facteur de la mesure de l'entrejambe. Plus la valeur est grande, plus elle sera retirée de la longueur.",
  "backRaise.t": "Élévation arrière",
  "backRaise.d": "Ce réglage lève la taille dans le dos, la taille ne se pose pas horizontalement, mais est inclinée à l'arrière. Ce réglage vous permet de la relever dans le dos si vous en avez besoin pour un bon ajustement."
}

export default o_waralee
