/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_walburga = {
  "headRatio.t": "Ratio de tête",
  "headRatio.d": "Contrôle la taille de l'ouverture de la tête",
  "lengthBonus.t": "Supplément de longueur",
  "lengthBonus.d": "Permet de varier la longueur du vêtement",
  "widthBonus.t": "Bonus de largeur",
  "widthBonus.d": "Permet de varier la largeur du vêtement",
  "length.t": "Longueur",
  "length.d": "Contrôle la longueur du vêtement",
  "neckoRatio.t": "Forme de l'encolure",
  "neckoRatio.d": "contrôle la forme de l'encolure",
  "neckline.t": "Ligne d'encolure",
  "neckline.d": "Contrôle si oui ou non il faut tracer un encolure"
}

export default o_walburga
