/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const optiongroups = {
  "advanced": "Avancé",
  "armhole": "Emmanchure",
  "closure": "Fermeture",
  "collar": "Col",
  "construction": "Montage",
  "cuffs": "Poignets",
  "darts": "Pinces",
  "elastic": "Élastique",
  "fit": "Ajustement",
  "pockets": "Poches",
  "preferences": "Préférences",
  "sleevecap": "Tête de manche",
  "sleeves": "Manches",
  "style": "Style",
  "backPockets": "Poches arrière",
  "frontPockets": "Poches avant",
  "waistband": "Ceinture",
  "fly": "Vol",
  "bellaDarts": "Pinces de Bella",
  "bellaArmhole": "Emmanchure de Bella",
  "bellaAdvanced": "Bella avancé",
  "clavi": "Bande de pourpre"
}

export default optiongroups
