/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const patrons = {
  "becomeAPatron": "Become a patron",
  "supportFreesewing": "Support FreeSewing"
}

export default patrons
