/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const posts = {
  "xMadeThis": "<strong>{x}</strong> made this",
  "xWroteThis": "<strong>{x}</strong> wrote this"
}

export default posts
