/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const settings = {
  "advanced.t": "Mode expert",
  "advanced.d": "Permet d'afficher ou non les paramètres avancés et les options de patron",
  "paperless.t": "Sans papier",
  "paperless.d": "Dessine un patron avec toutes les dimensions incluses afin que vous puissiez le transférer sur du tissu ou un autre support sans avoir à imprimer",
  "sa.t": "Marge de couture",
  "sa.d": "Contrôle la valeur de la marge de couture incluse dans votre patron",
  "locale.t": "Langue",
  "locale.d": "Détermine la langue utilisée sur votre patron",
  "only.t": "Contenus",
  "only.d": "Vous permet de contrôler quelles parties seront incluses dans votre patron",
  "units.t": "Unités",
  "units.d": "Contrôle les unités utilisées sur votre patron",
  "margin.t": "Marges",
  "margin.d": "Contrôle la marge autour des pièces du patron",
  "complete.t": "Détail",
  "complete.d": "Contrôle à quel point votre patron est détaillé ; soit un patron complet avec tous les détails, ou simplement les contours des parties du patron",
  "layout.t": "Mis en page",
  "layout.d": "Contrôle la manière dont les différentes parties sont placées sur votre patron",
  "debug.t": "Débug",
  "debug.d": "Activer le débogage pour obtenir des informations supplémentaires sur la façon dont votre patron a été créé",
  "scale.t": "Échelle",
  "scale.d": "Contrôle la largeur de la ligne de contour, la taille de police et les autres éléments dont la valeur est indépendante des mesures du patron",
  "renderer.t": "Moteur de Rendu",
  "renderer.d": "Contrôle comment le patron est restitué (dessiné) à l'écran",
  "xray.t": "Rayons X",
  "xray.d": "Regardez en dessous avec le mode rayons X de FreeSewing"
}

export default settings
