/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const themes = {
  "lightTheme": "Light Theme",
  "darkTheme": "Dark Theme",
  "hax0rTheme": "Hax0r Theme",
  "lgbtqTheme": "LGBTQ Theme",
  "transTheme": "Trans Theme"
}

export default themes
