/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Sélectionnez les unités que vous souhaitez utiliser",
  "username": "Choisissez un nom d’utilisateur",
  "avatar": "Ajoutez une photo de profil",
  "bio": "Parlez-nous un peu de vous",
  "social": "Dites-nous où nous pouvons vous suivre",
  "newsletter": "Donnez-nous votre préférence pour la newsletter",
  "letUsSetupYourAccount": "Laissez-nous configurer votre compte.",
  "walkYouThrough": "Nous vous guiderons à travers les étapes suivantes :",
  "someOptional": "Bien que toutes ces étapes soient facultatives, nous vous recommandons de les passer en revue pour tirer le meilleur parti de FreeSewing."
}

export default welcome
