/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cfp = {
  "author": "Autor",
  "githubRepo": "GitHub-Repository",
  "packageManager": "Paket-Manager",
  "patternName": "Schnittmuster-Name",
  "patternType": "Schnittmuster-Art",
  "patternCreated": "Dein Schnittmusterskelett wurde erstellt in",
  "runTheseCommands": "Um loszulegen, führe diesen Befehl aus",
  "startRollup": "In einem Terminal startest du den Rollup-Bundler im Beobachtungsmodus",
  "startWebpack": "Dadurch wird der 'example'-Ordner betreten und die Entwicklungsumgebung gestartet.",
  "devDocsAvailableAt": "Entwicklerdokumentation ist verfügbar auf",
  "talkToUs": "Für Fragen, Feedback oder Anregungen trete unserem Discord-Server bei",
  "draftYourPattern": "Zeichne dein Schnittmuster",
  "testYourPattern": "Teste dein Schnittmuster",
  "draftThing": "{thing} erstellen",
  "testThing": "{thing} testen",
  "renderInBrowser": "Klicke unten, um dein Schnittmuster im Browser zu rendern.",
  "weWillReRender": "Wenn du Änderungen vornimmst, werden wir es erneut für dich rendern.",
  "youCan": "Du kannst",
  "enterMeasurements": "Maße von Hand eingeben",
  "preloadMeasurements": "Einen bestehenden Satz an Maßen einlesen",
  "size": "Größe",
  "noRequiredMeasurements": "Dieses Schnittmuster hat keine benötigten Maße",
  "howtoAddMeasurements": "Um Maße als Anforderung zu definieren, füge sie der Sektion <b>measurements</b> in der Konfigurationsdatei des Schnittmusters hinzu.",
  "seeDocsAt": "Dokumentation zu diesem Thema ist verfügbar unter",
  "clearDesignMode": "Designmodus leeren",
  "designMode": "Designmodus",
  "exportMode": "Exportmodus",
  "thingIsEnabled": "{thing} ist aktiviert",
  "thingIsDisabled": "{thing} ist deaktiviert",
  "turnOn": "Aktivieren",
  "turnOff": "Deaktivieren",
  "validNameWarning": "Bitte wähle einen anderen Namen, da dieser Name Probleme verursachen würde.\nWir (wieder-)verwenden den Namen des Schnittmusters als NPM-Paketname.\nPaketnamen müssen in Kleinbuchstaben geschrieben sein und dürfen keine Sonderzeichen enthalten.\nBitte benenne dein Muster also entsprechend, wie in etwa:"
}

export default cfp
