/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "account": "Account",
  "blog": "Blog",
  "community": "Community",
  "designs": "Entwurf",
  "docs": "Dokumentation",
  "patternInstructions": "Anleitungen für das Schnittmuster",
  "patternOptions": "Schnittmusteroptionen",
  "requiredMeasurements": "Erforderliche Maße",
  "showcase": "Galerie",
  "sloganCome": "Komm für die Schnittmuster",
  "sloganStay": "Bleib für die Community"
}

export default common
