/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const common = {
  "designs": "Entwurf",
  "sloganCome": "Komm für die Schnittmuster",
  "sloganStay": "Bleib für die Community"
}

export default common
