/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const cty = {
  "wafsHashtag": "WeAreFreeSewing",
  "weAreACommunityOfMakers": "Wir sind eine Community von Macher/-innen",
  "weProvideMtmSewingPatterns": "Wir bieten maßgeschneiderte Schnittmuster an",
  "isAPatron": "ist ein/e Förderer/in",
  "contributesWith": "trägt bei mit",
  "communityBuilding": "Gemeinschaftsbildung / Community Building",
  "development": "Entwicklung",
  "patternTesting": "Test von Schnittmustern",
  "patternDesign": "Schnittmuster-Design",
  "support": "Unterstützung",
  "translation": "Übersetzung",
  "writing": "Schreiben",
  "whereToFindUs": "Wo du uns finden kannst",
  "whoWeAre": "Wer wir sind",
  "community": "Community",
  "team": "Team",
  "teams": "Teams",
  "contributors": "Mitwirkende",
  "calls": "Mitwirkendentreffen"
}

export default cty
