/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const email = {
  "chatWithUs": "Chatte mit uns",
  "emailchangeActionText": "Bestätige deine neue E-Mail-Adresse",
  "emailchangeCopy1": "Du hast um die Änderung der E-Mail-Adresse gebeten, die mit deinem Account unter <b>freesewing.org</b> verknüpft ist.<br><br>Bevor du dies tust, musst du deine neue E-Mail-Adresse bestätigen. Bitte klicke auf den folgenden Link, um dies zu tun:",
  "emailchangeHeaderOpeningLine": "Wir stellen nur sicher, dass wir dich bei Bedarf erreichen können",
  "emailchangeHiddenIntro": "Lass uns deine neue E-Mail-Adresse bestätigen",
  "emailchangeSubject": "Bitte bestätige deine neue E-Mail-Adresse",
  "emailchangeTitle": "Bitte bestätige deine neue E-Mail-Adresse",
  "emailchangeWhy": "Du hast diese E-Mail erhalten, weil du die mit deinem Konto auf freesewing.org verknüpfte E-Mail-Adresse geändert hast",
  "footerCredits": "Kreiert von Joost & Mitwirkenden, mit der finanziellen Unterstützung unserer Förderer ❤️ ",
  "footerSlogan": "Freesewing ist eine Open-Source Plattform für Schnittmuster nach Maß",
  "goodbyeCopy1": "Wenn du uns mitteilen möchtest, warum du uns verlässt, kannst du gerne auf diese Nachricht antworten. <br>Von unserer Seite aus werden wir dich nicht weiter stören.",
  "goodbyeHeaderOpeningLine": "Sei dir nur bewusst, dass du jederzeit wiederkommen kannst",
  "goodbyeHiddenIntro": "Vielen Dank, dass du Freesewing eine Chance gegeben hast",
  "goodbyeSubject": "Mach's gut! 👋",
  "goodbyeTitle": "Vielen Dank, dass du Freesewing eine Chance gegeben hast",
  "goodbyeWhy": "Du hast diese E-Mail als endgültiges Lebewohl erhalten, nachdem du deinen Account auf freesewing.org entfernt hast",
  "joostFromFreesewing": "Joost von Freesewing",
  "passwordresetActionText": "Erhalte erneut Zugang zu deinem Account",
  "passwordresetCopy1": "Du hast dein Passwort für deinen Account bei <b>freesewing.org</b> vergessen.<br><br>Klicke auf den folgenden Link, um dein Passwort zurückzusetzen:",
  "passwordresetHeaderOpeningLine": "Keine Sorge, solche Dinge passieren uns allen",
  "passwordresetHiddenIntro": "Erhalte erneut Zugang zu deinem Account",
  "passwordresetSubject": "Erhalte erneut Zugang zu deinem Account auf freesewing.org",
  "passwordresetTitle": "Setze dein Passwort zurück und erhalte erneut Zugang zu deinem Account",
  "passwordresetWhy": "Du hast diese E-Mail erhalten, weil du die Anfrage gestellt hast, dein Passwort von freesewing.org zurückzusetzen",
  "questionsJustReply": "Wenn du Fragen hast, antworte einfach auf diese E-Mail. Ich bin immer gerne bereit zu helfen. 🙂",
  "signature": "Liebe Grüße",
  "signupActionText": "Bestätige deine E-Mail-Adresse",
  "signupCopy1": "Danke, dass du dich bei <b>freesewing.org</b> angemeldet hast.<br><br>Bevor wir beginnen, musst du deine E-Mail-Adresse bestätigen. Bitte klicke auf den folgenden Link, um das zu tun:",
  "signupHeaderOpeningLine": "Wir freuen uns sehr darüber, dass du ein Teil der Freesewing-Community wirst.",
  "signupHiddenIntro": "Lass uns deine E-Mail-Adresse bestätigen",
  "signupSubject": "Willkommen bei freesewing.org",
  "signupTitle": "Willkommen an Bord",
  "signupWhy": "Du hast diese E-Mail erhalten, weil du dich gerade auf freesewing.org angemeldet hast"
}

export default email
