/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const errors = {
  "404": "Die von dir gesuchte Seite kann nicht gefunden werden",
  "confirmationNotFound": "Falls du über den Link in einer Bestätigungs-E-Mail auf dieser Seite gelandet bist, empfehlen wir dir, dieses Problem zu melden.",
  "emailExists": "Wir haben bereits einen Benutzer mit dieser E-Mail-Adresse. Möchtest du dich vielleicht stattdessen einloggen?",
  "networkError": "Back-End oder Netzwerk scheint nicht verfügbar zu sein",
  "notAValidImageFormat": "Kein gültiges Bildformat",
  "requestFailedWithStatusCode400": "Anfrage fehlgeschlagen",
  "requestFailedWithStatusCode401": "Authentifizierung fehlgeschlagen",
  "requestFailedWithStatusCode403": "Verboten",
  "requestFailedWithStatusCode500": "Es gab ein unerwartetes Problem. Bitte melde dies.",
  "something": "Etwas ist schiefgelaufen"
}

export default errors
