/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const i18n = {
  "de": "Deutsch",
  "en": "Englisch",
  "es": "Spanisch",
  "fr": "Französisch",
  "nl": "Niederländisch"
}

export default i18n
