/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const jargon = {
  "basting.d": "Siehe <a href='/docs/sewing/basting/'>Heften</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "coverlock.d": "Siehe <a href='/docs/sewing/coverlock/'>Coverlock</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "cutting.d": "Siehe <a href='/docs/sewing/cutting/'>Zuschnitt</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "darts.d": "<a href='/docs/sewing/darts/'>Abnäher</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "doubleWeltPockets.d": "Siehe <a href='/docs/sewing/double-welt-pockets/'>Doppelpaspeltasche</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "ease.d": "Siehe <a href='/docs/sewing/ease/'>Zugabe</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "edgestitch.d": "See <a href='/docs/sewing/edgestitching/'>Edgestitching</a> in the <a href='/docs/sewing'>Sewing documentation</a>",
  "fabricGrain.d": "Siehe <a href='/docs/sewing/fabric-grain/'>Fadenlauf</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "goodSidesTogether.d": "Siehe <a href='/docs/sewing/good-sides-together/'>rechts auf rechts</a> in der <a href='/docs/sewing/'>Dokumentation zum Nähen</a>",
  "onTheFold.d": "Siehe <a href='/docs/sewing/on-the-fold/'>Im Stoffbruch</a> in der <a href='/docs/sewing/'>Dokumentation zum Nähen</a>",
  "hemming.d": "Siehe <a href='/docs/sewing/hemming/'>Säumen</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "jersey.d": "Siehe <a href='/docs/sewing/jersey/'>Jersey</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "knitBinding.d": "Siehe <a href='/docs/sewing/knit-binding/'>Kantenabschluss mit Maschenware</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "knitFabric.d": "Siehe <a href='/docs/sewing/knit-fabric/'>Maschenware</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "pinning.d": "Siehe <a href='/docs/sewing/pinning/'>Stecken</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "rayon.d": "Siehe <a href='/docs/sewing/rayon/'>Rayon</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "sa.d": "Siehe <a href='/docs/sewing/seam-allowance/'>Nahtzugabe</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "serger.d": "Siehe <a href='/docs/sewing/serger/'>Overlock</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "slipstitch.d": "Siehe <a href='/docs/sewing/slipstitch/'>Kettstich</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "topstitching.d": "Siehe <a href='/docs/sewing/topstitching/'>Absteppen</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "trimming.d": "Siehe <a href='/docs/sewing/trimming/'>Zurückschneiden</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "twinNeedle.d": "Siehe <a href='/docs/sewing/twin-neelde/'>Zwillingsnadel</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "zigZag.d": "Siehe <a href='/docs/sewing/zig-zag-stitch/'>Zickzackstich</a> in der <a href='/docs/sewing'>Dokumentation zum Nähen</a>",
  "freesewing.d": "<b>FreeSewing</b> ist eine Open-Source Plattform für Schnittmuster nach Maß",
  "patternOptions.d": "Die <b>Schnittmusteroptionen</b> erlauben es dir, das Design des Schnittmusters anzupassen",
  "draftSettings.d": "Mit den <b>Entwurfseinstellungen</b> legst du fest, wie ein Schnittmuster erzeugt wird",
  "patrons.d": "Förderer/-innen unterstützen Freesewing finanziell. Sie sind treue Unterstützer/-innen, die für eine nachhaltige Zukunft für freesewing.org, unseren Code, unsere Schnittmuster und unsere Community sorgen.",
  "msf.d": "Médecins Sans Frontières/Ärzte ohne Grenzen - Siehe <a href='https://msf.org/'>msf.org</a>"
}

export default jargon
