/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_aaron = {
  "armholeDrop.t": "Armlochabsenkung",
  "armholeDrop.d": "Senkt das Armloch um diesen Wert. Negative Werte erhöhen es.",
  "backlineBend.t": "Armlochform hinten",
  "backlineBend.d": "Bestimmt die Form / Krümmung der Rückseite der Armlöcher.",
  "hipsEase.t": "Bequemlichkeitszugabe Hüfte",
  "hipsEase.d": "Die Menge an Bequemlichkeits-/Bewegungszugabe an deinen Hüften.",
  "necklineBend.t": "Ausschnittsform",
  "necklineBend.d": "Bestimmt die Form / Krümmung des Halsausschnitts vorne.",
  "necklineDrop.t": "Ausschnitt Tiefe",
  "necklineDrop.d": "Wie tief der Ausschnitt vorne geht.",
  "shoulderStrapPlacement.t": "Platzierung der Schulterträger",
  "shoulderStrapPlacement.d": "Bestimmt, ob der Schulterträger näher am Hals (niedrigere Zahlen), oder näher an der Schulter (höhere Zahlen) liegt.",
  "shoulderStrapWidth.t": "Breite der Schulterträger",
  "shoulderStrapWidth.d": "Die Breite der Schulterträger.",
  "stretchFactor.t": "Dehnung",
  "stretchFactor.d": "Bestimmt die horizontale negative Bewegungszugabe."
}

export default o_aaron
