/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_albert = {
  "backOpening.t": "Hintere Öffnung",
  "backOpening.d": "Steuert die Öffnung an der Rückseite der Schürze",
  "chestDepth.t": "Länge des Riemens",
  "chestDepth.d": "Steuert die Länge der Riemen",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Steuert die Länge der Schürze",
  "bibLength.t": "Latzlänge",
  "bibLength.d": "Steuert die Länge des Latzes",
  "bibWidth.t": "Latzbreite",
  "bibWidth.d": "Steuert die Breite des Latzes",
  "strapWidth.t": "Riemenbreite",
  "strapWidth.d": "Steuert die Breite des Riemens"
}

export default o_albert
