/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bent = {
  "sleeveBend.t": "Ärmelkrümmung",
  "sleeveBend.d": "Steuert die Krümmung des Ärmels am Ellbogen.",
  "sleevecapHeight.t": "Armkugel Höhe",
  "sleevecapHeight.d": "Steuert die Höhe der Armkugel."
}

export default o_bent
