/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_benjamin = {
  "adjustmentRibbon.t": "Einstellband",
  "adjustmentRibbon.d": "Einstellband verwenden oder nicht",
  "bandLength.t": "Bandlänge",
  "bandLength.d": "Lände des Bandes",
  "tipWidth.t": "Spitzenbreite",
  "tipWidth.d": "Breite der Spitzen",
  "knotWidth.t": "Knotenbreite",
  "knotWidth.d": "Breite des Knotens",
  "bowLength.t": "Fliegenlänge",
  "bowLength.d": "Länge der Fliege (wenn geknotet)",
  "bowStyle.t": "Fliegen-Stil",
  "bowStyle.d": "Stil der Fliege",
  "endStyle.t": "Enden-Stil",
  "endStyle.d": "Stil für die Enden der Fliege",
  "collarEase.t": "Kragen Zugabe",
  "collarEase.d": "Die Menge an Zugabe an deinem Hals",
  "ribbonWidth.t": "Bänderbreite",
  "ribbonWidth.d": "Breite des Bandes"
}

export default o_benjamin
