/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bella = {
  "chestEase.t": "Brustumfangszugabe",
  "chestEase.d": "Steuert die Größe der Zugabe zum Brustumfang",
  "waistEase.t": "Taillenzugabe",
  "waistEase.d": "Steuert die Menge an Leichtigkeit in deiner Taille",
  "bustSpanEase.t": "Zugabe seitlicher Brustbereich",
  "bustSpanEase.d": "Steuert die Größe der (horizontalen) Zugabe, zu deinem seitlichen Brustbereich, \nwenn Brustpunkt berechnet wird.",
  "fullChestEaseReduction.t": "Full chest ease reduction",
  "fullChestEaseReduction.d": "Allows you to independently reduce the ease around the chest to make it fit tight(er) in that area",
  "backDartHeight.t": "Höhe Rückenabnäher",
  "backDartHeight.d": "Steuert die Höhe des Rückenabnähers",
  "bustDartLength.t": "Länge des Brustabnähers",
  "bustDartLength.d": "Steuert die Länge des Brustabnähers",
  "waistDartLength.t": "Länge des Taillenabnähers",
  "waistDartLength.d": "Steuert die Länge des Taillenabnähers",
  "bustDartCurve.t": "Rundung Brustabnäher",
  "bustDartCurve.d": "Steuert die Krümmung des Büstendarts",
  "armholeDepth.t": "Armlochtiefe",
  "armholeDepth.d": "Steuert die Tiefe des Armloches",
  "backArmholeSlant.t": "Hintere Armlochschiebung",
  "backArmholeSlant.d": "Das Rüstungsloch dreht sich leicht um seinen Pitchpunkt",
  "frontArmholeCurvature.t": "Vordere Armlochkrümmung",
  "frontArmholeCurvature.d": "Steuert wie tief das Armloch nach vorne unten ausgeschnitten ist",
  "backArmholeCurvature.t": "Hintere Armlochkrümmung",
  "backArmholeCurvature.d": "Steuert wie tief das Armloch nach hinten unten ausgeschnitten ist",
  "frontArmholePitchDepth.t": "Front-Armloch-Tiefe",
  "frontArmholePitchDepth.d": "Stellt die horizontale Position des Vorderarmlochpunktes fest",
  "backArmholePitchDepth.t": "Rückenarmloch-Tiefe",
  "backArmholePitchDepth.d": "Stellt die horizontale Position des Rückenlochpunktes fest",
  "backNeckCutout.t": "Ausschnitt im Nacken",
  "backNeckCutout.d": "Steuert wie tief die Halsöffnung auf der Rückseite abgesogen wird",
  "backHemSlope.t": "Hinterer Saum Hang",
  "backHemSlope.d": "Steuert den Hang des Saum auf der Rückseite",
  "frontShoulderWidth.t": "Vordere Schulterbreite",
  "frontShoulderWidth.d": "Steuert die Schmalheit der vorderen Schultern relativ zum Rücken",
  "highBustWidth.t": "Oberbrustweite",
  "highBustWidth.d": "Erlaubt es dir die Oberbrustweite vorne zu optimieren"
}

export default o_bella
