/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bob = {
  "neckRatio.t": "Neck opening",
  "neckRatio.d": "Controls the size of the neck opening relative to the bib size",
  "widthRatio.t": "Width",
  "widthRatio.d": "Controls the width of the bib",
  "lengthRatio.t": "Length",
  "lengthRatio.d": "Controls the length of the bib",
  "headSize.t": "Head size",
  "headSize.d": "The head circumference you want the bib to accomodate"
}

export default o_bob
