/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_breanna = {
  "shoulderDart.t": "Schulterabnäher",
  "shoulderDart.d": "Ob ein Abnäher an der Schulter zur Abrundung des Rückens hinzugefügt werden soll oder nicht",
  "shoulderDartSize.t": "Größe der Schulterabnäher",
  "shoulderDartSize.d": "Größe des Schulterabnähers",
  "shoulderDartLength.t": "Länge des Schulterabnähers",
  "shoulderDartLength.d": "Die Länge des Abnähers an der Schulter",
  "waistDart.t": "Taillenabnäher",
  "waistDart.d": "Ob ein Abnäher an der Taille zur Abrundung des Rückens hinzugefügt werden soll oder nicht",
  "waistDartSize.t": "Größe des Taillenabnähers",
  "waistDartSize.d": "Die Größe des Abnähers an der Taille",
  "waistDartLength.t": "Länge des Taillenabnähers",
  "waistDartLength.d": "Die Länge des Abnähers an der Taille",
  "verticalEase.t": "Vertikale Zugabe",
  "verticalEase.d": "Die Menge an Zugabe, die über die Länge des Kleidungsstückes verteilt wird",
  "waistEase.t": "Taillenzugabe",
  "waistEase.d": "Die Menge an Bequemlichkeits-/Bewegungszugabe an der Taille",
  "primaryBustDart.t": "Brustabnäher",
  "primaryBustDart.d": "Wo der Büstendart platziert wird, um die Brust zu formen",
  "primaryBustDartLength.t": "Länge des Brustabnähers",
  "primaryBustDartLength.d": "Die Länge des Abnähers an der Brust",
  "secondaryBustDart.t": "Sekundärer Brustabnäher",
  "secondaryBustDart.d": "Optional einen sekundären Büstendart zur Verteilung der Form der Brust",
  "secondaryBustDartLength.t": "Länge des sekundären Brustabnähers",
  "secondaryBustDartLength.d": "Die Länge des sekundären Abnähers an der Brust",
  "primaryBustDartShaping.t": "Formgebung der Brustabnäher",
  "primaryBustDartShaping.d": "Steuert die Balance zwischen den sekundären und den Hauptbrustabnähern"
}

export default o_breanna
