/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_bruce = {
  "bulge.t": "Wölbung",
  "bulge.d": "Vergrößert den Winkel, um mehr Platz in der vorderen Tasche zu schaffen.",
  "legBonus.t": "Beinlängen-Bonus",
  "legBonus.d": "Zusätzliche Länge für die Beine.",
  "rise.t": "Anstieg",
  "rise.d": "Betrag, um den die Taille angehoben wird. Ein negativer Wert senkt sie ab.",
  "stretch.t": "Dehnung",
  "stretch.d": "Die Menge an negativer Bewegungszugabe.",
  "legStretch.t": "Bein Dehnung",
  "legStretch.d": "Das beste Ergebnis erzielst du, wenn du den Sitz der Beine etwas enger machst — Sag Nein zu klaffenden Lücken.",
  "backRise.t": "Hintere Anstieg",
  "backRise.d": "Betrag, um den die Taille hinten angehoben wird."
}

export default o_bruce
