/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cathrin = {
  "panels.t": "Anzahl der Schnittteile",
  "panels.d": "Die Anzahl der zu erstellenden Schnittteile. Mehr Schnittteile passen kurvenreicheren Modellen besser.",
  "waistReduction.t": "Taillenreduzierung",
  "waistReduction.d": "Der Betrag, um den das Korsett deine Taille einschnüren soll.",
  "backOpening.t": "Hintere Öffnung",
  "backOpening.d": "Öffnung in der hinteren Mitte",
  "backRise.t": "Anstieg hinten",
  "backRise.d": "Wie stark sich die hinteren Schnittteile von den Armen bis zur hinteren Mitte erstrecken.",
  "backDrop.t": "Rückenabsenkung",
  "backDrop.d": "Wie weit sich die hinteren Schnittteile von den Hüften in Richtung Rückenmitte absenken. Negative Werte heben den Rücken an.",
  "frontRise.t": "Frontanstieg",
  "frontRise.d": "Aufstieg der Frontteile in der Mitte zwischen den Brüsten. Negative Werte verringern sie.",
  "frontDrop.t": "Frontabsenkung",
  "frontDrop.d": "Wie weit sich die Frontteile von Ihrer Hüfte in Richtung Ihrer Mittelfront absenken.",
  "hipRise.t": "Hüftanstieg",
  "hipRise.d": "Wie stark die Seitenteile auf den Hüften stehen."
}

export default o_cathrin
