/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlita = {
  "contour.t": "Kontur",
  "contour.d": "Legt fest, wie stark figurbetont die Wiener Nähte sind."
}

export default o_carlita
