/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_carlton = {
  "seatEase.t": "Hüftzugabe",
  "seatEase.d": "Menge an Bequemlichkeits-/Bewegungszugabe an deinem Hintern",
  "pocketPlacementHorizontal.t": "Horizontale Taschenplatzierung",
  "pocketPlacementHorizontal.d": "Die (horizontale) Position der Taschen",
  "pocketPlacementVertical.t": "Vertikale Taschenplatzierung",
  "pocketPlacementVertical.d": "Die (vertikale) Position der Taschen",
  "collarHeight.t": "Kragenhöhe",
  "collarHeight.d": "Höhe des Kragens",
  "length.t": "Länge",
  "length.d": "Gesamtlänge",
  "pocketFlapRadius.t": "Taschenlaschenradius",
  "pocketFlapRadius.d": "Der Betrag, um den die Taschenlasche abgerundet ist",
  "pocketRadius.t": "Taschenradius",
  "pocketRadius.d": "Der Betrag, um den die Tasche abgerundet ist",
  "chestPocketHeight.t": "Brusttaschenhöhe",
  "chestPocketHeight.d": "Höhe der Brusttasche",
  "beltWidth.t": "Gürteilbreite",
  "beltWidth.d": "Breite des Gürtels",
  "buttonSpacingHorizontal.t": "Horizontaler Knopfabstand",
  "buttonSpacingHorizontal.d": "Horizontaler Abstand der Knöpfe, bestimmt auch den Übertritt des vorderen Verschlusses"
}

export default o_carlton
