/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_charlie = {
  "backPocketHorizontalPlacement.t": "Horizontale Platzierung der hinteren Tasche",
  "backPocketHorizontalPlacement.d": "Steuert die horizontale Platzierung der hinteren Tasche",
  "backPocketVerticalPlacement.t": "Vertikale Platzierung der hinteren Tasche",
  "backPocketVerticalPlacement.d": "Steuert die vertikale Platzierung der hinteren Tasche",
  "backPocketWidth.t": "Breite der hinteren Tasche",
  "backPocketWidth.d": "Steuert die Breite der hinteren Tasche",
  "backPocketDepth.t": "Tiefe der hinteren Tasche",
  "backPocketDepth.d": "Steuert die Tiefe der hinteren Tasche",
  "backPocketFacing.t": "Back pocket facing",
  "backPocketFacing.d": "Controls whether or not to include facing on the back pockets",
  "frontPocketSlantDepth.t": "Vordertasche Schrägtiefe",
  "frontPocketSlantDepth.d": "Steuert die Tiefe des (vorder) Taschenschlitzes",
  "frontPocketSlantWidth.t": "Fronttasche Schrägbreite",
  "frontPocketSlantWidth.d": "Steuert die Breite des (vorder) Taschenschlitzes",
  "frontPocketSlantRound.t": "Vordertaschenschlitzrunde",
  "frontPocketSlantRound.d": "Stellt fest, wie weit wir vom Ende der Schrägheit entfernt anfangen in das Aussennaht zu runden",
  "frontPocketSlantBend.t": "Vordertaschenschräg Biegen",
  "frontPocketSlantBend.d": "Steuert den Radius, mit dem wir die Taschenschiebung in die Außennaht umdrehen",
  "frontPocketWidth.t": "Breite der Fronttasche",
  "frontPocketWidth.d": "Steuert die Breite der Vordertasche",
  "frontPocketDepth.t": "Tiefe der Vordertasche",
  "frontPocketDepth.d": "Steuert die Tiefe der Vordertasche",
  "frontPocketFacing.t": "Fronttasche",
  "frontPocketFacing.d": "Legt fest, wie weit die Tasche in die Tasche hineinreicht",
  "beltLoops.t": "Gürtelschlaufen",
  "beltLoops.d": "Steuert die Anzahl der Gürtelschlaufen",
  "flyCurve.t": "Flugkurve",
  "flyCurve.d": "Steuert die Krümmung der Fliege J-Naht",
  "flyLength.t": "Fluglänge",
  "flyLength.d": "Steuert die Länge der Fliege",
  "flyWidth.t": "Fly width",
  "flyWidth.d": "Bestimmt, wie weit die J-Naht-Versatz vom Fliegenrand entfernt ist",
  "waistbandCurve.t": "Taillenband Kurve",
  "waistbandCurve.d": "Steuert die Kurven der Taille."
}

export default o_charlie
