/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_cornelius = {
  "fullness.t": "Fülle",
  "fullness.d": "Steuert die Fülle der Hosen",
  "waistbandBelowWaist.t": "Unterer Taillenband",
  "waistbandBelowWaist.d": "Prozentsatz um die Taille unter die aktuelle Taille zu bewegen",
  "waistReduction.t": "Taillenreduzierung",
  "waistReduction.d": "Prozentsatz um die Taille zu reduzieren",
  "cuffWidth.t": "Cuff width",
  "cuffWidth.d": "Breite der Beinschicht",
  "cuffStyle.t": "Manschettenstil",
  "cuffStyle.d": "Stil der Beinmanschette",
  "bandBelowKnee.t": "Kuff unter dem Knie",
  "bandBelowKnee.d": "Steuert die Manschettendistanz vom Knie",
  "kneeToBelow.t": "Manschettenlänge",
  "kneeToBelow.d": "Steuert die Dichtheit der Manschette im Vergleich zum Knie",
  "ventLength.t": "Ventillänge",
  "ventLength.d": "Steuert die Länge des Schlot zwischen Knie und Manschette"
}

export default o_cornelius
