/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_diana = {
  "shoulderSeamLength.t": "Schulternahtlänge",
  "shoulderSeamLength.d": "Steuert die Länge der Schulternaht",
  "drapeAngle.t": "Fallwinkel",
  "drapeAngle.d": "Steuert die Stärke des Fallwinkels"
}

export default o_diana
