/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florent = {
  "headEase.t": "Kopfumfangszugabe",
  "headEase.d": "Bequemlichkeits-/Bewegungszugabe zum Umfang deines Kopfes"
}

export default o_florent
