/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_florence = {
  "height.t": "Höhe",
  "height.d": "Steuert die Höhe der Gesichtsmaske",
  "length.t": "Länge",
  "length.d": "Steuert die Länge der Gesichtsmaske",
  "curve.t": "Krümmung",
  "curve.d": "Steuert die Krümmung der oberen Kante der Gesichtsmaske"
}

export default o_florence
