/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hortensia = {
  "size.t": "Grösse",
  "size.d": "Steuert die Gesamtgröße der Handtasche",
  "zipperSize.t": "Größe des Reißverschlusses",
  "zipperSize.d": "Welche Reißverschlussgröße verwendet werden soll",
  "strapLength.t": "Riemenlänge",
  "strapLength.d": "Steuert die Riemenlänge",
  "handleWidth.t": "Breite des Griffes",
  "handleWidth.d": "Steuert die Breite des Griffes"
}

export default o_hortensia
