/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_holmes = {
  "headEase.t": "Kopfumfangszugabe",
  "headEase.d": "Bequemlichkeits-/Bewegungszugabe zum Umfang deines Kopfes.",
  "lengthRatio.t": "Längenverhältnis",
  "lengthRatio.d": "Controls the length of the crown and ear flaps",
  "gores.t": "Number of gores",
  "gores.d": "The number of gores used to construct the crown",
  "visorAngle.t": "Visor angle",
  "visorAngle.d": "The arc angle used to draft the inner curve of the visor",
  "visorWidth.t": "Visor width",
  "visorWidth.d": "Controls the width of the visor",
  "earLength.t": "Ear flap length",
  "earLength.d": "Controls the length of the ear flaps independently from the crown pieces",
  "earWidth.t": "Ear flap width",
  "earWidth.d": "Controls the width of the ear flaps",
  "buttonhole.t": "Buttonhole guide",
  "buttonhole.d": "Adds a buttonhole to the ear flap to help you draft the buttonhole ear flap variant",
  "visorLength.t": "Visor length",
  "visorLength.d": "Controls the length of the visor"
}

export default o_holmes
