/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_holmes = {
  "headEase.t": "Kopfumfangszugabe",
  "headEase.d": "Bequemlichkeits-/Bewegungszugabe zum Umfang deines Kopfes.",
  "lengthRatio.t": "Längenverhältnis",
  "lengthRatio.d": "Kontrolliert die Länge der Hutkrone und Ohrklappen",
  "gores.t": "Anzahl der Keile",
  "gores.d": "Anzahl der Keile, die die Hutkrone zu bilden",
  "visorAngle.t": "Winkel des Mützenschirms",
  "visorAngle.d": "Winkel, der die innere Kurve des Mützenschirms beschreibt",
  "visorWidth.t": "Breite des Mützenschirms",
  "visorWidth.d": "Steuert die Breite des Mützenschirms",
  "earLength.t": "Länge der Ohrklappen",
  "earLength.d": "Steuert die Länge der Ohrklappen unabhängig von den Kronenstücken",
  "earWidth.t": "Breite der Ohrklappen",
  "earWidth.d": "Steuert die Breite der Ohrklappen",
  "buttonhole.t": "Führung für das Knopfloch",
  "buttonhole.d": "Fügt der Ohrklappe einen Knopfloch hinzu, um die Variante mit Knopflochs zu entwerfen",
  "visorLength.t": "Länge des Mützenschirmes",
  "visorLength.d": "Steuert die Länge des Mützenschirms"
}

export default o_holmes
