/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_hugo = {
  "hipsEase.t": "Zugabe Hüfte",
  "hipsEase.d": "Die Menge an Bequemlichkeitszugabe an deinen Hüften."
}

export default o_hugo
