/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_huey = {
  "pocket.t": "Tasche",
  "pocket.d": "Legt fest, ob vordere Taschen integriert werden oder nicht",
  "pocketHeight.t": "Taschenhöhe",
  "pocketHeight.d": "Steuert die Höhe der Tasche",
  "hoodHeight.t": "Kapuzenhöhe",
  "hoodHeight.d": "Steuert die Höhe der Kapuze",
  "hoodCutback.t": "Kapuzenausschnitt",
  "hoodCutback.d": "Leg fest, wie weit die Öffnung der Kapuze zurückgeschnitten wird",
  "hoodClosure.t": "Kapuzenverschluss",
  "hoodClosure.d": "Legt fest, wie viel von der der Kapuze zum vorderen Verschluss gehört",
  "hoodDepth.t": "Kapuzentiefe",
  "hoodDepth.d": "Steuert die Tiefe der Kapuze",
  "hoodAngle.t": "Winkel der Kapuze",
  "hoodAngle.d": "Steuert den Winkel, mit welchem die Kapuze angebracht wird"
}

export default o_huey
