/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_lunetius = {
  "lengthRatio.t": "Längenverhältnis",
  "lengthRatio.d": "Steuert die Länge des Kleidungsstückes",
  "widthRatio.t": "Breitenverhältnis",
  "widthRatio.d": "Steuert die Breite des Kleidungsstückes",
  "length.t": "Länge",
  "length.d": "Choose from the different length styles"
}

export default o_lunetius
