/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_octoplushy = {
  "size.t": "Size",
  "size.d": "Controls the overall size",
  "type.t": "Type",
  "type.d": "Allows you to choose one of the variants of this design",
  "armWidth.t": "Arm width",
  "armWidth.d": "Controls the width of the arms",
  "armLength.t": "Arm width",
  "armLength.d": "Controls the length of the arms",
  "neckWidth.t": "Neck width",
  "neckWidth.d": "Determines the width at the neck",
  "armTaper.t": "Arm tapering",
  "armTaper.d": "Controls the amount by which the arms taper",
  "bottomTopArmRatio.t": "Bottom/Top arm ratio",
  "bottomTopArmRatio.d": "FIXME: No idea what this does",
  "bottomArmReduction.t": "Bottom arm reduction",
  "bottomArmReduction.d": "FIXME: No idea what this does",
  "bottomArmReductionPlushy.t": "Bottom arm reduction (plushy)",
  "bottomArmReductionPlushy.d": "FIXME: No idea what this does"
}

export default o_octoplushy
