/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_paco = {
  "heelEase.t": "Bequemlichkeitszugabe Ferse",
  "heelEase.d": "Größe der Bequemlichkeitszugabe an der Ferse (wenn man in das Hosenbein hineinsteigt)",
  "frontPockets.t": "Vordere Taschen",
  "frontPockets.d": "Ob vordere Taschen an der Seitennaht hinzugefügt werden sollen oder nicht",
  "backPockets.t": "Gesäßtaschen",
  "backPockets.d": "Hinzufügen einer Kedertasche zur Rückseite oder nicht",
  "elasticatedHem.t": "Elastischer Saum",
  "elasticatedHem.d": "Ob ein elastischer Saum gewünscht ist oder nicht",
  "ankleElastic.t": "Knöchel/Saum Gummizugbreite",
  "ankleElastic.d": "Breite des (optionalen) Gummizugs am Knöchel/Saum"
}

export default o_paco
