/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_penelope = {
  "backDartDepthFactor.t": "Zurück zum Abnäherinhalttiefenfaktor",
  "backDartDepthFactor.d": "Wie weit der rückwärtige Abnäher vom Taillenbund nach unten geht. Dies ist ein Faktor des Abstandes von der natürlichen Taille bis zum Gesäßumfang.",
  "backVent.t": "Hinterlüftung",
  "backVent.d": "Fügt einen Bewegungschlitz hinten am Rock hinzu.",
  "backVentLength.t": "Rückenlüftungslänge",
  "backVentLength.d": "Die Länge des Bewegungschlitzes hinten als ein Prozentsatz der Gesamtrocklänge.",
  "dartToSideSeamFactor.t": "Abnäher zu Seitennaht Faktor",
  "dartToSideSeamFactor.d": "Prozentuales Verhältnis wieviel der Reduktion von der Hüftweite zur Taille über die Abnäher und wieviel über die Seitennäht erzielt wurde.",
  "frontDartDepthFactor.t": "Vorderer Abnäherinhälttiefenfaktor",
  "frontDartDepthFactor.d": "Wie weit nach unten der vordere Abnäher von der Taillenlinie geht. Dies ist ein Faktor des Maßes von der natürlichen Taille zum Gesäßumfang.",
  "hem.t": "Höhe des Saumes",
  "hem.d": "Breite des Saumes. Maß in absoluten Werten angeben.",
  "hemBonus.t": "Saumzugabe",
  "hemBonus.d": "Diese Option reduziert die Saumweite. Sie ist ein prozentualer Anteil des Gesäßumfangs.",
  "lengthBonus.t": "Längenbonus",
  "lengthBonus.d": "Dies legt Länge des Rockes fest. Es ist einem Prozentsatz des Abstands natürliche Taille zu Knie definiert.",
  "nrOfDarts.t": "Anzahl Abnäher",
  "nrOfDarts.d": "Die Anzahl der Abnäher, die in dem Schnittmuster verwendet werden. Das Maximum ist 2. Dies kann reduziert werden, wenn das Schnittmuster zu kleine Abnäher erstellt.",
  "seatEase.t": "Zugabe Gesäß",
  "seatEase.d": "Zugegebene Weite auf Höhe des Gesäßs.",
  "waistBand.t": "Taillenbund",
  "waistBand.d": "Füge einen Taillenbund zum Schnittmuster hinzu.",
  "waistBandWidth.t": "Breite des Taillenbundes",
  "waistBandWidth.d": "Die Breite des Taillenbundes.",
  "waistEase.t": "Taille erleichtert",
  "waistEase.d": "Zugegebene Weite auf Taillenhöhe.",
  "zipperLocation.t": "Platzierung Reißverschluss",
  "zipperLocation.d": "Platzierung des Reißverschlusses."
}

export default o_penelope
