/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sandy = {
  "waistbandWidth.t": "Taillenbundweite",
  "waistbandWidth.d": "Kontrolliert die Weite des Taillenbundes.",
  "waistbandPosition.t": "Position des Taillenbundes",
  "waistbandPosition.d": "Legt die Position des Taillenbundes fest.",
  "waistbandShape.t": "Taillenbundform",
  "waistbandShape.d": "Hier stellen Sie ein, on sie einen geraden oder einen körpergeformten Bund wollen.",
  "circleRatio.t": "Kreisverhältnis",
  "circleRatio.d": "Die Prozente eines Kreises aus dem Sie den Rock erstellen möchten.",
  "waistbandOverlap.t": "Überlappung des Taillenbundes",
  "waistbandOverlap.d": "Der Betrag, mit dem sich der Taillenbund überlappt.",
  "gathering.t": "Kräuseln",
  "gathering.d": "Der Prozentsatz um welcher die Oberkante des Rockteils länger ist als die Unterkante des Bundes.",
  "seamlessFullCircle.t": "Nahtloser Vollkreis",
  "seamlessFullCircle.d": "Aktiviert einen nahtlosen Vollkreis für das Rockteil.",
  "hemWidth.t": "Saumbreite",
  "hemWidth.d": "Breite des Saumes"
}

export default o_sandy
