/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_shin = {
  "legReduction.t": "Verjüngung am Bein",
  "legReduction.d": "Reduziert die Hosenbeinöffnung um Anstehen zu verhindern",
  "elasticWidth.t": "Breite des Gummis",
  "elasticWidth.d": "Breite des Gummizugs an der Taille"
}

export default o_shin
