/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_simone = {
  "bustDartAngle.t": "Winkel des Brustabnähers",
  "bustDartAngle.d": "Kontrolliert den Winkel, in welchem der (seitliche) Brustabnäher sich nach unten neigt",
  "bustDartLength.t": "Länge des Brustabnähers",
  "bustDartLength.d": "Regelt, wie nahe der Brustabnäher an den Brustpunkt kommt",
  "contour.t": "Kontur",
  "contour.d": "Legt fest, wie eng anliegend der Schnitt unterhalb der Brust gestaltet wird",
  "frontDarts.t": "Vordere Abnäher",
  "frontDarts.d": "Legt fest, ob vordere Abnäher im Schnitt eingearbeitet werden sollen",
  "frontDartLength.t": "Länge der vorderen Abnäher",
  "frontDartLength.d": "Legt fest, wie nahe die vorderen Abnäher an den Brustpunkt heranreichen"
}

export default o_simone
