/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_sven = {
  "hipsEase.t": "Zugabe Hüfte",
  "hipsEase.d": "Steuert die Menge an Zugabe an deinen Hüften (am unteren Ende des Pullovers)",
  "ribbing.t": "Bündchen",
  "ribbing.d": "Ob Saum und Manschetten mit Bündchen abschließen oder nicht.",
  "ribbingHeight.t": "Bündchen-Höhe",
  "ribbingHeight.d": "Die Höhe der Bündchen",
  "ribbingStretch.t": "Bündchen-Elastizität",
  "ribbingStretch.d": "Die Menge an negativer Zugabe für die an Manschetten und Saum verwendeten Bündchen."
}

export default o_sven
