/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tamiko = {
  "flare.t": "Ausstellen",
  "flare.d": "Die Menge, um die sich das Kleidungsstück von der Brust nach unten ausgestellt wird",
  "shoulderseamLength.t": "Schulternahtlänge",
  "shoulderseamLength.d": "Die Länge der Schulternaht als Faktor deines Schulter-zu-Schulter-Maßes",
  "shoulderSlope.t": "Schulterneigung",
  "shoulderSlope.d": "Steuert den Winkel der Schulternähte"
}

export default o_tamiko
