/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_teagan = {
  "draftForHighBust.t": "Entwurf für hohe Büste",
  "draftForHighBust.d": "Zeichnen Sie das Muster für die hohe Büstenmessung (falls vorhanden) statt der (vollen) Truhe. Dies wird zu einem besser angepassten Kleidungsstück für Brustkleidung führen.",
  "sleeveEase.t": "Bequemlichkeitszugabe Ärmel",
  "sleeveEase.d": "Größe der Bequemlichkeitszugabe an den Ärmeln",
  "sleeveLength.t": "Ärmellänge",
  "sleeveLength.d": "Steuert die Länge deiner Ärmel",
  "necklineBend.t": "Krümmung Halsausschnitt",
  "necklineBend.d": "Steuert die Krümmung des Halsausschnitts.",
  "necklineDepth.t": "Ausschnitttiefe",
  "necklineDepth.d": "Steuert, wie tief der Halsausschnitt fällt.",
  "necklineWidth.t": "Ausschnittbreite",
  "necklineWidth.d": "Steuert die Breite des Halsausschnitts."
}

export default o_teagan
