/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_theo = {
  "wedge.t": "Keil",
  "wedge.d": "Steuert die Länge der Kreuznaht",
  "legWidth.t": "Beinweite",
  "legWidth.d": "Legt die Weite des Hosenbeins fest"
}

export default o_theo
