/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_titan = {
  "kneeEase.t": "Knie-Zugabe",
  "kneeEase.d": "Kontrolliert die Zugabe am Knie",
  "waistHeight.t": "Taillenhöhe",
  "waistHeight.d": "Steuert die Höhe des Taillenbundes, 100% = Taillenhöhe, 0% = Hüfthöhe",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Steuert die Länge der Hose",
  "crotchDrop.t": "Schritt-Tiefe",
  "crotchDrop.d": "Senkt die Schrittiefe für mehr Tragekomfort",
  "fitKnee.t": "Am Knie anliegend",
  "fitKnee.d": "Legt die Bein-Passform auf Grundlage des Knieumfangst statt des Gesäßumfangs fest",
  "legBalance.t": "Bein-Balance",
  "legBalance.d": "Steuert das Verhältnis zwischen Vorder- und Hinterteil des Beins",
  "crossSeamCurveStart.t": "Start der Quernahtkurve",
  "crossSeamCurveStart.d": "Bestimmt, wie weit wir in die Quernaht hineinspringen und kurven",
  "crossSeamCurveBend.t": "Quernaht Kurve",
  "crossSeamCurveBend.d": "Steuert die Krümmung der Kreuznaht",
  "crossSeamCurveAngle.t": "Quernaht Winkel",
  "crossSeamCurveAngle.d": "Steuert den Winkel der Quernaht",
  "crotchSeamCurveStart.t": "Beginn der Schrittnahtkurve",
  "crotchSeamCurveStart.d": "Legt fest, wie weit wir in die Schrittnaht hineinfahren",
  "crotchSeamCurveBend.t": "Crotch Naht Biegen",
  "crotchSeamCurveBend.d": "Steuert die Krümmung der Schrittnaht",
  "crotchSeamCurveAngle.t": "Schneckennaht Winkel",
  "crotchSeamCurveAngle.d": "Steuert den Winkel der Schrittnaht",
  "waistBalance.t": "Taillenbilanz",
  "waistBalance.d": "Steuert die horizontale Position der Taille relativ zum Sitz",
  "waistbandWidth.t": "Taillenbundweite",
  "waistbandWidth.d": "Die Breite des Taillenbundes",
  "grainlinePosition.t": "Position Fadenlauf",
  "grainlinePosition.d": "Steuert die horizontale Position des Beins relativ zum Sitz"
}

export default o_titan
