/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tiberius = {
  "headRatio.t": "Kopfgrößenverhältnis",
  "headRatio.d": "Steuert die Größe der Kopföffnung",
  "armholeDrop.t": "Armlochabsenkung",
  "armholeDrop.d": "Steuert die Tiefe des Armloches",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Erlaubt Variation der Länge des Kleidungsstücks",
  "widthBonus.t": "Breitenzugabe",
  "widthBonus.d": "Erlaubt Variation der Breite des Kleidungsstücks",
  "clavi.t": "Clavi",
  "clavi.d": "Legt fest, ob Hilfslinien für Clavi enthalten sind oder nicht",
  "clavusLocation.t": "Positionierung der Clavi",
  "clavusLocation.d": "Steuert die Position der Clavi",
  "clavusWidth.t": "Breite der Clavi",
  "clavusWidth.d": "Steuert die Breite der Clavi",
  "length.t": "Länge",
  "length.d": "Steuert die Länge des Kleidungsstückes",
  "width.t": "Breite",
  "width.d": "Steuert die Breite des Kleidungsstückes",
  "forceWidth.t": "Breite erzwingen",
  "forceWidth.d": "Breiteneinstellungen unabhängig von Einschränkungen anwenden"
}

export default o_tiberius
