/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_tiberius = {
  "headRatio.t": "Head ratio",
  "headRatio.d": "Controls the size of the head opening",
  "armholeDrop.t": "Armlochabsenkung",
  "armholeDrop.d": "Steuert die Tiefe des Armloches",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Allows variation of the length of the garment",
  "widthBonus.t": "Breitenzugabe",
  "widthBonus.d": "Allows variation of the width of the garment",
  "clavi.t": "Clavi",
  "clavi.d": "Whether or not to include guides for clavi",
  "clavusLocation.t": "Clavus location",
  "clavusLocation.d": "Controls the location of the clavi",
  "clavusWidth.t": "Clavus width",
  "clavusWidth.d": "Controls the width of the clavi",
  "length.t": "Länge",
  "length.d": "Steuert die Länge des Kleidungsstückes",
  "width.t": "Breite",
  "width.d": "Steuert die Breite des Kleidungsstückes",
  "forceWidth.t": "Breite erzwingen",
  "forceWidth.d": "Breiteneinstellungen unabhängig von Einschränkungen anwenden"
}

export default o_tiberius
