/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_trayvon = {
  "tipWidth.t": "Spitzenbreite",
  "tipWidth.d": "Die Breite deiner Krawatte an der Spitze",
  "knotWidth.t": "Knotenbreite",
  "knotWidth.d": "Die Breite deiner Krawatte am Knoten"
}

export default o_trayvon
