/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_ursula = {
  "fabricStretch.t": "Stoffdehnbarkeit",
  "fabricStretch.d": "Passe dies für mehr oder weniger dehnbaren Stoff an",
  "gussetWidth.t": "Zwickelbreite",
  "gussetWidth.d": "Steuert die Breite des Zwickels",
  "gussetLength.t": "Zwickellänge",
  "gussetLength.d": "Steuert die Länge des Zwickels",
  "elasticStretch.t": "Dehnbarkeit des Gummis",
  "elasticStretch.d": "Passe dies für mehr oder weniger dehnbaren Gummi an",
  "rise.t": "Sitz",
  "rise.d": "Steuert die Höhe der Taille",
  "legOpening.t": "Beinöffnung",
  "legOpening.d": "Legt fest, wie hoch das Bein ausgeschnitten wird",
  "frontDip.t": "Absenkung der vorderen Taille",
  "frontDip.d": "Steuert, wie stark die vordere Taille gekümmt ist (legt dadurch mehr oder weniger Haut frei)",
  "backDip.t": "Absenkung hintere Taille",
  "backDip.d": "Steuert, wie stark die hintere Taille gekümmt ist (legt dadurch mehr oder weniger Haut frei)",
  "taperToGusset.t": "Vordere Freilegung",
  "taperToGusset.d": "Steuert die Menge an freigelegter Haut auf der vorderen Seite",
  "backExposure.t": "Hintere Freilegung",
  "backExposure.d": "Steuert die Menge an freigelegter Haut auf der hinteren Seite"
}

export default o_ursula
