/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_walburga = {
  "headRatio.t": "Head ratio",
  "headRatio.d": "Controls the size of the head opening",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Allows variation of the length of the garment",
  "widthBonus.t": "Breitenzugabe",
  "widthBonus.d": "Allows variation of the width of the garment",
  "length.t": "Länge",
  "length.d": "Steuert die Länge des Kleidungsstückes",
  "neckoRatio.t": "Neck opening shape",
  "neckoRatio.d": "controls the shape of the neck opening",
  "neckline.t": "Neckline",
  "neckline.d": "Controls whether or not to draft a neck opening"
}

export default o_walburga
