/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_wahid = {
  "backScyeDart.t": "Rückwärtige Armlochabnäher",
  "backScyeDart.d": "Die Menge, die in einem Abnäher hinten am Armloch entnommen werden muss.",
  "frontScyeDart.t": "Vorderer Armlochabnäher",
  "frontScyeDart.d": "Die Menge, die in einem Abnäher an der Vorderseite des Armlochs entnommen werden muss.",
  "pocketLocation.t": "Taschenplatzierung",
  "pocketLocation.d": "Bestimmt die Platzierung der Tasche",
  "pocketWidth.t": "Taschenbreite",
  "pocketWidth.d": "Bestimmt die Breite der Tasche",
  "weltHeight.t": "Paspelhöhe",
  "weltHeight.d": "Bestimmt die Höhe der Paspel",
  "necklineDrop.t": "Ausschnitt Tiefe",
  "necklineDrop.d": "Legt fest, wie tief der Ausschnitt vorne ausgeschnitten ist",
  "frontStyle.t": "Ausschnittstil",
  "frontStyle.d": "Stil des Ausschnitts",
  "hemStyle.t": "Saumstil",
  "hemStyle.d": "Art des vorderen Saums",
  "hemRadius.t": "Saumradius",
  "hemRadius.d": "Der Betrag, um den der Saum gerundet ist",
  "backInset.t": "Rückseite Ausschnitt",
  "backInset.d": "Wie viel die Rückseite des Armlochs nach innen verschoben ist",
  "frontInset.t": "Vorderseite Ausschnitt",
  "frontInset.d": "Wieviel das Armloch an der Vorderseite nach innen verschoben wird",
  "shoulderInset.t": "Schulterversatz nach innen",
  "shoulderInset.d": "Wieviel die Schulternaht nach innen Richtung Schulter versetzt wird",
  "neckInset.t": "Nackenauschnitt",
  "neckInset.d": "Wieviel die Schulternaht am Nacken nach innen versetzt wird",
  "pocketAngle.t": "Winkel der Tasche",
  "pocketAngle.d": "Winkel der Taschenneigung"
}

export default o_wahid
