/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const o_walburga = {
  "headRatio.t": "Kopfgrößenverhältnis",
  "headRatio.d": "Steuert die Größe der Kopföffnung",
  "lengthBonus.t": "Längenzugabe",
  "lengthBonus.d": "Erlaubt Variation der Länge des Kleidungsstücks",
  "widthBonus.t": "Breitenzugabe",
  "widthBonus.d": "Erlaubt Variation der Breite des Kleidungsstücks",
  "length.t": "Länge",
  "length.d": "Steuert die Länge des Kleidungsstückes",
  "neckoRatio.t": "Form des Halsausschnittes",
  "neckoRatio.d": "Steuert die Form des Halsausschnittes",
  "neckline.t": "Halsausschnitt",
  "neckline.d": "Bestimmt, ob ein Halsausschnit erstellt werden soll oder nicht"
}

export default o_walburga
