/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const optiongroups = {
  "advanced": "Fortgeschritten",
  "armhole": "Armloch",
  "closure": "Verschluss",
  "collar": "Kragen",
  "construction": "Konstruktion",
  "cuffs": "Manschetten",
  "darts": "Abnäher",
  "elastic": "Gummi",
  "fit": "Passform",
  "pockets": "Taschen",
  "preferences": "Einstellungen",
  "sleevecap": "Armkugel",
  "sleeves": "Ärmel",
  "style": "Stil",
  "backPockets": "Gesäßtaschen",
  "frontPockets": "Vordere Taschen",
  "waistband": "Bund",
  "fly": "Hosenstall",
  "bellaDarts": "Bella darts",
  "bellaArmhole": "Bella armhole",
  "bellaAdvanced": "Bella advanced",
  "clavi": "Clavi"
}

export default optiongroups
