/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const patrons = {
  "becomeAPatron": "Förderer/in werden",
  "supportFreesewing": "Unterstütze FreeSewing"
}

export default patrons
