/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const settings = {
  "advanced.t": "Expertenmodus",
  "advanced.d": "Legt fest, ob erweiterte Einstellungen und Schnittmusteroptionen angezeigt werden sollen oder nicht",
  "paperless.t": "Papierlos",
  "paperless.d": "Zeichnet ein Schnittmuster mit allen benötigten Dimensionen, sodass es direkt auf den Stoff oder ein anderes Medium übertragen werden kann, ohne es auszudrucken",
  "sa.t": "Nahtzugabe",
  "sa.d": "Steuert die Breite der Nahtzugabe, die in deinem Schnittmuster enthalten ist",
  "locale.t": "Sprache",
  "locale.d": "Legt die für deine Schnittmuster verwendete Sprache fest",
  "only.t": "Inhalte",
  "only.d": "Damit kannst du genau festlegen, welche Teile des Schnittmusters auf deinem Schnittmusterbogen erscheinen",
  "units.t": "Maßeinheiten",
  "units.d": "Legt die in deinem Schnittmuster verwendete Maßeinheit fest",
  "margin.t": "Randabstand",
  "margin.d": "Legt den freien Rand um die einzelnen Teile des Schnittmusters fest",
  "complete.t": "Details",
  "complete.d": "Legt fest, wie detailliert das Schnittmuster dargestellt wird; entweder ein vollständiges Schnittmuster mit allen Details oder eine einfache Kontur der Schnittmusterteile",
  "layout.t": "Layout",
  "layout.d": "Legt fest, wie die einzelnen Teile auf deinem Schnittmusterbogen angeordnet werden",
  "debug.t": "Debug",
  "debug.d": "Debuggen aktivieren, um zusätzliche Informationen dazu zu erhalten, wie dein Schnittmuster erstellt wurde",
  "scale.t": "Beschriftungsgröße",
  "scale.d": "Steuert die allgemeine Linienbreite, Schriftgröße und andere Elementgrößen, \nbeeinflusst jedoch nicht den Maßstab des Schnittmusters selbst",
  "renderer.t": "Render engine",
  "renderer.d": "Controls how the pattern is rendered (drawn) on the screen",
  "xray.t": "X-ray",
  "xray.d": "Look under the hood with FreeSewing's X-ray mode"
}

export default settings
