/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const themes = {
  "lightTheme": "Helles Thema",
  "darkTheme": "Dunkles Thema",
  "hax0rTheme": "Hax0r Thema",
  "lgbtqTheme": "LGBTQ Thema",
  "transTheme": "Trans Thema"
}

export default themes
