/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
const welcome = {
  "units": "Wähle die Einheiten aus, die du verwenden möchtest",
  "username": "Wähle einen Benutzernamen",
  "avatar": "Profilbild hinzufügen",
  "bio": "Erzähle uns ein wenig über dich",
  "social": "Lass uns wissen, wo wir dir folgen können",
  "newsletter": "Teile uns deine Newsletter-Präferenz mit",
  "letUsSetupYourAccount": "Lass uns deinen Account einrichten.",
  "walkYouThrough": "Wir führen dich durch die folgenden Schritte:",
  "someOptional": "Obwohl alle diese Schritte optional sind, empfehlen wir dir sie durchzugehen, um das Beste aus FreeSewing herauszuholen."
}

export default welcome
