export default `
path,circle,rect{fill:none;stroke:none}
path{fill:none;stroke:#000;stroke-opacity:1;stroke-width:.3;stroke-linecap:round;stroke-linejoin:round}
path.fabric{stroke-width:.6;stroke:#653f95}
path.lining{stroke-width:.6;stroke:#0275d8}
path.interfacing{stroke-width:.6;stroke:#d9534f}
path.canvas{stroke-width:.6;stroke:#5cb85c}
path.various{stroke-width:.6;stroke:#5bc0de}
path.sa{stroke-dasharray:0.4,0.8}
path.help{stroke-width:.2;stroke-dasharray:15,1.5,1,1.5}
path.hint{stroke-width:.2;stroke-dasharray:0.4,0.8}
path.note{stroke:#0275d8;stroke-width:.6;marker-start:url(#noteArrow)}

text{font-size:5px;font-family:-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;fill:#000;
text-anchor:start;font-weight:200}
text.center{text-anchor:middle}
text.part-nr{font-size:28px;text-anchor:middle;fill:#000;font-weight:100}
text.part-nr.horizontal{text-anchor:start}
text.part-title{font-size:18px;text-anchor:middle;fill:#000}
text.part-title.horizontal{text-anchor:start}
text.pattern-title{font-size:8px;font-weight:bold;text-anchor:middle;fill:#000}
text.pattern-title.horizontal{text-anchor:start}
text.part-msg{font-size:10px;text-anchor:middle}
text.part-meta{font-size:7px;text-anchor:middle}
text.part-msg.horizontal,text.part-meta.horizontal,text.part-title.vertical,text.part-msg.vertical{text-anchor:start}
text.part-nr.small{font-size:14px}
text.part-title.small{font-size:9px}
text.pattern-title.small{font-size:4px}
text.part-msg.small{font-size:5px}
text.part-meta.small{font-size:5px}
text.part-nr.extrasmall{font-size:7px}
text.part-title.extrasmall{font-size:5px}
text.pattern-title.extrasmall{font-size:3px}
text.part-msg.extrasmall{font-size:4px}
text.part-meta.extrasmall{font-size:3px}
text.note,text.dimension-label{fill:#0275d8}
text.note tspan{alignment-baseline:middle}
text.note-5,text.note-6,text.note-7,text.note-11,text.note-12,text.note-0,text.note-1,text.dimension-label{text-anchor:middle}
text.note-8,text.note-9,text.note-10{text-anchor:end}
text.dimension-label{font-size:7px}
text.grainline{fill:#999}

path.arrow{stroke:#0275d8}
path.grainline{stroke:#999;stroke-width:.6;marker-start:url(#grainlineStart);marker-end:url(#grainlineEnd)}
path.dimension{stroke:#0275d8;stroke-width:.6;marker-start:url(#dimensionStart);marker-end:url(#dimensionEnd)}
path.dimension.dimension-sm{stroke-width:.3}
path.dimension-leader{stroke:#0275d8;stroke-width:.3}
path.single-arrow{marker-start:url(#dimensionStart)}
path.double-arrow{marker-start:url(#dimensionStart);marker-end:url(#dimensionEnd)}

.text-xs{font-size:3px}
.text-sm{font-size:4px}
.text-lg{font-size:7px}
.text-xl{font-size:9px}
.text-center{text-anchor:middle}
.stroke-xs{stroke-width:.1}
.stroke-sm{stroke-width:.2}
.stroke-lg{stroke-width:.6}
.stroke-xl{stroke-width:1}
.stroke-xxl{stroke-width:2}
.dashed{stroke-dasharray:1,1.5}
.lashed{stroke-dasharray:6,6}
.dotted{stroke-dasharray:0.4,0.8}
.hidden{stroke:none;file:none}
.stroke-fabric{stroke:#653f95}
.stroke-lining{stroke:#0275d8}
.stroke-interfacing{stroke:#d9534f}
.stroke-canvas{stroke:#5cb85c}
.stroke-note{stroke:#0275d8}
.stroke-mark{stroke:#f0ad4e}
.stroke-hint{stroke:#86739c}
.stroke-gray{stroke:#999}
.fill-fabric{fill:#653f95}
.fill-lining{fill:#0275d8}
.fill-interfacing{fill:#d9534f}
.fill-canvas{fill:#5cb85c}
.fill-note{fill:#0275d8}
.fill-mark{fill:#f0ad4e}
.fill-hint{fill:#86739c}
.fill-gray{fill:#999}
`;
