import { version } from '../package.json'
import { config as brianConfig } from '@freesewing/brian'

export default {
  version,
  name: 'huey',
  design: 'Joost De Cock',
  code: 'Joost De Cock',
  department: 'tops',
  type: 'pattern',
  difficulty: 3,
  optionGroups: {
    fit: [
      'bicepsEase',
      'chestEase',
      'cuffEase',
      'collarEase',
      'shoulderEase',
      'hipsEase',
      'ribbingStretch',
      'draftForHighBust',
    ],
    style: [
      'lengthBonus',
      'sleeveLengthBonus',
      'ribbing',
      'pocket',
      'ribbingHeight',
      'pocketHeight',
      'pocketWidth',
      'hoodHeight',
      'hoodCutback',
      'hoodClosure',
      'hoodDepth',
      'hoodAngle',
      's3Collar',
      's3Armhole',
    ],
    advanced: brianConfig.optionGroups.advanced,
  },
  measurements: [...brianConfig.measurements, 'head', 'hips'],
  optionalMeasurements: brianConfig.optionalMeasurements,
  dependencies: {
    backBase: 'base',
    frontBase: 'backBase',
    sleevecap: 'frontBase',
    sleeveBase: 'sleevecap',
    back: 'backBase',
    front: ['frontBase', 'back'],
    sleeve: ['sleeveBase', 'back'],
    pocket: 'front',
    hood: ['front', 'back'],
  },
  inject: {
    backBase: 'base',
    frontBase: 'backBase',
    sleeveBase: 'sleevecap',
    back: 'backBase',
    front: 'frontBase',
    sleeve: 'sleeveBase',
    pocket: 'front',
  },
  hide: ['base', 'sleevecap', 'backBase', 'frontBase', 'sleeveBase'],
  parts: ['hood', 'waistband', 'cuff'],
  options: {
    ...brianConfig.options,

    // Specific to Huey
    ribbing: { bool: true },
    pocket: { bool: true },
    ribbingHeight: { pct: 10, min: 5, max: 15 },
    pocketHeight: { pct: 30, min: 25, max: 35 },
    pocketWidth: { pct: 60, min: 50, max: 70 },
    hipsEase: { pct: 8, min: 4, max: 12 },
    hoodHeight: { pct: 59, min: 55, max: 65 },
    hoodCutback: { pct: 10, min: 5, max: 15 },
    hoodClosure: { pct: 13.5, min: 10, max: 15 },
    hoodDepth: { pct: 8.5, min: 5, max: 12 },
    ribbingStretch: { pct: 15, min: 0, max: 30 },
    hoodAngle: { deg: 5, min: 2, max: 8 },
  },
}
