export default {
  men: {
    manSize34: {
      bicepsCircumference: 335,
      centerBackNeckToWaist: 489,
      chestCircumference: 849,
      headCircumference: 570,
      hipsCircumference: 722,
      hipsToUpperLeg: 183,
      naturalWaistToHip: 100,
      neckCircumference: 366,
      shoulderSlope: 43,
      shoulderToShoulder: 419,
      shoulderToWrist: 670,
      upperLegCircumference: 565,
      wristCircumference: 175
    },
    manSize36: {
      bicepsCircumference: 290,
      centerBackNeckToWaist: 492,
      chestCircumference: 907,
      headCircumference: 575,
      hipsCircumference: 780,
      hipsToUpperLeg: 193,
      naturalWaistToHip: 105,
      neckCircumference: 378,
      shoulderSlope: 46,
      shoulderToShoulder: 431,
      shoulderToWrist: 675,
      upperLegCircumference: 582,
      wristCircumference: 180
    },
    manSize38: {
      bicepsCircumference: 305,
      centerBackNeckToWaist: 495,
      chestCircumference: 965,
      headCircumference: 580,
      hipsCircumference: 838,
      hipsToUpperLeg: 202,
      naturalWaistToHip: 110,
      neckCircumference: 391,
      shoulderSlope: 49,
      shoulderToShoulder: 444,
      shoulderToWrist: 680,
      upperLegCircumference: 598,
      wristCircumference: 185
    },
    manSize40: {
      bicepsCircumference: 320,
      centerBackNeckToWaist: 498,
      chestCircumference: 1023,
      headCircumference: 585,
      hipsCircumference: 896,
      hipsToUpperLeg: 211,
      naturalWaistToHip: 115,
      neckCircumference: 404,
      shoulderSlope: 52,
      shoulderToShoulder: 457,
      shoulderToWrist: 685,
      upperLegCircumference: 614,
      wristCircumference: 190
    },
    manSize42: {
      bicepsCircumference: 335,
      centerBackNeckToWaist: 501,
      chestCircumference: 1081,
      headCircumference: 590,
      hipsCircumference: 895,
      hipsToUpperLeg: 220,
      naturalWaistToHip: 120,
      neckCircumference: 416,
      shoulderSlope: 55,
      shoulderToShoulder: 470,
      shoulderToWrist: 690,
      upperLegCircumference: 630,
      wristCircumference: 195
    },
    manSize44: {
      bicepsCircumference: 350,
      centerBackNeckToWaist: 505,
      chestCircumference: 1139,
      headCircumference: 595,
      hipsCircumference: 1012,
      hipsToUpperLeg: 229,
      naturalWaistToHip: 125,
      neckCircumference: 429,
      shoulderSlope: 58,
      shoulderToShoulder: 483,
      shoulderToWrist: 700,
      upperLegCircumference: 646,
      wristCircumference: 200
    }
  }
};
