/*
 * This file was auto-generated by the prebuild script
 * Any changes you make to it will be lost on the next (pre)build.
 */
import { siteNav as en } from './sitenav.en.mjs'
import { siteNav as fr } from './sitenav.fr.mjs'
import { siteNav as es } from './sitenav.es.mjs'
import { siteNav as de } from './sitenav.de.mjs'
import { siteNav as nl } from './sitenav.nl.mjs'
import { siteNav as uk } from './sitenav.uk.mjs'
export const siteNav = { en,fr,es,de,nl,uk }