cp aaron/i18n/index.mjs aaron/i18n/index.mjs
cp aaron/i18n/index.mjs albert/i18n/index.mjs
cp aaron/i18n/index.mjs bee/i18n/index.mjs
cp aaron/i18n/index.mjs bella/i18n/index.mjs
cp aaron/i18n/index.mjs benjamin/i18n/index.mjs
cp aaron/i18n/index.mjs bent/i18n/index.mjs
cp aaron/i18n/index.mjs bibi/i18n/index.mjs
cp aaron/i18n/index.mjs bob/i18n/index.mjs
cp aaron/i18n/index.mjs breanna/i18n/index.mjs
cp aaron/i18n/index.mjs brian/i18n/index.mjs
cp aaron/i18n/index.mjs bruce/i18n/index.mjs
cp aaron/i18n/index.mjs carlita/i18n/index.mjs
cp aaron/i18n/index.mjs carlton/i18n/index.mjs
cp aaron/i18n/index.mjs cathrin/i18n/index.mjs
cp aaron/i18n/index.mjs charlie/i18n/index.mjs
cp aaron/i18n/index.mjs cornelius/i18n/index.mjs
cp aaron/i18n/index.mjs diana/i18n/index.mjs
cp aaron/i18n/index.mjs examples/i18n/index.mjs
cp aaron/i18n/index.mjs florence/i18n/index.mjs
cp aaron/i18n/index.mjs florent/i18n/index.mjs
cp aaron/i18n/index.mjs gozer/i18n/index.mjs
cp aaron/i18n/index.mjs hi/i18n/index.mjs
cp aaron/i18n/index.mjs holmes/i18n/index.mjs
cp aaron/i18n/index.mjs hortensia/i18n/index.mjs
cp aaron/i18n/index.mjs huey/i18n/index.mjs
cp aaron/i18n/index.mjs hugo/i18n/index.mjs
cp aaron/i18n/index.mjs jaeger/i18n/index.mjs
cp aaron/i18n/index.mjs jane/i18n/index.mjs
cp aaron/i18n/index.mjs legend/i18n/index.mjs
cp aaron/i18n/index.mjs lily/i18n/index.mjs
cp aaron/i18n/index.mjs lucy/i18n/index.mjs
cp aaron/i18n/index.mjs lumina/i18n/index.mjs
cp aaron/i18n/index.mjs lumira/i18n/index.mjs
cp aaron/i18n/index.mjs lunetius/i18n/index.mjs
cp aaron/i18n/index.mjs magde/i18n/index.mjs
cp aaron/i18n/index.mjs noble/i18n/index.mjs
cp aaron/i18n/index.mjs octoplushy/i18n/index.mjs
cp aaron/i18n/index.mjs onyx/i18n/index.mjs
cp aaron/i18n/index.mjs opal/i18n/index.mjs
cp aaron/i18n/index.mjs otis/i18n/index.mjs
cp aaron/i18n/index.mjs paco/i18n/index.mjs
cp aaron/i18n/index.mjs penelope/i18n/index.mjs
cp aaron/i18n/index.mjs plugintest/i18n/index.mjs
cp aaron/i18n/index.mjs rendertest/i18n/index.mjs
cp aaron/i18n/index.mjs sandy/i18n/index.mjs
cp aaron/i18n/index.mjs shelly/i18n/index.mjs
cp aaron/i18n/index.mjs shin/i18n/index.mjs
cp aaron/i18n/index.mjs simon/i18n/index.mjs
cp aaron/i18n/index.mjs simone/i18n/index.mjs
cp aaron/i18n/index.mjs skully/i18n/index.mjs
cp aaron/i18n/index.mjs sven/i18n/index.mjs
cp aaron/i18n/index.mjs tamiko/i18n/index.mjs
cp aaron/i18n/index.mjs teagan/i18n/index.mjs
cp aaron/i18n/index.mjs tiberius/i18n/index.mjs
cp aaron/i18n/index.mjs titan/i18n/index.mjs
cp aaron/i18n/index.mjs trayvon/i18n/index.mjs
cp aaron/i18n/index.mjs tristan/i18n/index.mjs
cp aaron/i18n/index.mjs uma/i18n/index.mjs
cp aaron/i18n/index.mjs umbra/i18n/index.mjs
cp aaron/i18n/index.mjs wahid/i18n/index.mjs
cp aaron/i18n/index.mjs walburga/i18n/index.mjs
cp aaron/i18n/index.mjs waralee/i18n/index.mjs
cp aaron/i18n/index.mjs yuri/i18n/index.mjs
