/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
import de as deNamespaces from "./next/de/index.mjs"
import en as enNamespaces from "./next/en/index.mjs"
import es as esNamespaces from "./next/es/index.mjs"
import fr as frNamespaces from "./next/fr/index.mjs"
import nl as nlNamespaces from "./next/nl/index.mjs"

export const de = deNamespaces
export const en = enNamespaces
export const es = esNamespaces
export const fr = frNamespaces
export const nl = nlNamespaces
