/*
 * This file is auto-generated by the prebuild script
 * All edits will be overwritten on the next (pre)build
 */
import deNamespaces from "./next/de/index.mjs"
import enNamespaces from "./next/en/index.mjs"
import esNamespaces from "./next/es/index.mjs"
import frNamespaces from "./next/fr/index.mjs"
import nlNamespaces from "./next/nl/index.mjs"

export const de = deNamespaces
export const en = enNamespaces
export const es = esNamespaces
export const fr = frNamespaces
export const nl = nlNamespaces

export const languages = {
  de: "Deutsch",
  en: "English",
  es: "Español",
  fr: "Français",
  nl: "Nederlands"
}
