import pkg from '../package.json'

export default {
  name: 'hugo',
  version: pkg.version,
  design: 'Joost De Cock',
  code: 'Joost De Cock',
  department: 'tops',
  type: 'pattern',
  difficulty: 3,
  optionGroups: {
    fit: ['bicepsEase', 'chestEase', 'cuffEase', 'hipsEase', 'ribbingStretch'],
    style: ['lengthBonus', 'sleeveLengthBonus', 'ribbingHeight'],
    advanced: ['acrossBackFactor', 'backNeckCutout'],
  },
  measurements: [
    'biceps',
    'chest',
    'head',
    'hips',
    'hpsToWaistBack',
    'waistToHips',
    'neck',
    'shoulderSlope',
    'shoulderToShoulder',
    'shoulderToWrist',
    'wrist',
  ],
  parts: ['waistband', 'cuff'],
  dependencies: {
    frontBase: 'base',
    front: 'frontBase',
    backBase: 'base',
    back: ['backBase', 'front'],
    sleevecap: 'front',
    sleeveBase: 'sleevecap',
    sleeve: ['sleeveBase', 'front', 'back'],
    pocket: 'front',
    pocketFacing: 'pocket',
    hoodCenter: 'hoodSide',
    hoodSide: ['front', 'back'],
  },
  inject: {
    frontBase: 'base',
    front: 'frontBase',
    backBase: 'base',
    back: 'backBase',
    sleeveBase: 'sleevecap',
    sleeve: 'sleeveBase',
    pocket: 'front',
    pocketFacing: 'pocket',
  },
  hide: ['base', 'frontBase', 'backBase', 'sleeveBase', 'sleevecap'],
  options: {
    // Constants
    brianFitCollar: false,
    brianFitSleeve: false,
    collarEase: 0.05,
    collarFactor: 4.3,
    armholeDepthFactor: 0.5,
    shoulderEase: 0,
    shoulderSlopeReduction: 0,
    frontArmholeDeeper: 0,
    sleevecapEase: 0,
    sleevecapTopFactorX: 0.5,
    sleevecapTopFactorY: 1,
    sleevecapBackFactorX: 0.5,
    sleevecapBackFactorY: 0.35,
    sleevecapFrontFactorX: 0.5,
    sleevecapFrontFactorY: 0.35,
    sleevecapQ1Offset: 0.03,
    sleevecapQ2Offset: 0,
    sleevecapQ3Offset: 0,
    sleevecapQ4Offset: 0.03,
    sleevecapQ1Spread1: 0.05,
    sleevecapQ1Spread2: 0.05,
    sleevecapQ2Spread1: 0.05,
    sleevecapQ2Spread2: 0.05,
    sleevecapQ3Spread1: 0.05,
    sleevecapQ3Spread2: 0.05,
    sleevecapQ4Spread1: 0.05,
    sleevecapQ4Spread2: 0.05,
    sleeveWidthGuarantee: 1,
    s3Collar: 0,
    s3Armhole: 0,

    // Percentages
    acrossBackFactor: { pct: 97, min: 93, max: 100 },
    backNeckCutout: { pct: 5, min: 2, max: 8 },
    bicepsEase: { pct: 15, min: 0, max: 50 },
    chestEase: { pct: 8, min: 4, max: 20 },
    hipsEase: { pct: 12, min: 4, max: 20 },
    cuffEase: { pct: 20, min: 10, max: 50 },
    lengthBonus: { pct: 10, min: 0, max: 20 },
    sleeveLengthBonus: { pct: 2, min: 0, max: 10 },
    ribbingStretch: { pct: 5, min: 0, max: 10 },
    ribbingHeight: { pct: 10, min: 4, max: 20 },
  },
}
