name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi there 😃

          Since this is your first issue here, please take a moment to read how we use issues.

          If there's something not working, wrong, broken, or confusing, you came to the right place.

          If it's help or support you're looking for,
          please join our Discord server at https://discord.freesewing.org/
          rather than creating an issue.

          Also, you can support FreeSewing via https://freesewing.org/patrons/join/

          ♥

        pr-message: |
          Hi there 👋

          Thank you for submitting a pull request.

          Please note that our code of conduct lives at
            https://freesewing.dev/contributors/code-of-conduct/

