name: Unit tests - Tutorial

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/tutorial/**'
      - '!packages/tutorial/README.md'
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/tutorial/**'
      - '!packages/tutorial/README.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd packages/tutorial && npm install
        env:
          CI: true
      - name: Install peer & test dependencies
        run: "cd packages/tutorial && npm install @freesewing/core@^2.19.9 @freesewing/plugin-bundle@^2.19.9 @freesewing/models@2.19.9 @freesewing/pattern-info@2.19.9 mocha chai"
        env:
          CI: true
      - name: Build pattern
        run: cd packages/tutorial && npm run build
      - name: Run pattern unit tests
        run: cd packages/tutorial && npm run testci
